export interface PYQReference {
  ncertChapter: string;
  ncertTopic: string;
  ncertPage: string;
  ncertExemplar?: string;
  source: 'NCERT' | 'NCERT Exemplar' | 'CBSE PYQ';
}

export interface PYQQuestion {
  id: string;
  year: string;
  marks: 1 | 2 | 3 | 5;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  topic: string;
  question: string;
  modelAnswer: string;
  answerTips: string[];
  reference: PYQReference;
  isFrequent: boolean;
}

export interface PYQChapterData {
  chapterSlug: string;
  frequentlyRepeatedConcepts: string[];
  answerWritingTips: string[];
  relatedNCERTTopics: string[];
  relatedNCERTExemplarTopics: string[];
  questions: PYQQuestion[];
}

export const pyqSeries: Record<string, PYQChapterData> = {
  'chemical-reactions': {
    chapterSlug: 'chemical-reactions',
    frequentlyRepeatedConcepts: [
      'Balancing chemical equations',
      'Identification of oxidation and reduction',
      'Types of reactions (combination, decomposition, displacement, double displacement)',
      'Exothermic vs endothermic reactions',
      'Corrosion and rancidity prevention',
    ],
    answerWritingTips: [
      'Always write balanced equations with physical states (s), (l), (g), (aq)',
      'Use arrows: ↑ for gas evolved, ↓ for precipitate formed',
      'Define the reaction type before giving the example',
      'For redox questions, clearly state which substance is oxidised and which is reduced',
    ],
    relatedNCERTTopics: ['Chemical Equations', 'Types of Chemical Reactions', 'Oxidation and Reduction', 'Effects of Oxidation in Everyday Life'],
    relatedNCERTExemplarTopics: ['Balancing Equations', 'Types of Reactions', 'Redox Identification'],
    questions: [
      {
        id: 'cr-q1',
        year: '2023',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Types of Reactions',
        question: 'Identify the type of reaction: CaO + H₂O → Ca(OH)₂ + heat',
        modelAnswer: 'This is a combination reaction. Two reactants (CaO and H₂O) combine to form a single product Ca(OH)₂. It is also exothermic since heat is released.',
        answerTips: ['Mention both combination and exothermic if applicable', 'State the definition before identifying'],
        reference: { ncertChapter: 'Chemical Reactions and Equations', ncertTopic: 'Types of Chemical Reactions', ncertPage: 'p. 6', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cr-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Balancing Equations',
        question: 'Balance the equation: Fe + H₂O → Fe₃O₄ + H₂',
        modelAnswer: '3Fe + 4H₂O → Fe₃O₄ + 4H₂. Count: Fe = 3 on both sides, O = 4 on both sides, H = 8 on both sides.',
        answerTips: ['Start with the most complex compound (Fe₃O₄)', 'Verify atom count on both sides'],
        reference: { ncertChapter: 'Chemical Reactions and Equations', ncertTopic: 'Writing Chemical Equations', ncertPage: 'p. 3', source: 'NCERT' },
        isFrequent: true,
      },
      {
        id: 'cr-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Oxidation-Reduction',
        question: 'In the reaction CuO + H₂ → Cu + H₂O, identify the substance oxidised, the substance reduced, the oxidising agent, and the reducing agent.',
        modelAnswer: 'H₂ is oxidised to H₂O (gains oxygen) → H₂ is the reducing agent. CuO is reduced to Cu (loses oxygen) → CuO is the oxidising agent.',
        answerTips: ['Substance that gains oxygen = oxidised = reducing agent', 'Substance that loses oxygen = reduced = oxidising agent'],
        reference: { ncertChapter: 'Chemical Reactions and Equations', ncertTopic: 'Oxidation and Reduction', ncertPage: 'p. 12', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cr-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Decomposition Reactions',
        question: 'Why does silver chloride turn grey when kept in sunlight? Write the balanced equation and state the type of reaction.',
        modelAnswer: 'Silver chloride (AgCl) decomposes in sunlight to form silver metal and chlorine gas: 2AgCl → 2Ag + Cl₂. This is a photodecomposition reaction (decomposition by light). The white AgCl turns grey due to the formation of metallic silver. This is used in black-and-white photography.',
        answerTips: ['Name the reaction type: photodecomposition', 'Mention the application in photography'],
        reference: { ncertChapter: 'Chemical Reactions and Equations', ncertTopic: 'Decomposition Reactions', ncertPage: 'p. 8', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cr-q5',
        year: '2019',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Corrosion and Rancidity',
        question: '(a) What is corrosion? Give one example. (b) What is rancidity? (c) Suggest two methods to prevent corrosion and two to prevent rancidity.',
        modelAnswer: '(a) Corrosion is the slow degradation of metals by the action of air and moisture. Example: Rusting of iron (Fe₂O₃·xH₂O). (b) Rancidity is the oxidation of fats and oils producing unpleasant smell and taste. (c) Corrosion prevention: painting, galvanisation, oiling, alloying. Rancidity prevention: adding antioxidants, storing in airtight containers, refrigeration, nitrogen flushing.',
        answerTips: ['Give 2 methods each for full marks', 'Use the term "oxidation" when explaining rancidity'],
        reference: { ncertChapter: 'Chemical Reactions and Equations', ncertTopic: 'Effects of Oxidation in Everyday Life', ncertPage: 'p. 15', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cr-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Exothermic Reactions',
        question: 'Why is respiration considered an exothermic reaction?',
        modelAnswer: 'During respiration, glucose combines with oxygen to release a large amount of energy: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy. Since energy is released, it is exothermic.',
        answerTips: ['Write the balanced equation', 'Emphasise that energy is released'],
        reference: { ncertChapter: 'Chemical Reactions and Equations', ncertTopic: 'Exothermic and Endothermic Reactions', ncertPage: 'p. 5', source: 'CBSE PYQ' },
        isFrequent: true,
      },
    ],
  },

  'acids-bases-salts': {
    chapterSlug: 'acids-bases-salts',
    frequentlyRepeatedConcepts: [
      'pH scale and everyday applications',
      'Important salts (NaHCO₃, Na₂CO₃, CaOCl₂, CaSO₄·½H₂O)',
      'Chlor-alkali process',
      'Acid-base indicators and colour changes',
      'Neutralisation reactions',
    ],
    answerWritingTips: [
      'Always write chemical formulas with correct subscripts',
      'For pH questions, mention the numerical value and whether it is acidic/basic/neutral',
      'When describing salts, give both the chemical name and formula',
    ],
    relatedNCERTTopics: ['Acids and Bases', 'pH Scale', 'Salts', 'Plaster of Paris', 'Chlor-Alkali Process'],
    relatedNCERTExemplarTopics: ['pH Calculations', 'Salt Identification', 'Indicator Colours'],
    questions: [
      {
        id: 'ab-q1',
        year: '2023',
        marks: 1,
        difficulty: 'Easy',
        topic: 'pH Scale',
        question: 'Fresh milk has a pH of 6. When it changes to curd, will the pH increase or decrease? Why?',
        modelAnswer: 'The pH will decrease (become more acidic). When milk turns to curd, lactic acid is produced by bacteria. The presence of acid lowers the pH below 6.',
        answerTips: ['State the direction of pH change', 'Explain that lactic acid is produced'],
        reference: { ncertChapter: 'Acids, Bases and Salts', ncertTopic: 'pH Scale', ncertPage: 'p. 25', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'ab-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Plaster of Paris',
        question: 'Write the chemical formula of Plaster of Paris. Why must it be stored in a moisture-proof container?',
        modelAnswer: 'Formula: CaSO₄·½H₂O (calcium sulphate hemihydrate). It must be stored in a moisture-proof container because it absorbs water from the air and sets into hard gypsum (CaSO₄·2H₂O), making it unusable.',
        answerTips: ['Write the full formula with the water of crystallisation', 'Mention the product gypsum'],
        reference: { ncertChapter: 'Acids, Bases and Salts', ncertTopic: 'Plaster of Paris', ncertPage: 'p. 33', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'ab-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Chlor-Alkali Process',
        question: 'Explain the chlor-alkali process. Write the balanced equation and state the three products and their uses.',
        modelAnswer: 'When electricity is passed through brine (NaCl solution), it decomposes to form NaOH, Cl₂, and H₂. Equation: 2NaCl + 2H₂O → 2NaOH + Cl₂↑ + H₂↑. Uses: NaOH — soap, paper; Cl₂ — water treatment, PVC; H₂ — fuel, hydrogenation of oils.',
        answerTips: ['Write the balanced equation', 'List all 3 products with at least one use each'],
        reference: { ncertChapter: 'Acids, Bases and Salts', ncertTopic: 'Chlor-Alkali Process', ncertPage: 'p. 35', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'ab-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Indicators',
        question: 'A student tests three solutions with litmus paper. Solution A turns red litmus blue, solution B turns blue litmus red, and solution C does not change either. Identify the nature of each solution and give one example.',
        modelAnswer: 'Solution A is basic (e.g., NaOH — turns red litmus blue). Solution B is acidic (e.g., HCl — turns blue litmus red). Solution C is neutral (e.g., NaCl solution or pure water — no colour change).',
        answerTips: ['Identify acid/base/neutral for each', 'Give a real example for each'],
        reference: { ncertChapter: 'Acids, Bases and Salts', ncertTopic: 'Acids and Bases', ncertPage: 'p. 18', source: 'NCERT' },
        isFrequent: false,
      },
      {
        id: 'ab-q5',
        year: '2019',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Salt Preparation and Uses',
        question: '(a) Write the chemical formula and one use each for: baking soda, washing soda, bleaching powder. (b) How is bleaching powder prepared? Write the equation.',
        modelAnswer: '(a) Baking soda: NaHCO₃ — used in baking (releases CO₂). Washing soda: Na₂CO₃·10H₂O — used in glass and soap making. Bleaching powder: CaOCl₂ — used for bleaching cotton and disinfecting water. (b) Bleaching powder is prepared by the action of chlorine on dry slaked lime: Ca(OH)₂ + Cl₂ → CaOCl₂ + H₂O.',
        answerTips: ['Give formula + use for each salt', 'Write the preparation equation for bleaching powder'],
        reference: { ncertChapter: 'Acids, Bases and Salts', ncertTopic: 'Salts', ncertPage: 'p. 30', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'ab-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Neutralisation',
        question: 'What happens when an acid reacts with a base? Give one example with equation.',
        modelAnswer: 'Acid + Base → Salt + Water (neutralisation). Example: HCl + NaOH → NaCl + H₂O. The reaction is exothermic.',
        answerTips: ['State the general equation', 'Give a specific example with equation'],
        reference: { ncertChapter: 'Acids, Bases and Salts', ncertTopic: 'Neutralisation', ncertPage: 'p. 22', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'metals-non-metals': {
    chapterSlug: 'metals-non-metals',
    frequentlyRepeatedConcepts: [
      'Reactivity series and displacement reactions',
      'Extraction of metals (roasting, calcination, electrolytic reduction)',
      'Properties of ionic compounds',
      'Corrosion and galvanisation',
      'Alloys and their composition',
    ],
    answerWritingTips: [
      'For extraction questions, mention the reactivity level of the metal',
      'Differentiate roasting (sulphide ores, with O₂) from calcination (carbonate ores, without O₂)',
      'For ionic compounds, mention high melting point, solubility, and conductivity',
    ],
    relatedNCERTTopics: ['Physical Properties', 'Chemical Properties', 'Reactivity Series', 'Extraction of Metals', 'Corrosion', 'Alloys'],
    relatedNCERTExemplarTopics: ['Reactivity Series', 'Ionic vs Covalent', 'Extraction Methods'],
    questions: [
      {
        id: 'mn-q1',
        year: '2023',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Reactivity Series',
        question: 'Why can copper not displace zinc from zinc sulphate solution?',
        modelAnswer: 'Copper is less reactive than zinc. In the reactivity series, zinc is above copper. Only a more reactive metal can displace a less reactive metal from its salt solution.',
        answerTips: ['Reference the reactivity series', 'State the rule of displacement'],
        reference: { ncertChapter: 'Metals and Non-metals', ncertTopic: 'Reactivity Series', ncertPage: 'p. 48', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'mn-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Ionic Compounds',
        question: 'Give two properties of ionic compounds.',
        modelAnswer: '1. High melting and boiling points due to strong electrostatic forces between ions. 2. Conduct electricity in molten or aqueous state (ions become free to move) but not in solid state.',
        answerTips: ['Give at least 2 distinct properties', 'Explain why (strong electrostatic forces)'],
        reference: { ncertChapter: 'Metals and Non-metals', ncertTopic: 'Ionic Compounds', ncertPage: 'p. 52', source: 'NCERT' },
        isFrequent: true,
      },
      {
        id: 'mn-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Extraction of Metals',
        question: 'Differentiate between roasting and calcination with one example each.',
        modelAnswer: 'Roasting: Sulphide ores are heated strongly in the presence of excess air to convert them to oxides. Example: 2ZnS + 3O₂ → 2ZnO + 2SO₂. Calcination: Carbonate ores are heated strongly in the absence of air to convert them to oxides. Example: ZnCO₃ → ZnO + CO₂.',
        answerTips: ['Roasting = with O₂, for sulphide ores', 'Calcination = without O₂, for carbonate ores', 'Give balanced equations'],
        reference: { ncertChapter: 'Metals and Non-metals', ncertTopic: 'Extraction of Metals', ncertPage: 'p. 55', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'mn-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Corrosion',
        question: 'What is galvanisation? Why is it done? Why is zinc used instead of copper?',
        modelAnswer: 'Galvanisation is coating iron with a thin layer of zinc. It prevents rusting. Zinc is used because it is more reactive than iron — it oxidises first (sacrificial protection). Copper is less reactive than iron, so it would not protect iron; instead, iron would corrode faster.',
        answerTips: ['Define galvanisation', 'Explain sacrificial protection', 'Explain why zinc, not copper'],
        reference: { ncertChapter: 'Metals and Non-metals', ncertTopic: 'Corrosion', ncertPage: 'p. 58', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'mn-q5',
        year: '2019',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Extraction of Metals',
        question: 'Describe the steps involved in the extraction of metals of high, medium, and low reactivity. Give one example each.',
        modelAnswer: 'High reactivity (Na, K, Ca, Al): Extracted by electrolytic reduction of their molten salts. Example: Na is obtained by electrolysis of molten NaCl. Medium reactivity (Zn, Fe, Pb): Extracted by roasting/calcination followed by reduction with carbon. Example: ZnO + C → Zn + CO. Low reactivity (Cu, Ag, Au): Found in native state or extracted by roasting alone. Example: Cu₂S + O₂ → 2Cu + SO₂.',
        answerTips: ['Group by reactivity level', 'Give the extraction method and example for each'],
        reference: { ncertChapter: 'Metals and Non-metals', ncertTopic: 'Extraction of Metals', ncertPage: 'p. 54', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'mn-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Alloys',
        question: 'What is an alloy? Name the constituents of brass.',
        modelAnswer: 'An alloy is a homogeneous mixture of two or more metals, or a metal and a non-metal. Brass is an alloy of copper (60-80%) and zinc (20-40%).',
        answerTips: ['Define alloy', 'Give the composition of brass'],
        reference: { ncertChapter: 'Metals and Non-metals', ncertTopic: 'Alloys', ncertPage: 'p. 61', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'carbon-compounds': {
    chapterSlug: 'carbon-compounds',
    frequentlyRepeatedConcepts: [
      'Functional groups and IUPAC naming',
      'Homologous series (alkanes, alkenes, alkynes)',
      'Esterification and saponification',
      'Soaps vs detergents in hard water',
      'Hydrogenation of oils',
    ],
    answerWritingTips: [
      'Draw structures when asked about functional groups',
      'Write balanced equations for esterification and saponification',
      'For soap/detergent questions, explain micelle formation',
    ],
    relatedNCERTTopics: ['Bonding in Carbon', 'Hydrocarbons', 'Functional Groups', 'Soaps and Detergents'],
    relatedNCERTExemplarTopics: ['IUPAC Naming', 'Functional Group Identification', 'Esterification'],
    questions: [
      {
        id: 'cc-q1',
        year: '2023',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Functional Groups',
        question: 'Identify the functional group present in CH₃COOH and C₂H₅OH.',
        modelAnswer: 'CH₃COOH (ethanoic acid) has the carboxylic acid group (–COOH). C₂H₅OH (ethanol) has the alcohol group (–OH).',
        answerTips: ['Name the functional group, not just the compound', 'Use correct notation: –COOH, –OH'],
        reference: { ncertChapter: 'Carbon and Its Compounds', ncertTopic: 'Functional Groups', ncertPage: 'p. 71', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Homologous Series',
        question: 'Write the general formula of alkanes. Give the molecular formula of the alkane with 4 carbon atoms.',
        modelAnswer: 'General formula of alkanes: CₙH₂ₙ₊₂. For n = 4: C₄H₂(4)+2 = C₄H₁₀ (butane).',
        answerTips: ['State the general formula', 'Substitute n correctly'],
        reference: { ncertChapter: 'Carbon and Its Compounds', ncertTopic: 'Hydrocarbons', ncertPage: 'p. 68', source: 'NCERT' },
        isFrequent: true,
      },
      {
        id: 'cc-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Esterification',
        question: 'What is esterification? Write the equation for the reaction between ethanoic acid and ethanol. Name the product and state one characteristic property.',
        modelAnswer: 'Esterification is the reaction between a carboxylic acid and an alcohol in the presence of conc. H₂SO₄ to form an ester and water. Equation: CH₃COOH + C₂H₅OH →(conc. H₂SO₄)→ CH₃COOC₂H₅ + H₂O. The product is ethyl ethanoate, which has a sweet fruity smell.',
        answerTips: ['Write the equation with the catalyst above the arrow', 'Name the ester and mention its smell'],
        reference: { ncertChapter: 'Carbon and Its Compounds', ncertTopic: 'Chemical Properties of Carbon Compounds', ncertPage: 'p. 75', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Soaps and Detergents',
        question: 'Why are soaps ineffective in hard water while detergents are effective? Explain with the chemical reason.',
        modelAnswer: 'Hard water contains Ca²⁺ and Mg²⁺ ions. Soap (sodium salt of fatty acid) reacts with these ions to form insoluble scum (calcium/magnesium salt of fatty acid), which prevents lathering. Detergents have sulphonate heads that do not form insoluble salts with Ca²⁺/Mg²⁺, so they lather even in hard water.',
        answerTips: ['Mention Ca²⁺ and Mg²⁺ ions', 'Explain scum formation for soap', 'Explain why detergents do not form scum'],
        reference: { ncertChapter: 'Carbon and Its Compounds', ncertTopic: 'Soaps and Detergents', ncertPage: 'p. 80', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q5',
        year: '2019',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Hydrogenation',
        question: '(a) What is hydrogenation? Write the equation. (b) Name the catalyst used and the temperature. (c) State one industrial application.',
        modelAnswer: '(a) Hydrogenation is the addition of hydrogen to unsaturated hydrocarbons (C=C) in the presence of a catalyst to form saturated hydrocarbons. Equation: C₂H₄ + H₂ →(Ni, 200°C)→ C₂H₆. (b) Catalyst: Nickel (Ni), temperature: ~200°C. (c) Industrial application: conversion of liquid vegetable oils into solid fats (vanaspati ghee / margarine).',
        answerTips: ['Write the equation with catalyst and temperature', 'Mention the industrial application clearly'],
        reference: { ncertChapter: 'Carbon and Its Compounds', ncertTopic: 'Chemical Properties of Carbon Compounds', ncertPage: 'p. 74', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Covalent Bonding',
        question: 'Why does carbon form covalent bonds and not ionic bonds?',
        modelAnswer: 'Carbon has 4 valence electrons. It cannot lose 4 electrons (too much energy required) or gain 4 electrons (nucleus cannot hold 10 electrons). So it shares electrons, forming covalent bonds.',
        answerTips: ['Mention 4 valence electrons', 'Explain why losing/gaining 4 electrons is not possible'],
        reference: { ncertChapter: 'Carbon and Its Compounds', ncertTopic: 'Bonding in Carbon', ncertPage: 'p. 62', source: 'NCERT' },
        isFrequent: true,
      },
    ],
  },

  'periodic-classification': {
    chapterSlug: 'periodic-classification',
    frequentlyRepeatedConcepts: [
      'Modern periodic law and table structure',
      'Trends: atomic size, metallic character',
      'Mendeleev vs modern periodic table',
      'Groups and periods relationship',
    ],
    answerWritingTips: [
      'State the periodic law clearly (Moseley: atomic number basis)',
      'For trends, explain the reason (nuclear charge, number of shells)',
      'Use specific element examples to illustrate trends',
    ],
    relatedNCERTTopics: ['Mendeleev\'s Periodic Table', 'Modern Periodic Table', 'Periodic Trends'],
    relatedNCERTExemplarTopics: ['Period/Group Determination', 'Trend Prediction'],
    questions: [
      {
        id: 'pc-q1',
        year: '2023',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Modern Periodic Table',
        question: 'State the modern periodic law.',
        modelAnswer: 'The properties of elements are a periodic function of their atomic numbers (proposed by Henry Moseley).',
        answerTips: ['Mention atomic number, not atomic mass', 'Credit Moseley'],
        reference: { ncertChapter: 'Periodic Classification of Elements', ncertTopic: 'Modern Periodic Table', ncertPage: 'p. 88', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'pc-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Periodic Trends',
        question: 'Why does atomic size decrease across a period from left to right?',
        modelAnswer: 'Across a period, the nuclear charge increases (more protons) while the number of shells remains the same. The stronger nuclear charge pulls the electrons closer to the nucleus, decreasing the atomic size.',
        answerTips: ['Mention increasing nuclear charge', 'Mention same number of shells'],
        reference: { ncertChapter: 'Periodic Classification of Elements', ncertTopic: 'Periodic Trends', ncertPage: 'p. 92', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'pc-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Mendeleev vs Modern',
        question: 'State two limitations of Mendeleev\'s periodic table. How were they overcome in the modern periodic table?',
        modelAnswer: '1. Position of isotopes: Mendeleev could not place isotopes (same properties, different atomic masses). Modern table places them in the same position (same atomic number). 2. Wrong order of atomic masses: Mendeleev placed Ar before K and Co before Ni based on properties, violating atomic mass order. Modern table arranges by atomic number, resolving this anomaly.',
        answerTips: ['Give 2 distinct limitations', 'Explain how the modern table fixes each'],
        reference: { ncertChapter: 'Periodic Classification of Elements', ncertTopic: 'Mendeleev\'s Periodic Table', ncertPage: 'p. 84', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'pc-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Electronic Configuration',
        question: 'An element has atomic number 17. (a) Write its electronic configuration. (b) Identify the period and group. (c) Name the element and state whether it is a metal or non-metal.',
        modelAnswer: '(a) Electronic configuration: 2, 8, 7. (b) Period 3 (3 shells), Group 17 (7 valence electrons). (c) The element is chlorine (Cl). It is a non-metal (has 7 valence electrons, tends to gain 1 electron).',
        answerTips: ['Write the full configuration', 'Explain how period and group are determined', 'State metal/non-metal with reasoning'],
        reference: { ncertChapter: 'Periodic Classification of Elements', ncertTopic: 'Modern Periodic Table', ncertPage: 'p. 90', source: 'NCERT' },
        isFrequent: true,
      },
      {
        id: 'pc-q5',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Groups and Periods',
        question: 'How many groups and periods are there in the modern periodic table?',
        modelAnswer: 'There are 18 groups (vertical columns) and 7 periods (horizontal rows) in the modern periodic table.',
        answerTips: ['State both numbers correctly: 18 groups, 7 periods'],
        reference: { ncertChapter: 'Periodic Classification of Elements', ncertTopic: 'Modern Periodic Table', ncertPage: 'p. 88', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'life-processes': {
    chapterSlug: 'life-processes',
    frequentlyRepeatedConcepts: [
      'Photosynthesis equation and factors',
      'Aerobic vs anaerobic respiration',
      'Human heart and double circulation',
      'Nephron structure and function',
      'Digestive enzymes and their action',
      'Xylem vs phloem transport',
    ],
    answerWritingTips: [
      'Write full balanced equations for photosynthesis and respiration with conditions above the arrow',
      'For heart questions, mention right = deoxygenated, left = oxygenated',
      'Draw and label diagrams when asked (heart, nephron, digestive system)',
    ],
    relatedNCERTTopics: ['Nutrition', 'Respiration', 'Transportation', 'Excretion'],
    relatedNCERTExemplarTopics: ['Photosynthesis Equation', 'Heart Structure', 'Nephron Function'],
    questions: [
      {
        id: 'lp-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Photosynthesis',
        question: 'Write the balanced equation for photosynthesis. State the role of chlorophyll and the two main stages of photosynthesis.',
        modelAnswer: 'Equation: 6CO₂ + 6H₂O →(sunlight, chlorophyll)→ C₆H₁₂O₆ + 6O₂. Chlorophyll absorbs sunlight and converts it to chemical energy. Two stages: (1) Light reaction — chlorophyll absorbs light, splits water into H and O, produces ATP and NADPH. (2) Dark reaction (Calvin cycle) — CO₂ is converted to glucose using ATP and NADPH.',
        answerTips: ['Write the equation with sunlight and chlorophyll above the arrow', 'Name both stages'],
        reference: { ncertChapter: 'Life Processes', ncertTopic: 'Nutrition — Photosynthesis', ncertPage: 'p. 98', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lp-q2',
        year: '2022',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Respiration',
        question: 'Differentiate between aerobic and anaerobic respiration (site, products, energy output).',
        modelAnswer: 'Aerobic: occurs in mitochondria, uses oxygen, products are CO₂ + H₂O + 38 ATP. Anaerobic: occurs in cytoplasm, no oxygen needed, products are lactic acid (muscles) or ethanol + CO₂ (yeast) + 2 ATP. Aerobic is more efficient.',
        answerTips: ['Compare in a table format', 'Mention ATP values (38 vs 2)'],
        reference: { ncertChapter: 'Life Processes', ncertTopic: 'Respiration', ncertPage: 'p. 108', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lp-q3',
        year: '2023',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Human Heart',
        question: 'Describe the human heart. Explain double circulation and its significance. Why is it necessary?',
        modelAnswer: 'The human heart has 4 chambers: right atrium, right ventricle, left atrium, left ventricle. Right side carries deoxygenated blood, left side carries oxygenated blood. Double circulation: blood passes through the heart twice in one cycle. (1) Pulmonary circulation: right ventricle → lungs → left atrium (blood gets oxygenated). (2) Systemic circulation: left ventricle → body → right atrium (blood delivers O₂ to tissues). Significance: it keeps oxygenated and deoxygenated blood separate, ensuring efficient oxygen supply to the body and maintaining high pressure for blood flow.',
        answerTips: ['Mention 4 chambers', 'Describe both circuits', 'Explain the significance (separation of blood, efficiency)'],
        reference: { ncertChapter: 'Life Processes', ncertTopic: 'Transportation', ncertPage: 'p. 118', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lp-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Excretion',
        question: 'Describe the structure and function of a nephron.',
        modelAnswer: 'The nephron is the functional unit of the kidney. It consists of: (1) Bowman\'s capsule — cup-shaped structure that contains the glomerulus (cluster of capillaries) where filtration occurs. (2) Tubule — the filtered fluid passes through the proximal tubule, Loop of Henle, and distal tubule where useful substances (glucose, amino acids, water) are reabsorbed. (3) Collecting duct — collects urine. Function: filtration of blood → reabsorption of useful substances → secretion of waste → urine formation.',
        answerTips: ['Name all parts: Bowman\'s capsule, glomerulus, tubule, collecting duct', 'Describe the 3 steps: filtration, reabsorption, secretion'],
        reference: { ncertChapter: 'Life Processes', ncertTopic: 'Excretion', ncertPage: 'p. 125', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lp-q5',
        year: '2019',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Digestion',
        question: 'What is the role of saliva in digestion of food?',
        modelAnswer: 'Saliva contains the enzyme salivary amylase which breaks down starch into maltose (sugar) in the mouth. It also moistens the food, making it easier to swallow.',
        answerTips: ['Name the enzyme: salivary amylase', 'State what it breaks down: starch → maltose'],
        reference: { ncertChapter: 'Life Processes', ncertTopic: 'Nutrition', ncertPage: 'p. 100', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lp-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Plant Transport',
        question: 'Which tissue transports food in plants? In which direction does it flow?',
        modelAnswer: 'Phloem transports food (sucrose) in plants. It flows bidirectionally (both upward and downward) from leaves (source) to all parts of the plant. It uses ATP energy for translocation.',
        answerTips: ['Name phloem', 'Mention bidirectional flow and ATP usage'],
        reference: { ncertChapter: 'Life Processes', ncertTopic: 'Transportation', ncertPage: 'p. 121', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'control-coordination': {
    chapterSlug: 'control-coordination',
    frequentlyRepeatedConcepts: [
      'Reflex action and reflex arc pathway',
      'Structure of neuron and synapse',
      'Parts of the brain and their functions',
      'Plant hormones and tropisms',
      'Endocrine glands and hormones',
    ],
    answerWritingTips: [
      'For reflex arc, trace the full pathway: receptor → sensory neuron → spinal cord → motor neuron → effector',
      'For brain parts, mention the specific function of each part',
      'For plant hormones, name the hormone and its specific action',
    ],
    relatedNCERTTopics: ['Nervous System', 'Reflex Action', 'Human Brain', 'Hormones in Animals', 'Plant Movement'],
    relatedNCERTExemplarTopics: ['Reflex Arc', 'Brain Parts', 'Plant Hormones'],
    questions: [
      {
        id: 'cc-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Reflex Action',
        question: 'What is a reflex action? Trace the pathway of a reflex arc. Why is it faster than a voluntary response?',
        modelAnswer: 'A reflex action is an involuntary, rapid response to a stimulus that does not involve the brain. Pathway: Receptor (skin) → Sensory neuron → Spinal cord → Motor neuron → Effector (muscle). This is faster than a voluntary response because the impulse does not travel to the brain for processing — it goes directly through the spinal cord.',
        answerTips: ['Define reflex action', 'Trace the full pathway', 'Explain why it is faster (brain bypassed)'],
        reference: { ncertChapter: 'Control and Coordination', ncertTopic: 'Reflex Action', ncertPage: 'p. 135', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Neuron Structure',
        question: 'Draw a labelled diagram of a neuron. Name the parts that receive and transmit impulses.',
        modelAnswer: 'A neuron consists of: Dendrites (receive impulses), Cell body (contains nucleus), Axon (transmits impulses), Myelin sheath (insulates axon), Nerve endings (pass impulse to next neuron or effector). Dendrites receive impulses; the axon transmits them.',
        answerTips: ['Label all parts', 'Specifically name dendrites (receive) and axon (transmit)'],
        reference: { ncertChapter: 'Control and Coordination', ncertTopic: 'Nervous System', ncertPage: 'p. 130', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Human Brain',
        question: 'Name the three main parts of the human brain. State one function of each.',
        modelAnswer: '1. Cerebrum — controls thinking, memory, reasoning, speech, and voluntary actions. 2. Cerebellum — controls balance, posture, and coordination of voluntary movements. 3. Medulla — controls involuntary functions like breathing, heart rate, and blood pressure.',
        answerTips: ['Name all 3 parts', 'Give one specific function for each'],
        reference: { ncertChapter: 'Control and Coordination', ncertTopic: 'Human Brain', ncertPage: 'p. 138', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Plant Hormones',
        question: 'Name five plant hormones. State one function of each.',
        modelAnswer: '1. Auxin — promotes cell elongation, causes phototropism. 2. Gibberellin — promotes stem growth and seed germination. 3. Cytokinin — promotes cell division, delays leaf ageing. 4. Abscisic acid — inhibits growth, closes stomata during water stress. 5. Ethylene — promotes fruit ripening and flower wilting.',
        answerTips: ['Name all 5 hormones', 'Give one specific function for each'],
        reference: { ncertChapter: 'Control and Coordination', ncertTopic: 'Plant Movement', ncertPage: 'p. 143', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q5',
        year: '2019',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Endocrine Glands',
        question: 'Why is the use of iodised salt advised?',
        modelAnswer: 'Iodine is essential for the thyroid gland to produce thyroxine hormone. Lack of iodine causes goitre (enlarged thyroid). Iodised salt prevents iodine deficiency and goitre.',
        answerTips: ['Mention thyroxine and goitre', 'Explain the cause-effect chain'],
        reference: { ncertChapter: 'Control and Coordination', ncertTopic: 'Hormones in Animals', ncertPage: 'p. 145', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'cc-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Synapse',
        question: 'What is a synapse? How do signals cross it?',
        modelAnswer: 'A synapse is the junction between two neurons. Electrical signals cannot cross the gap directly. Instead, the impulse triggers the release of chemical messengers called neurotransmitters, which diffuse across the synapse and initiate a new electrical impulse in the next neuron.',
        answerTips: ['Define synapse as a junction/gap', 'Mention neurotransmitters'],
        reference: { ncertChapter: 'Control and Coordination', ncertTopic: 'Nervous System', ncertPage: 'p. 133', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'reproduction': {
    chapterSlug: 'reproduction',
    frequentlyRepeatedConcepts: [
      'Human reproductive system',
      'Pollination and fertilisation in plants',
      'Menstrual cycle',
      'Asexual reproduction methods',
      'DNA copying and variation',
    ],
    answerWritingTips: [
      'For plant reproduction, trace the path from pollination to fertilisation',
      'For human reproduction, mention the site of fertilisation (fallopian tube)',
      'Give specific examples for asexual reproduction methods',
    ],
    relatedNCERTTopics: ['Asexual Reproduction', 'Sexual Reproduction in Plants', 'Reproduction in Humans', 'Reproductive Health'],
    relatedNCERTExemplarTopics: ['Asexual Methods', 'Flower Parts', 'Menstrual Cycle'],
    questions: [
      {
        id: 'rp-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Asexual Reproduction',
        question: 'Name four methods of asexual reproduction. Give one example of each.',
        modelAnswer: '1. Binary fission — Amoeba (parent divides into two equal daughter cells). 2. Budding — Hydra (outgrowth grows and detaches). 3. Fragmentation — Spirogyra (body breaks into fragments, each regrows). 4. Spore formation — Rhizopus (bread mould, spores germinate under favourable conditions).',
        answerTips: ['Name 4 methods', 'Give a specific organism for each'],
        reference: { ncertChapter: 'How do Organisms Reproduce?', ncertTopic: 'Asexual Reproduction', ncertPage: 'p. 155', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'rp-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Plant Reproduction',
        question: 'Differentiate between self-pollination and cross-pollination. Give one advantage of cross-pollination.',
        modelAnswer: 'Self-pollination: pollen transfers from anther to stigma of the same flower. Cross-pollination: pollen transfers from anther of one flower to stigma of another flower of the same species. Advantage of cross-pollination: it creates genetic variation, leading to healthier and more adaptable offspring.',
        answerTips: ['Define both types', 'Mention variation as the advantage'],
        reference: { ncertChapter: 'How do Organisms Reproduce?', ncertTopic: 'Sexual Reproduction in Plants', ncertPage: 'p. 160', source: 'NCERT' },
        isFrequent: true,
      },
      {
        id: 'rp-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Human Reproduction',
        question: 'Where does fertilisation occur in human females? What happens to the zygote after fertilisation?',
        modelAnswer: 'Fertilisation occurs in the fallopian tube (oviduct), where the sperm meets the ovum. The fertilised egg (zygote) then travels to the uterus and implants in the endometrium (uterine lining). The zygote divides repeatedly to form an embryo, which develops into a foetus. The placenta provides nutrition and oxygen to the developing foetus.',
        answerTips: ['Name the fallopian tube as the site', 'Mention implantation in the uterus', 'Mention the placenta'],
        reference: { ncertChapter: 'How do Organisms Reproduce?', ncertTopic: 'Reproduction in Humans', ncertPage: 'p. 166', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'rp-q4',
        year: '2020',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Human Reproductive System',
        question: 'Describe the male and female human reproductive systems. Name the primary reproductive organs and their functions.',
        modelAnswer: 'Male system: Testes (produce sperm and testosterone), Vas deferens (transports sperm), Prostate gland and seminal vesicles (produce seminal fluid), Penis (delivers sperm). Female system: Ovaries (produce eggs and oestrogen/progesterone), Fallopian tubes (site of fertilisation), Uterus (site of implantation and foetal development), Cervix (opening of uterus), Vagina (birth canal and receives sperm).',
        answerTips: ['Name all major organs for both systems', 'State the function of each organ'],
        reference: { ncertChapter: 'How do Organisms Reproduce?', ncertTopic: 'Reproduction in Humans', ncertPage: 'p. 164', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'rp-q5',
        year: '2019',
        marks: 2,
        difficulty: 'Easy',
        topic: 'DNA Copying',
        question: 'Why is DNA copying important in reproduction? Why are variations important?',
        modelAnswer: 'DNA copying ensures that offspring inherit traits from the parent. However, small errors during copying create variations. Variations are important because they help organisms adapt to changing environments, ensuring species survival. Without variations, a single environmental change could wipe out an entire species.',
        answerTips: ['Mention inheritance of traits', 'Explain why variation matters for survival'],
        reference: { ncertChapter: 'How do Organisms Reproduce?', ncertTopic: 'Reproduction', ncertPage: 'p. 152', source: 'NCERT' },
        isFrequent: false,
      },
      {
        id: 'rp-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Menstrual Cycle',
        question: 'What is menstruation?',
        modelAnswer: 'If fertilisation does not occur, the thickened endometrium (uterine lining) is shed along with blood and mucus through the vagina. This is called menstruation and lasts about 3-5 days.',
        answerTips: ['Mention the shedding of the endometrium', 'Mention it occurs when fertilisation does not happen'],
        reference: { ncertChapter: 'How do Organisms Reproduce?', ncertTopic: 'Reproduction in Humans', ncertPage: 'p. 168', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'heredity-evolution': {
    chapterSlug: 'heredity-evolution',
    frequentlyRepeatedConcepts: [
      'Mendel\'s monohybrid and dihybrid crosses',
      'Homologous vs analogous organs',
      'Evidence of evolution (fossils)',
      'Speciation and its factors',
      'Sex determination',
    ],
    answerWritingTips: [
      'Use Punnett squares for cross questions',
      'For homologous/analogous, state structure, function, and ancestry',
      'For speciation, list the factors: isolation, variation, selection, time',
    ],
    relatedNCERTTopics: ['Heredity', 'Mendel\'s Experiments', 'Evolution', 'Speciation', 'Sex Determination'],
    relatedNCERTExemplarTopics: ['Monohybrid Cross', 'Dihybrid Cross', 'Homologous vs Analogous'],
    questions: [
      {
        id: 'he-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Mendel\'s Crosses',
        question: 'A tall pea plant (TT) is crossed with a short pea plant (tt). Give the genotype and phenotype of F₁. If F₁ plants are self-pollinated, what is the F₂ phenotypic ratio?',
        modelAnswer: 'Cross: TT × tt → all F₁ are Tt (heterozygous). Phenotype: all tall (T is dominant). F₁ self-pollination: Tt × Tt → TT, Tt, Tt, tt → 3 tall : 1 short. This is the monohybrid ratio.',
        answerTips: ['Show the cross step by step', 'State both genotype and phenotype for F₁', 'Give the 3:1 ratio for F₂'],
        reference: { ncertChapter: 'Heredity and Evolution', ncertTopic: 'Mendel\'s Experiments', ncertPage: 'p. 178', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Sex Determination',
        question: 'Explain how the sex of a child is determined in humans. Who is responsible?',
        modelAnswer: 'Human females have XX sex chromosomes and produce only X-type eggs. Males have XY chromosomes and produce both X-type and Y-type sperm (50% each). If an X sperm fertilises the egg, the child is XX (female). If a Y sperm fertilises the egg, the child is XY (male). Therefore, the father determines the sex of the child.',
        answerTips: ['Mention XX (female) and XY (male)', 'Explain that the father provides either X or Y', 'Conclude that the father is responsible'],
        reference: { ncertChapter: 'Heredity and Evolution', ncertTopic: 'Sex Determination', ncertPage: 'p. 186', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Homologous vs Analogous',
        question: 'Differentiate between homologous and analogous organs. Give one example of each. What type of evolution do they indicate?',
        modelAnswer: 'Homologous organs: same basic structure but different functions, indicating common ancestry (divergent evolution). Example: forelimbs of human and frog. Analogous organs: different basic structures but same function, indicating no common ancestry (convergent evolution). Example: wings of butterfly and bird.',
        answerTips: ['Compare structure, function, and ancestry', 'Give specific examples', 'Name the type of evolution'],
        reference: { ncertChapter: 'Heredity and Evolution', ncertTopic: 'Evolution', ncertPage: 'p. 190', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Speciation',
        question: 'What is speciation? List four factors that can lead to speciation.',
        modelAnswer: 'Speciation is the formation of a new species from an existing one. Factors: (1) Geographical isolation — separation by rivers, mountains, or oceans. (2) Genetic variation — mutations create differences. (3) Natural selection — environment favours certain traits. (4) Reproductive isolation — over time, the separated populations cannot interbreed even if brought together again.',
        answerTips: ['Define speciation', 'List 4 factors with brief explanations'],
        reference: { ncertChapter: 'Heredity and Evolution', ncertTopic: 'Speciation', ncertPage: 'p. 193', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q5',
        year: '2019',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Fossils',
        question: 'What are fossils? How is the age of a fossil determined?',
        modelAnswer: 'Fossils are preserved remains or impressions of ancient organisms found in rocks. The age is determined by dating the rock layers in which they are found (carbon dating for relatively recent fossils, and comparing the depth of rock layers).',
        answerTips: ['Define fossils', 'Mention dating methods'],
        reference: { ncertChapter: 'Heredity and Evolution', ncertTopic: 'Evolution', ncertPage: 'p. 192', source: 'NCERT' },
        isFrequent: false,
      },
      {
        id: 'he-q6',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Acquired vs Inherited Traits',
        question: 'Why are acquired traits not inherited? Give one example.',
        modelAnswer: 'Acquired traits change somatic (body) cells, not germ (reproductive) cells. Only changes in germ cell DNA are passed to offspring. Example: muscle growth from exercise is an acquired trait — it is not inherited by children.',
        answerTips: ['Mention somatic vs germ cells', 'Give a clear example'],
        reference: { ncertChapter: 'Heredity and Evolution', ncertTopic: 'Evolution', ncertPage: 'p. 191', source: 'CBSE PYQ' },
        isFrequent: true,
      },
    ],
  },

  'light-reflection-refraction': {
    chapterSlug: 'light-reflection-refraction',
    frequentlyRepeatedConcepts: [
      'Mirror and lens formula numericals',
      'Image formation by concave/convex mirrors and lenses',
      'Sign convention and magnification',
      'Refractive index calculations',
      'Power of a lens',
    ],
    answerWritingTips: [
      'Always use the sign convention (New Cartesian): distances against incident light are negative',
      'Write the formula before substituting values',
      'State the nature of the image (real/virtual, erect/inverted, magnified/diminished)',
    ],
    relatedNCERTTopics: ['Reflection of Light', 'Spherical Mirrors', 'Refraction of Light', 'Spherical Lenses', 'Power of a Lens'],
    relatedNCERTExemplarTopics: ['Mirror Formula Numericals', 'Lens Formula Numericals', 'Ray Diagrams'],
    questions: [
      {
        id: 'lr-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Mirror Formula',
        question: 'An object of height 4 cm is placed at 15 cm from a concave mirror of focal length 10 cm. Find the image distance and magnification. State the nature of the image.',
        modelAnswer: 'Using 1/v + 1/u = 1/f: 1/v = 1/f − 1/u = 1/(−10) − 1/(−15) = −1/10 + 1/15 = (−3+2)/30 = −1/30. So v = −30 cm. Magnification m = −v/u = −(−30)/(−15) = −2. Image is real, inverted, and magnified 2 times (image height = 8 cm).',
        answerTips: ['Write the formula first', 'Apply sign convention correctly', 'State image nature: real, inverted, magnified'],
        reference: { ncertChapter: 'Light – Reflection and Refraction', ncertTopic: 'Spherical Mirrors', ncertPage: 'p. 210', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lr-q2',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Convex Mirror',
        question: 'Why is a convex mirror used as a rear-view mirror in vehicles?',
        modelAnswer: 'A convex mirror is used because it always produces an erect, diminished image and provides a wider field of view, allowing the driver to see more area behind the vehicle.',
        answerTips: ['Mention wider field of view', 'Mention erect and diminished image'],
        reference: { ncertChapter: 'Light – Reflection and Refraction', ncertTopic: 'Spherical Mirrors', ncertPage: 'p. 205', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lr-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Lens Formula',
        question: 'An object is placed 30 cm from a convex lens of focal length 15 cm. Find the image position and nature.',
        modelAnswer: 'Using 1/v − 1/u = 1/f: 1/v = 1/f + 1/u = 1/15 + 1/(−30) = 1/15 − 1/30 = 2/30 − 1/30 = 1/30. So v = 30 cm. Image is real, inverted, and same size (m = v/u = 30/(−30) = −1). The object is at 2F, so the image forms at 2F on the other side.',
        answerTips: ['Use lens formula (1/v − 1/u = 1/f)', 'Apply sign convention', 'State the image nature'],
        reference: { ncertChapter: 'Light – Reflection and Refraction', ncertTopic: 'Spherical Lenses', ncertPage: 'p. 220', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lr-q4',
        year: '2020',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Power of a Lens',
        question: 'The focal length of a lens is 50 cm. Calculate its power. Is the lens converging or diverging?',
        modelAnswer: 'P = 1/f (in metres) = 1/0.5 = +2 D. Since the power is positive, it is a converging (convex) lens.',
        answerTips: ['Convert cm to metres', 'State whether converging or diverging based on sign'],
        reference: { ncertChapter: 'Light – Reflection and Refraction', ncertTopic: 'Power of a Lens', ncertPage: 'p. 225', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lr-q5',
        year: '2019',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Image Formation',
        question: 'Draw ray diagrams for image formation by a concave mirror when the object is placed at: (a) infinity, (b) between F and C, (c) between F and P. Describe the nature of each image.',
        modelAnswer: '(a) Object at infinity: image is real, inverted, point-sized at F. (b) Object between F and C: image is real, inverted, magnified, beyond C. (c) Object between F and P: image is virtual, erect, magnified, behind the mirror. For (a): two parallel rays reflect through F. For (b): one ray parallel to axis reflects through F, another through C reflects back. For (c): one ray parallel to axis reflects through F, another towards pole reflects making equal angle; reflected rays diverge, extensions meet behind mirror.',
        answerTips: ['Describe all 3 cases', 'State image nature for each: real/virtual, erect/inverted, magnified/diminished'],
        reference: { ncertChapter: 'Light – Reflection and Refraction', ncertTopic: 'Spherical Mirrors', ncertPage: 'p. 206', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'lr-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Refractive Index',
        question: 'The refractive index of water is 1.33. What is the speed of light in water? (c = 3×10⁸ m/s)',
        modelAnswer: 'n = c/v, so v = c/n = 3×10⁸/1.33 ≈ 2.25×10⁸ m/s. Light slows down in water.',
        answerTips: ['Use n = c/v', 'State that light slows down in denser media'],
        reference: { ncertChapter: 'Light – Reflection and Refraction', ncertTopic: 'Refraction of Light', ncertPage: 'p. 217', source: 'NCERT' },
        isFrequent: true,
      },
    ],
  },

  'human-eye': {
    chapterSlug: 'human-eye',
    frequentlyRepeatedConcepts: [
      'Defects of vision (myopia, hypermetropia) — causes and correction',
      'Accommodation and working of the eye',
      'Scattering of light and Tyndall effect',
      'Dispersion and rainbow formation',
    ],
    answerWritingTips: [
      'For vision defects, mention the cause, where the image forms, and the corrective lens',
      'Draw ray diagrams for myopia and hypermetropia correction',
      'For scattering, mention 1/λ⁴ dependence (Rayleigh scattering)',
    ],
    relatedNCERTTopics: ['The Human Eye', 'Defects of Vision', 'Dispersion of Light', 'Atmospheric Refraction'],
    relatedNCERTExemplarTopics: ['Myopia Correction', 'Hypermetropia Correction', 'Tyndall Effect'],
    questions: [
      {
        id: 'he-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Myopia',
        question: 'What is myopia? State two causes. How is it corrected? Draw a ray diagram for correction.',
        modelAnswer: 'Myopia (short-sightedness) is a defect where a person can see nearby objects clearly but cannot see distant objects. The image of a distant object forms in front of the retina. Causes: (1) elongated eyeball, (2) excessive curvature of the eye lens. Correction: a concave lens (diverging) of suitable focal length is used so that the rays diverge before entering the eye and focus on the retina.',
        answerTips: ['Define myopia', 'Give 2 causes', 'Mention concave lens for correction'],
        reference: { ncertChapter: 'Human Eye and Colourful World', ncertTopic: 'Defects of Vision', ncertPage: 'p. 235', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Accommodation',
        question: 'What is accommodation of the eye? How does the eye achieve it?',
        modelAnswer: 'Accommodation is the ability of the eye to focus on both near and distant objects by changing the focal length of the lens. The ciliary muscles contract or relax to change the curvature (and thus focal length) of the eye lens. For near objects, the lens becomes thicker (more curvature, shorter focal length); for distant objects, it becomes thinner.',
        answerTips: ['Define accommodation', 'Explain the role of ciliary muscles'],
        reference: { ncertChapter: 'Human Eye and Colourful World', ncertTopic: 'The Human Eye', ncertPage: 'p. 232', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q3',
        year: '2023',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Scattering',
        question: 'Why does the sky appear blue on a clear day?',
        modelAnswer: 'Air molecules in the atmosphere scatter sunlight. Shorter wavelengths (blue/violet) are scattered more than longer wavelengths (Rayleigh scattering, intensity ∝ 1/λ⁴). Since our eyes are more sensitive to blue than violet, the sky appears blue.',
        answerTips: ['Mention Rayleigh scattering', 'Mention 1/λ⁴ dependence', 'Explain why blue, not violet'],
        reference: { ncertChapter: 'Human Eye and Colourful World', ncertTopic: 'Scattering of Light', ncertPage: 'p. 245', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Hypermetropia',
        question: 'What is hypermetropia? State two causes. Name the type of lens used to correct it and explain how it works.',
        modelAnswer: 'Hypermetropia (long-sightedness) is a defect where a person can see distant objects but cannot see nearby objects clearly. The image of a near object forms behind the retina. Causes: (1) shortened eyeball, (2) low curvature of the eye lens. Correction: a convex lens (converging) is used. It converges the rays before they enter the eye, so the image forms on the retina.',
        answerTips: ['Define hypermetropia', 'Give 2 causes', 'Mention convex lens and explain convergence'],
        reference: { ncertChapter: 'Human Eye and Colourful World', ncertTopic: 'Defects of Vision', ncertPage: 'p. 237', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'he-q5',
        year: '2019',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Tyndall Effect',
        question: 'What is the Tyndall effect? Give one example.',
        modelAnswer: 'The Tyndall effect is the scattering of light by particles in a colloid or fine suspension, making the path of the light beam visible. Example: when a beam of sunlight passes through a dusty room, the dust particles scatter the light and the beam becomes visible.',
        answerTips: ['Define the effect', 'Give a real-life example'],
        reference: { ncertChapter: 'Human Eye and Colourful World', ncertTopic: 'Scattering of Light', ncertPage: 'p. 246', source: 'NCERT' },
        isFrequent: true,
      },
      {
        id: 'he-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Dispersion',
        question: 'What is dispersion of light? Which colour bends the most and why?',
        modelAnswer: 'Dispersion is the splitting of white light into its constituent colours (VIBGYOR) when passing through a prism. Violet bends the most because it has the shortest wavelength and the highest refractive index. Red bends the least (longest wavelength, lowest refractive index).',
        answerTips: ['Define dispersion', 'Mention violet bends most due to shortest wavelength'],
        reference: { ncertChapter: 'Human Eye and Colourful World', ncertTopic: 'Dispersion of Light', ncertPage: 'p. 242', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'electricity': {
    chapterSlug: 'electricity',
    frequentlyRepeatedConcepts: [
      'Ohm\'s law numericals',
      'Series and parallel circuit calculations',
      'Electric power and energy (kWh)',
      'Resistance depends on length, area, material',
      'Heating effect of current',
    ],
    answerWritingTips: [
      'Write the formula before substituting values',
      'For series/parallel, state whether current or voltage is the same',
      'Convert units correctly (cm to m, kW to W)',
    ],
    relatedNCERTTopics: ['Electric Current', 'Ohm\'s Law', 'Resistance', 'Series and Parallel Circuits', 'Electric Power', 'Heating Effect'],
    relatedNCERTExemplarTopics: ['Circuit Calculations', 'Power and Energy', 'Resistance Formula'],
    questions: [
      {
        id: 'el-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Ohm\'s Law',
        question: 'A current of 0.5 A flows through a resistor of 20 Ω. Calculate the voltage across it and the power dissipated.',
        modelAnswer: 'V = IR = 0.5 × 20 = 10 V. P = VI = 10 × 0.5 = 5 W (or P = I²R = 0.25 × 20 = 5 W).',
        answerTips: ['Write V = IR first', 'Use P = VI or I²R for power'],
        reference: { ncertChapter: 'Electricity', ncertTopic: 'Ohm\'s Law', ncertPage: 'p. 260', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'el-q2',
        year: '2022',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Parallel Circuits',
        question: 'Three resistors of 2Ω, 3Ω, and 6Ω are connected in parallel across a 6V battery. Calculate: (a) the equivalent resistance, (b) the total current, (c) the current through the 2Ω resistor.',
        modelAnswer: '(a) 1/Req = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1, so Req = 1Ω. (b) I = V/Req = 6/1 = 6A. (c) In parallel, voltage across each resistor = 6V. I₂ = V/R = 6/2 = 3A.',
        answerTips: ['Show the reciprocal calculation for parallel', 'Use V = IR for each part'],
        reference: { ncertChapter: 'Electricity', ncertTopic: 'Series and Parallel Circuits', ncertPage: 'p. 268', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'el-q3',
        year: '2023',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Resistance',
        question: 'What happens to the resistance of a wire if its length is doubled (keeping area constant)?',
        modelAnswer: 'R = ρL/A. If L is doubled and A is constant, R also doubles. Resistance is directly proportional to length.',
        answerTips: ['State the formula R = ρL/A', 'Explain the proportional relationship'],
        reference: { ncertChapter: 'Electricity', ncertTopic: 'Resistance', ncertPage: 'p. 264', source: 'NCERT' },
        isFrequent: true,
      },
      {
        id: 'el-q4',
        year: '2020',
        marks: 5,
        difficulty: 'Hard',
        topic: 'Electric Power',
        question: 'A 100 W bulb operates at 220 V. Calculate: (a) the resistance of the bulb, (b) the current drawn, (c) the energy consumed in 1 hour, (d) the cost if 1 unit costs ₹5.',
        modelAnswer: '(a) R = V²/P = 220²/100 = 48400/100 = 484 Ω. (b) I = P/V = 100/220 = 0.45 A. (c) Energy = P × t = 100 W × 1 h = 100 Wh = 0.1 kWh. (d) Cost = 0.1 units × ₹5 = ₹0.50.',
        answerTips: ['Use correct formulas: R = V²/P, I = P/V', 'Convert Wh to kWh', 'Calculate cost from units'],
        reference: { ncertChapter: 'Electricity', ncertTopic: 'Electric Power', ncertPage: 'p. 275', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'el-q5',
        year: '2019',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Heating Effect',
        question: 'State Joule\'s law of heating. Why are coils of electric heaters made of alloys and not pure metals?',
        modelAnswer: 'Joule\'s law: H = I²Rt (heat produced is proportional to the square of current, resistance, and time). Alloys (like Nichrome) are used because: (1) they have high resistivity (produce more heat), (2) they do not oxidise at high temperatures (longer lifespan), (3) they have high melting points.',
        answerTips: ['State H = I²Rt', 'Give 2 reasons for using alloys'],
        reference: { ncertChapter: 'Electricity', ncertTopic: 'Heating Effect of Current', ncertPage: 'p. 272', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'el-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Commercial Unit',
        question: 'Define 1 kWh. Express it in joules.',
        modelAnswer: '1 kWh is the energy consumed when a 1000 W appliance runs for 1 hour. 1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J.',
        answerTips: ['Define in terms of power and time', 'Show the conversion to joules'],
        reference: { ncertChapter: 'Electricity', ncertTopic: 'Electric Power', ncertPage: 'p. 276', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'magnetic-effects': {
    chapterSlug: 'magnetic-effects',
    frequentlyRepeatedConcepts: [
      'Magnetic field lines — properties and patterns',
      'Electric motor principle and working',
      'Electromagnetic induction and generator',
      'Fleming\'s left-hand and right-hand rules',
      'Domestic electric circuits and safety',
    ],
    answerWritingTips: [
      'For motor/generator, state the energy conversion and the rule used',
      'For field lines, mention: closed loops, never intersect, denser = stronger',
      'For domestic circuits, mention live, neutral, earth wires and their colours',
    ],
    relatedNCERTTopics: ['Magnetic Field', 'Electric Motor', 'Electromagnetic Induction', 'Domestic Circuits'],
    relatedNCERTExemplarTopics: ['Field Line Properties', 'Motor vs Generator', 'Fleming\'s Rules'],
    questions: [
      {
        id: 'me-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Magnetic Field Lines',
        question: 'List three properties of magnetic field lines. Why do they never intersect?',
        modelAnswer: 'Properties: (1) They form closed continuous loops. (2) They never intersect each other. (3) The density of lines indicates field strength — closer lines mean a stronger field. They never intersect because if they did, it would mean the magnetic field has two directions at the point of intersection, which is physically impossible.',
        answerTips: ['List 3 properties', 'Explain why they cannot intersect'],
        reference: { ncertChapter: 'Magnetic Effects of Electric Current', ncertTopic: 'Magnetic Field', ncertPage: 'p. 285', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'me-q2',
        year: '2022',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Electric Motor',
        question: 'What is an electric motor? State its principle. Name the rule used to find the direction of force.',
        modelAnswer: 'An electric motor converts electrical energy into mechanical (rotational) energy. Principle: when a current-carrying conductor is placed in a magnetic field, it experiences a force. The direction of force is found using Fleming\'s left-hand rule (forefinger = field, middle finger = current, thumb = force/motion).',
        answerTips: ['State the energy conversion', 'State the principle (force on current in magnetic field)', 'Name Fleming\'s left-hand rule'],
        reference: { ncertChapter: 'Magnetic Effects of Electric Current', ncertTopic: 'Electric Motor', ncertPage: 'p. 293', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'me-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Electromagnetic Induction',
        question: 'What is electromagnetic induction? State Fleming\'s right-hand rule. Where is it used?',
        modelAnswer: 'Electromagnetic induction is the production of an electric current (EMF) in a conductor when the magnetic flux through it changes (discovered by Faraday). Fleming\'s right-hand rule: stretch thumb, forefinger, and middle finger of the right hand mutually perpendicular. Forefinger = magnetic field, thumb = motion of conductor, middle finger = induced current. It is used to find the direction of induced current in generators.',
        answerTips: ['Define electromagnetic induction', 'State the right-hand rule', 'Mention its use in generators'],
        reference: { ncertChapter: 'Magnetic Effects of Electric Current', ncertTopic: 'Electromagnetic Induction', ncertPage: 'p. 297', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'me-q4',
        year: '2020',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Domestic Circuits',
        question: 'What is the function of an earth wire? Why is it necessary?',
        modelAnswer: 'The earth wire connects the metal body of an appliance to the ground. If a fault causes the body to become live, the current flows to earth through the low-resistance earth wire instead of through the user\'s body, preventing electric shock. It is necessary for safety.',
        answerTips: ['Explain the connection to ground', 'Emphasise safety and preventing shock'],
        reference: { ncertChapter: 'Magnetic Effects of Electric Current', ncertTopic: 'Domestic Circuits', ncertPage: 'p. 305', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'me-q5',
        year: '2019',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Field Around Wire',
        question: 'What is the shape of magnetic field lines around a straight current-carrying conductor?',
        modelAnswer: 'The magnetic field lines around a straight current-carrying conductor form concentric circles in a plane perpendicular to the wire. The direction is given by the right-hand thumb rule.',
        answerTips: ['Mention concentric circles', 'Mention the right-hand thumb rule'],
        reference: { ncertChapter: 'Magnetic Effects of Electric Current', ncertTopic: 'Magnetic Field', ncertPage: 'p. 286', source: 'NCERT' },
        isFrequent: false,
      },
      {
        id: 'me-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Motor vs Generator',
        question: 'Differentiate between an electric motor and a generator in one sentence.',
        modelAnswer: 'A motor converts electrical energy to mechanical energy (uses Fleming\'s left-hand rule), while a generator converts mechanical energy to electrical energy (uses Fleming\'s right-hand rule).',
        answerTips: ['State the energy conversion for each', 'Mention the respective Fleming\'s rule'],
        reference: { ncertChapter: 'Magnetic Effects of Electric Current', ncertTopic: 'Electric Motor', ncertPage: 'p. 293', source: 'NCERT' },
        isFrequent: true,
      },
    ],
  },

  'sources-of-energy': {
    chapterSlug: 'sources-of-energy',
    frequentlyRepeatedConcepts: [
      'Conventional vs non-conventional energy',
      'Solar and wind energy',
      'Biogas plant and advantages',
      'Nuclear fission',
      'Greenhouse effect',
    ],
    answerWritingTips: [
      'Compare renewable vs non-renewable in a table',
      'For biogas, mention the composition (60-70% methane) and the slurry by-product',
      'For nuclear energy, mention the advantages and the radioactive waste disadvantage',
    ],
    relatedNCERTTopics: ['Conventional Sources', 'Non-Conventional Sources', 'Nuclear Energy', 'Environmental Consequences'],
    relatedNCERTExemplarTopics: ['Energy Source Comparison', 'Biogas Process'],
    questions: [
      {
        id: 'se-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Biogas',
        question: 'Explain how biogas is produced. Write the main component and state two advantages over wood as fuel.',
        modelAnswer: 'Biogas is produced by anaerobic decomposition of animal dung and organic waste by bacteria in a biogas plant. The main component is methane (CH₄, 60-70%). Advantages over wood: (1) burns cleanly without smoke, reducing air pollution, (2) the spent slurry is an excellent organic manure, (3) reduces deforestation as wood is not needed.',
        answerTips: ['Mention anaerobic decomposition', 'State methane as the main component', 'Give 2 advantages over wood'],
        reference: { ncertChapter: 'Sources of Energy', ncertTopic: 'Non-Conventional Sources', ncertPage: 'p. 315', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'se-q2',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Renewable Energy',
        question: 'Which energy source is considered the cleanest? Why?',
        modelAnswer: 'Solar energy is the cleanest because it produces no air pollution, no greenhouse gases, and no radioactive waste. It is also renewable (inexhaustible).',
        answerTips: ['Name solar energy', 'Give 2-3 reasons why it is cleanest'],
        reference: { ncertChapter: 'Sources of Energy', ncertTopic: 'Non-Conventional Sources', ncertPage: 'p. 312', source: 'NCERT' },
        isFrequent: false,
      },
      {
        id: 'se-q3',
        year: '2023',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Greenhouse Effect',
        question: 'What is the greenhouse effect? Name two greenhouse gases.',
        modelAnswer: 'The greenhouse effect is the trapping of heat by certain gases in the atmosphere, similar to how a greenhouse retains heat. These gases allow sunlight to pass through but absorb infrared radiation (heat) reflected from Earth. Greenhouse gases: carbon dioxide (CO₂) and methane (CH₄).',
        answerTips: ['Define the effect', 'Name 2 greenhouse gases'],
        reference: { ncertChapter: 'Sources of Energy', ncertTopic: 'Environmental Consequences', ncertPage: 'p. 320', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'se-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Nuclear Energy',
        question: 'What is nuclear fission? State one advantage and one disadvantage of nuclear energy.',
        modelAnswer: 'Nuclear fission is the splitting of a heavy nucleus (like U-235) when it absorbs a neutron, releasing enormous energy and more neutrons (chain reaction). Advantage: a small amount of fuel produces huge energy without CO₂ emissions. Disadvantage: it produces radioactive waste that is difficult to dispose of safely, and there is a risk of nuclear accidents (e.g., Chernobyl).',
        answerTips: ['Define fission with U-235 example', 'Give one advantage and one disadvantage'],
        reference: { ncertChapter: 'Sources of Energy', ncertTopic: 'Nuclear Energy', ncertPage: 'p. 318', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'se-q5',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Fossil Fuels',
        question: 'Why are fossil fuels called non-renewable?',
        modelAnswer: 'Fossil fuels (coal, petroleum, natural gas) take millions of years to form from dead organisms under high pressure and temperature. They cannot be replenished on a human timescale, making them non-renewable.',
        answerTips: ['Mention millions of years to form', 'State they cannot be replenished quickly'],
        reference: { ncertChapter: 'Sources of Energy', ncertTopic: 'Conventional Sources', ncertPage: 'p. 310', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },

  'our-environment': {
    chapterSlug: 'our-environment',
    frequentlyRepeatedConcepts: [
      'Food chain and food web',
      '10% law of energy transfer',
      'Ozone layer formation and depletion',
      'Biodegradable vs non-biodegradable waste',
      'Biological magnification',
    ],
    answerWritingTips: [
      'For energy transfer, show the calculation step by step (10% at each level)',
      'For ozone, write both formation (O₂ + O → O₃) and depletion (Cl + O₃ → ClO + O₂) equations',
      'Mention that energy flow is unidirectional, only nutrients cycle',
    ],
    relatedNCERTTopics: ['Ecosystem', 'Food Chains and Webs', 'Ozone Layer', 'Waste Management'],
    relatedNCERTExemplarTopics: ['10% Law Numericals', 'Ozone Depletion', 'Biological Magnification'],
    questions: [
      {
        id: 'oe-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: '10% Law',
        question: 'In a food chain, grass has 20,000 J of energy. Calculate the energy available to the secondary consumer (snake). State the law used.',
        modelAnswer: 'Food chain: Grass → Grasshopper → Snake. According to the 10% law (Lindeman\'s law), only 10% of energy at one trophic level is available to the next. Grass (20,000 J) → Grasshopper (10% of 20,000 = 2,000 J) → Snake (10% of 2,000 = 200 J). Energy available to the snake = 200 J.',
        answerTips: ['Name the 10% law (Lindeman)', 'Show step-by-step calculation', 'State the final answer clearly'],
        reference: { ncertChapter: 'Our Environment', ncertTopic: 'Food Chains', ncertPage: 'p. 330', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'oe-q2',
        year: '2022',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Ozone Layer',
        question: 'How is ozone formed in the atmosphere? How is it depleted? Write the equations. Why is the ozone layer important?',
        modelAnswer: 'Formation: UV light splits O₂ into oxygen atoms: O₂ → 2O. The oxygen atom combines with O₂: O + O₂ → O₃ (ozone). Depletion: CFCs release chlorine atoms in the stratosphere: Cl + O₃ → ClO + O₂. The chlorine destroys ozone molecules. Importance: the ozone layer absorbs harmful UV radiation, protecting living organisms from skin cancer, DNA damage, and other health issues.',
        answerTips: ['Write both formation and depletion equations', 'Mention UV absorption as the function'],
        reference: { ncertChapter: 'Our Environment', ncertTopic: 'Ozone Layer', ncertPage: 'p. 335', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'oe-q3',
        year: '2023',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Waste Types',
        question: 'Differentiate between biodegradable and non-biodegradable waste. Give two examples of each.',
        modelAnswer: 'Biodegradable waste can be decomposed by microorganisms. Examples: vegetable peels, paper, cloth. Non-biodegradable waste cannot be decomposed by microorganisms and persists in the environment. Examples: plastic, glass, metal.',
        answerTips: ['Define both types', 'Give 2 examples each'],
        reference: { ncertChapter: 'Our Environment', ncertTopic: 'Waste Management', ncertPage: 'p. 338', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'oe-q4',
        year: '2020',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Biological Magnification',
        question: 'What is biological magnification? Explain with an example. Why are top predators most affected?',
        modelAnswer: 'Biological magnification is the accumulation of non-biodegradable toxins in increasing concentrations at higher trophic levels. Example: DDT is sprayed on crops → absorbed by plants → eaten by small fish → eaten by large fish → eaten by hawks. The concentration of DDT increases at each level. Top predators are most affected because they consume many organisms from lower levels, accumulating the highest concentration of toxins.',
        answerTips: ['Define the term', 'Give a specific food chain example', 'Explain why top predators have the highest concentration'],
        reference: { ncertChapter: 'Our Environment', ncertTopic: 'Food Chains', ncertPage: 'p. 332', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'oe-q5',
        year: '2019',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Food Chain',
        question: 'What is the difference between a food chain and a food web?',
        modelAnswer: 'A food chain is a linear sequence showing energy flow from producers to consumers. A food web is a network of interconnected food chains showing all possible feeding relationships in an ecosystem.',
        answerTips: ['Mention linear vs network', 'Mention that a food web shows all relationships'],
        reference: { ncertChapter: 'Our Environment', ncertTopic: 'Food Chains', ncertPage: 'p. 328', source: 'NCERT' },
        isFrequent: false,
      },
      {
        id: 'oe-q6',
        year: '2022',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Energy Flow',
        question: 'Why is the flow of energy in an ecosystem said to be unidirectional?',
        modelAnswer: 'Energy flows from the sun to producers, then to consumers, and is ultimately lost as heat. It does not cycle back to the sun or to producers. Only nutrients cycle in an ecosystem; energy flow is one-way.',
        answerTips: ['Mention sun → producers → consumers → heat', 'Contrast with nutrient cycling'],
        reference: { ncertChapter: 'Our Environment', ncertTopic: 'Food Chains', ncertPage: 'p. 331', source: 'NCERT' },
        isFrequent: true,
      },
    ],
  },

  'sustainable-management': {
    chapterSlug: 'sustainable-management',
    frequentlyRepeatedConcepts: [
      '3Rs — Reduce, Reuse, Recycle',
      'Water conservation and rainwater harvesting',
      'Forest conservation (Chipko Movement, Amrita Devi Bishnoi)',
      'Fossil fuels and their environmental impact',
      'Ganga Action Plan',
    ],
    answerWritingTips: [
      'State the 3Rs in priority order (Reduce > Reuse > Recycle)',
      'For water conservation, mention rainwater harvesting and drip irrigation',
      'Mention specific movements (Chipko, Amrita Devi Bishnoi) with details',
    ],
    relatedNCERTTopics: ['Water Conservation', 'Forest Conservation', 'Coal and Petroleum', '3Rs of Waste Management'],
    relatedNCERTExemplarTopics: ['Sustainable Practices', 'Water Conservation Methods'],
    questions: [
      {
        id: 'sm-q1',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: '3Rs',
        question: 'What are the 3Rs of waste management? Explain each with one example. State the priority order.',
        modelAnswer: 'The 3Rs are: (1) Reduce — use less resources to minimise waste. Example: use less electricity, water. (2) Reuse — use items again instead of discarding. Example: reuse glass bottles and bags. (3) Recycle — process waste into new products. Example: recycle paper, plastic, metal. Priority order: Reduce > Reuse > Recycle. Reduce is most important because it prevents waste at the source.',
        answerTips: ['Define each R with an example', 'State the priority order', 'Explain why Reduce is first'],
        reference: { ncertChapter: 'Sustainable Management of Natural Resources', ncertTopic: '3Rs of Waste Management', ncertPage: 'p. 345', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'sm-q2',
        year: '2022',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Water Conservation',
        question: 'What is rainwater harvesting? Mention two advantages.',
        modelAnswer: 'Rainwater harvesting is the collection and storage of rainwater from rooftops or surfaces for reuse or groundwater recharge. Advantages: (1) recharges groundwater aquifers, (2) reduces dependence on municipal water supply, (3) prevents urban flooding by reducing runoff.',
        answerTips: ['Define rainwater harvesting', 'Give 2 advantages'],
        reference: { ncertChapter: 'Sustainable Management of Natural Resources', ncertTopic: 'Water Conservation', ncertPage: 'p. 348', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'sm-q3',
        year: '2023',
        marks: 3,
        difficulty: 'Medium',
        topic: 'Forest Conservation',
        question: 'Describe the Chipko Movement. Who led it? What was its significance?',
        modelAnswer: 'The Chipko Movement was a forest conservation movement in Uttarakhand where villagers hugged trees to prevent them from being felled by contractors. It was led by Sundarlal Bahuguna. Significance: it highlighted the importance of forests in maintaining ecological balance, preventing soil erosion, and protecting local communities dependent on forests. It inspired similar movements across India.',
        answerTips: ['Mention Uttarakhand and hugging trees', 'Name Sundarlal Bahuguna', 'State the significance'],
        reference: { ncertChapter: 'Sustainable Management of Natural Resources', ncertTopic: 'Forest Conservation', ncertPage: 'p. 350', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'sm-q4',
        year: '2020',
        marks: 2,
        difficulty: 'Easy',
        topic: 'Fossil Fuels',
        question: 'Why are coal and petroleum called non-renewable? Mention two harmful effects of burning them.',
        modelAnswer: 'Coal and petroleum take millions of years to form from dead organisms under high pressure and temperature, so they cannot be replenished on a human timescale. Harmful effects of burning: (1) release CO₂ (greenhouse gas → global warming), (2) release SO₂ (causes acid rain), (3) release particulate matter (air pollution).',
        answerTips: ['Mention millions of years to form', 'Give 2 harmful effects with specific gases'],
        reference: { ncertChapter: 'Sustainable Management of Natural Resources', ncertTopic: 'Coal and Petroleum', ncertPage: 'p. 352', source: 'CBSE PYQ' },
        isFrequent: true,
      },
      {
        id: 'sm-q5',
        year: '2019',
        marks: 1,
        difficulty: 'Easy',
        topic: 'Ganga Action Plan',
        question: 'What was the Ganga Action Plan? When was it launched?',
        modelAnswer: 'The Ganga Action Plan was launched in 1985 to reduce pollution in the river Ganga by treating domestic and industrial waste before it enters the river.',
        answerTips: ['Mention 1985', 'State the purpose: reducing pollution'],
        reference: { ncertChapter: 'Sustainable Management of Natural Resources', ncertTopic: 'Water Conservation', ncertPage: 'p. 349', source: 'NCERT' },
        isFrequent: false,
      },
    ],
  },
};

export function getPYQData(chapterSlug: string): PYQChapterData | undefined {
  return pyqSeries[chapterSlug];
}

export function getAllPYQQuestions(): { chapter: string; question: PYQQuestion }[] {
  const all: { chapter: string; question: PYQQuestion }[] = [];
  for (const [slug, data] of Object.entries(pyqSeries)) {
    for (const q of data.questions) {
      all.push({ chapter: slug, question: q });
    }
  }
  return all;
}
