import type { Flashcard, FormulaCard } from '../revision-content';

export const lifeProcessesFlashcards: Flashcard[] = [
  {
    front: 'What are life processes? Name the four main types.',
    back: 'Life processes are the essential functions that maintain life: nutrition, respiration, transportation, and excretion.',
    definition: 'Life processes: The essential functions performed by living organisms to maintain their life.',
    explanation: 'These processes provide energy, remove waste, and transport materials needed for survival.',
    keyword: 'Nutrition, Respiration, Transportation, Excretion',
    commonMistake: 'Forgetting excretion — it is one of the four main life processes.',
    examTip: 'Be able to define each life process and give its primary organ/system.',
    memoryTrick: '"N-R-T-E" — Nutrition, Respiration, Transportation, Excretion.',
  },
  {
    front: 'Write the balanced equation for photosynthesis.',
    back: '6CO₂ + 6H₂O →(sunlight, chlorophyll)→ C₆H₁₂O₆ + 6O₂',
    definition: 'Photosynthesis: Green plants make food from CO₂ and water using sunlight and chlorophyll.',
    explanation: 'Chlorophyll in chloroplasts absorbs sunlight. CO₂ and H₂O are converted to glucose (C₆H₁₂O₆) and O₂ is released.',
    keyword: 'Sunlight + Chlorophyll above arrow',
    commonMistake: 'Forgetting to write "sunlight" and "chlorophyll" above the arrow — they are essential conditions.',
    examTip: 'Always write the full balanced equation with conditions. Also know: O₂ is a by-product, not the main product.',
    memoryTrick: '"6 CO₂ + 6 H₂O = 1 Glucose + 6 O₂" — six in, glucose and six out.',
  },
  {
    front: 'What is the difference between aerobic and anaerobic respiration?',
    back: 'Aerobic: uses O₂, in mitochondria, produces CO₂ + H₂O + 38 ATP. Anaerobic: no O₂, in cytoplasm, produces lactic acid (muscles) or ethanol+CO₂ (yeast) + 2 ATP.',
    definition: 'Aerobic: with O₂, 38 ATP. Anaerobic: without O₂, 2 ATP.',
    explanation: 'Aerobic respiration completely breaks down glucose using oxygen, releasing maximum energy. Anaerobic respiration partially breaks down glucose without oxygen, releasing less energy.',
    keyword: '38 ATP vs 2 ATP',
    commonMistake: 'Writing the wrong site — aerobic is in mitochondria, anaerobic is in cytoplasm.',
    examTip: 'Know both anaerobic equations: muscles → lactic acid, yeast → ethanol + CO₂.',
    memoryTrick: '"Aerobic = 38 (lots), Anaerobic = 2 (little)."',
  },
  {
    front: 'Why do muscles cramp during heavy exercise?',
    back: 'During heavy exercise, muscles respire anaerobically (not enough O₂), producing lactic acid. Accumulation of lactic acid causes cramps.',
    definition: 'Muscle cramps: Caused by lactic acid accumulation from anaerobic respiration.',
    explanation: 'When oxygen supply is insufficient during intense activity, glucose is partially broken down into lactic acid, which accumulates and causes pain/cramps.',
    keyword: 'Lactic acid accumulation',
    commonMistake: 'Saying cramps are caused by CO₂ buildup — they are caused by lactic acid.',
    examTip: 'Know that resting and massaging improves blood flow, supplying O₂ to break down lactic acid.',
    memoryTrick: '"No O₂ = Lactic acid = Cramp" — oxygen debt causes cramps.',
  },
  {
    front: 'What is double circulation? Why is it necessary?',
    back: 'Blood passes through the heart twice per complete cycle: pulmonary (heart→lungs→heart) and systemic (heart→body→heart). It is necessary to maintain separation of oxygenated and deoxygenated blood and maintain high pressure.',
    definition: 'Double circulation: Blood flows through the heart twice per cycle — pulmonary and systemic.',
    explanation: 'The right side pumps deoxygenated blood to lungs; the left side pumps oxygenated blood to the body. This ensures efficient oxygen supply and prevents mixing of blood.',
    keyword: 'Pulmonary + Systemic',
    commonMistake: 'Saying the left side has deoxygenated blood — left = oxygenated, right = deoxygenated.',
    examTip: 'Know that double circulation maintains blood pressure and ensures oxygenated blood reaches all organs efficiently.',
    memoryTrick: '"Right = Dirty (deoxy), Left = Clean (oxy)" — right side to lungs, left side to body.',
  },
  {
    front: 'What is the role of bile in digestion? Is it an enzyme?',
    back: 'Bile is produced by the liver and stored in the gall bladder. It emulsifies fats (breaks large fat globules into smaller ones). It is NOT an enzyme — it does not chemically break down fats.',
    definition: 'Bile: A non-enzymatic fluid that emulsifies fats.',
    explanation: 'Bile salts break large fat globules into tiny droplets, increasing surface area for the enzyme lipase to act. Bile also makes the small intestine alkaline.',
    keyword: 'Emulsification (not digestion)',
    commonMistake: 'Calling bile an enzyme — it is NOT. It only emulsifies; it does not chemically break down fats.',
    examTip: 'Know that bile makes the intestine alkaline so pancreatic enzymes can work.',
    memoryTrick: '"Bile = Breaks big fat into small fat" — it is a physical change, not a chemical one.',
  },
  {
    front: 'What is a nephron? Name its three main functions.',
    back: 'The nephron is the structural and functional unit of the kidney. Its three functions: (1) Filtration (glomerulus), (2) Reabsorption (tubule), (3) Secretion (tubule → urine).',
    definition: 'Nephron: The functional unit of the kidney that filters blood and produces urine.',
    explanation: 'Blood is filtered in the glomerulus (Bowman\'s capsule). Useful substances are reabsorbed. Waste is secreted into the tubule and collected as urine.',
    keyword: 'Filtration, Reabsorption, Secretion',
    commonMistake: 'Forgetting reabsorption — the nephron does not just filter; it also reabsorbs useful substances like glucose and water.',
    examTip: 'Be able to label the nephron: glomerulus, Bowman\'s capsule, proximal tubule, loop of Henle, distal tubule, collecting duct.',
    memoryTrick: '"FRSU" — Filtration, Reabsorption, Secretion, Urine.',
  },
  {
    front: 'Differentiate between xylem and phloem.',
    back: 'Xylem transports water and minerals upward (roots→leaves), no energy needed. Phloem transports food (sucrose) bidirectionally (leaves→all parts), uses ATP energy.',
    definition: 'Xylem: Water/minerals, upward, passive. Phloem: Food, both directions, active (uses ATP).',
    explanation: 'Xylem relies on transpiration pull (water moves up due to evaporation from leaves). Phloem uses active transport (energy from ATP) to move sucrose from source (leaves) to sink (roots, fruits).',
    keyword: 'Xylem = water up, Phloem = food both ways',
    commonMistake: 'Saying phloem transports only upward — it transports food in both directions.',
    examTip: 'Know that phloem transport is called translocation and requires ATP.',
    memoryTrick: '"Xylem Up (water), Phloem Both-ways (food)" — xylem is one-way, phloem is two-way.',
  },
];

export const lifeProcessesFormulas: FormulaCard[] = [
  {
    formula: '6CO₂ + 6H₂O →(sunlight, chlorophyll)→ C₆H₁₂O₆ + 6O₂',
    label: 'Photosynthesis',
    symbols: 'CO₂ = Carbon dioxide, H₂O = Water, C₆H₁₂O₆ = Glucose, O₂ = Oxygen',
    units: 'No SI units — chemical equation',
    usedFor: 'Describing how green plants make food from CO₂ and water using sunlight',
    conditions: 'Requires sunlight, chlorophyll, and water. Occurs in chloroplasts during the day.',
    commonMistakes: 'Forgetting to write "sunlight" and "chlorophyll" above the arrow. Also, O₂ is released as a by-product, not CO₂.',
    example: 'A green leaf absorbs 6 molecules of CO₂ and 6 molecules of H₂O. In the presence of sunlight and chlorophyll, it produces 1 molecule of glucose (C₆H₁₂O₆) and releases 6 molecules of O₂.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP',
    label: 'Aerobic Respiration',
    symbols: 'C₆H₁₂O₆ = Glucose, O₂ = Oxygen, CO₂ = Carbon dioxide, H₂O = Water, ATP = Adenosine Triphosphate (energy)',
    units: 'No SI units — chemical equation; ATP is the energy unit',
    usedFor: 'Describing the complete breakdown of glucose in the presence of oxygen to release energy',
    conditions: 'Requires oxygen. Occurs in mitochondria. Produces 38 ATP per glucose molecule.',
    commonMistakes: 'Writing 2 ATP instead of 38 ATP — aerobic produces 38, anaerobic produces only 2.',
    example: 'During respiration, 1 molecule of glucose (180 g) reacts with 6 molecules of O₂ to produce 6 molecules of CO₂, 6 molecules of H₂O, and 38 molecules of ATP (energy).',
    signConvention: 'Not applicable',
  },
  {
    formula: 'C₆H₁₂O₆ → 2C₃H₆O₃ + 2 ATP (muscles)',
    label: 'Anaerobic Respiration in Muscles',
    symbols: 'C₆H₁₂O₆ = Glucose, C₃H₆O₃ = Lactic acid, ATP = Energy',
    units: 'No SI units — chemical equation',
    usedFor: 'Explains why muscles cramp during heavy exercise (lactic acid buildup)',
    conditions: 'No oxygen available. Occurs in cytoplasm. Produces only 2 ATP.',
    commonMistakes: 'Writing CO₂ as a product — in muscles, anaerobic respiration produces lactic acid, not CO₂.',
    example: 'During a sprint, when oxygen supply is insufficient, glucose is partially broken down in muscle cells, producing lactic acid (C₃H₆O₃) and only 2 ATP. The lactic acid causes muscle cramps.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ + 2 ATP (yeast)',
    label: 'Anaerobic Respiration in Yeast (Fermentation)',
    symbols: 'C₆H₁₂O₆ = Glucose, C₂H₅OH = Ethanol, CO₂ = Carbon dioxide, ATP = Energy',
    units: 'No SI units — chemical equation',
    usedFor: 'Explains fermentation used in brewing (alcohol) and baking (CO₂ makes dough rise)',
    conditions: 'No oxygen. Occurs in yeast cells in cytoplasm. Produces ethanol, CO₂, and 2 ATP.',
    commonMistakes: 'Confusing yeast anaerobic products (ethanol + CO₂) with muscle anaerobic products (lactic acid).',
    example: 'Yeast ferments glucose: 1 molecule of glucose produces 2 molecules of ethanol, 2 molecules of CO₂ (which makes bread dough rise), and 2 ATP.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Cardiac Output = Heart Rate × Stroke Volume',
    label: 'Cardiac Output',
    symbols: 'Heart Rate = beats per minute (bpm), Stroke Volume = volume of blood pumped per beat (mL/beat)',
    units: 'Heart Rate: bpm (beats per minute). Stroke Volume: mL/beat. Cardiac Output: mL/min',
    usedFor: 'Calculating the total volume of blood pumped by the heart per minute',
    conditions: 'Applies to the human heart. Normal resting heart rate: 60-100 bpm. Normal stroke volume: ~70 mL/beat.',
    commonMistakes: 'Confusing stroke volume with cardiac output — stroke volume is per beat, cardiac output is per minute.',
    example: 'If heart rate = 72 bpm and stroke volume = 70 mL/beat, then cardiac output = 72 × 70 = 5040 mL/min (about 5 litres per minute).',
    signConvention: 'Not applicable',
  },
];

export const controlCoordinationFlashcards: Flashcard[] = [
  {
    front: 'What is a reflex action? Give one example.',
    back: 'An involuntary, rapid response to a stimulus that does not involve the brain. Example: withdrawing your hand from a hot plate.',
    definition: 'Reflex action: An involuntary, rapid response to a stimulus, mediated by the spinal cord.',
    explanation: 'The stimulus is detected by receptors, the signal goes to the spinal cord (not brain), and the spinal cord sends a signal to the effector muscle to respond immediately.',
    keyword: 'Involuntary + spinal cord',
    commonMistake: 'Saying the brain is involved in reflex action — the brain is bypassed for speed.',
    examTip: 'Know the pathway: receptor → sensory neuron → spinal cord → motor neuron → effector.',
    memoryTrick: '"Reflex = Rapid, brain is bypassed" — spinal cord does the thinking.',
  },
  {
    front: 'What is a synapse? How do signals cross it?',
    back: 'A synapse is the junction between two neurons. Electrical signals cannot cross directly; they trigger the release of chemical messengers (neurotransmitters) that cross the gap.',
    definition: 'Synapse: The gap between two neurons where electrical signals convert to chemical signals.',
    explanation: 'When an electrical impulse reaches the end of an axon, it triggers the release of neurotransmitters. These chemicals diffuse across the synapse and start a new electrical impulse in the next neuron.',
    keyword: 'Neurotransmitters',
    commonMistake: 'Saying electrical signals cross the synapse directly — they do not; chemical neurotransmitters cross.',
    examTip: 'Know that the synapse ensures unidirectional flow of impulses (from axon to dendrite, not reverse).',
    memoryTrick: '"Synapse = Chemical bridge" — electricity becomes chemicals, then electricity again.',
  },
  {
    front: 'Name the three main parts of the brain and their functions.',
    back: 'Cerebrum: thinking, memory, voluntary actions. Cerebellum: balance, posture, coordination. Medulla: involuntary functions (breathing, heart rate, blood pressure).',
    definition: 'Cerebrum = cognition, Cerebellum = coordination, Medulla = involuntary control.',
    explanation: 'The cerebrum is the largest part and controls higher functions. The cerebellum coordinates movement. The medulla controls automatic functions like breathing.',
    keyword: 'CCM',
    commonMistake: 'Confusing cerebrum (thinking) with cerebellum (balance) — they sound similar but have different functions.',
    examTip: 'Also know the pons: regulates breathing rhythm.',
    memoryTrick: '"CCM" — Cerebrum = Cognition, Cerebellum = Coordination, Medulla = Maintenance.',
  },
  {
    front: 'Name the five plant hormones and one function of each.',
    back: 'Auxin: cell elongation (phototropism). Gibberellin: stem growth, seed germination. Cytokinin: cell division. Abscisic acid: inhibits growth, closes stomata. Ethylene: fruit ripening.',
    definition: 'Plant hormones: Auxin, Gibberellin, Cytokinin, Abscisic acid, Ethylene.',
    explanation: 'Phytohormones regulate plant growth and development. Auxin causes phototropism (bending towards light). Abscisic acid is a growth inhibitor.',
    keyword: 'AGCAE',
    commonMistake: 'Confusing auxin (elongation) with cytokinin (division) — auxin elongates cells, cytokinin divides them.',
    examTip: 'Know that ethylene is a gaseous hormone (fruit ripening) and abscisic acid closes stomata during water stress.',
    memoryTrick: '"All Good Children Are Eating" — Auxin, Gibberellin, Cytokinin, Abscisic acid, Ethylene.',
  },
  {
    front: 'How does phototropism work in plants?',
    back: 'When light hits one side of a shoot, auxin migrates to the shaded side. More auxin causes faster cell elongation on the shaded side, making the shoot bend towards light.',
    definition: 'Phototropism: Growth movement of a plant shoot towards light, caused by auxin migration.',
    explanation: 'Auxin is photosensitive. It moves away from light to the shaded side, where it promotes cell elongation. The shaded side grows faster, causing bending towards light.',
    keyword: 'Auxin → shaded side → faster growth',
    commonMistake: 'Saying auxin moves towards light — it moves AWAY from light to the shaded side.',
    examTip: 'Know that roots show negative phototropism (grow away from light) and positive geotropism (grow downwards).',
    memoryTrick: '"Auxin runs from light" — it goes to the dark side, making it grow faster and bend towards light.',
  },
  {
    front: 'What is the difference between nervous and hormonal control?',
    back: 'Nervous: fast, electrical, short-lived, specific pathway. Hormonal: slow, chemical (blood), long-lasting, affects target organs widely.',
    definition: 'Nervous = fast & specific. Hormonal = slow & widespread.',
    explanation: 'Nerve impulses travel at high speed through neurons. Hormones travel slowly through the bloodstream but have longer-lasting effects.',
    keyword: 'Fast vs Slow',
    commonMistake: 'Saying hormonal control is faster — it is slower but longer-lasting.',
    examTip: 'Be able to compare in a table: speed, pathway, duration, target, mode of transmission.',
    memoryTrick: '"Nervous = Fast and Short, Hormonal = Slow and Long."',
  },
  {
    front: 'What causes diabetes and goitre? How are they treated?',
    back: 'Diabetes: insulin deficiency (high blood sugar) → treated with insulin injections. Goitre: thyroxine deficiency due to iodine lack → treated with iodine in diet.',
    definition: 'Diabetes = low insulin. Goitre = low thyroxine (iodine deficiency).',
    explanation: 'Insulin is produced by the pancreas and lowers blood sugar. Thyroxine is produced by the thyroid and needs iodine. Low thyroxine causes the thyroid to enlarge (goitre).',
    keyword: 'Insulin (pancreas), Thyroxine (thyroid, needs iodine)',
    commonMistake: 'Saying goitre is caused by insulin deficiency — goitre is caused by thyroxine deficiency (iodine).',
    examTip: 'Know the gland and treatment for each: diabetes → pancreas → insulin; goitre → thyroid → iodine.',
    memoryTrick: '"Diabetes = Pancreas + Insulin, Goitre = Thyroid + Iodine."',
  },
  {
    front: 'What is the fight-or-flight response? Which hormone is involved?',
    back: 'Adrenaline (from adrenal glands) is released during fear/stress. It increases heart rate, breathing rate, and blood flow to muscles, preparing the body for rapid action.',
    definition: 'Fight-or-flight: Adrenaline-mediated stress response preparing the body for action.',
    explanation: 'Adrenaline increases blood supply to muscles, dilates air passages, and raises blood sugar for quick energy. This prepares the body to fight or flee.',
    keyword: 'Adrenaline',
    commonMistake: 'Confusing adrenaline with thyroxine — adrenaline is the fight-or-flight hormone; thyroxine regulates metabolism.',
    examTip: 'Know the source: adrenaline is secreted by the adrenal glands (located on top of kidneys).',
    memoryTrick: '"Adrenaline = Action" — it prepares the body to fight or run.',
  },
];

export const controlCoordinationFormulas: FormulaCard[] = [
  {
    formula: 'Stimulus → Receptor → Sensory neuron → CNS → Motor neuron → Effector',
    label: 'Nervous Pathway',
    symbols: 'Stimulus = environmental change, Receptor = sensory cell, Sensory neuron = carries signal to CNS, CNS = brain/spinal cord, Motor neuron = carries signal from CNS, Effector = muscle/gland',
    units: 'No SI units — biological pathway',
    usedFor: 'Describing the complete pathway of a nervous impulse from stimulus to response',
    conditions: 'Requires a functional nervous system with intact neurons and synapses.',
    commonMistakes: 'Confusing sensory (towards CNS) and motor (away from CNS) neurons.',
    example: 'Touching a hot plate: heat (stimulus) → skin receptors → sensory neuron → spinal cord → motor neuron → arm muscle (effector) pulls hand away.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Reflex arc: Receptor → Sensory neuron → Spinal cord → Motor neuron → Effector',
    label: 'Reflex Arc Pathway',
    symbols: 'Receptor = detects stimulus, Sensory neuron = carries signal to spinal cord, Spinal cord = processes reflex (no brain), Motor neuron = carries signal to muscle, Effector = muscle that responds',
    units: 'No SI units — biological pathway',
    usedFor: 'Explaining how reflex actions bypass the brain for faster response',
    conditions: 'The spinal cord must be intact. The brain is not involved in the reflex itself (though it is informed afterwards).',
    commonMistakes: 'Including the brain in the reflex arc — the brain is bypassed for speed.',
    example: 'Stepping on a thorn: thorn (stimulus) → skin receptors → sensory neuron → spinal cord → motor neuron → leg muscle (effector) lifts foot.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Auxin → Cell elongation → Phototropism (bending towards light)',
    label: 'Phototropism Mechanism',
    symbols: 'Auxin = plant hormone, Cell elongation = cells get longer, Phototropism = growth towards light',
    units: 'No SI units — biological mechanism',
    usedFor: 'Explaining why plant shoots bend towards light',
    conditions: 'Requires unilateral (one-sided) light. Auxin must be present and functional.',
    commonMistakes: 'Saying auxin moves towards light — it moves AWAY from light to the shaded side.',
    example: 'A potted plant is placed near a window. Light comes from one side. Auxin migrates to the shaded side, causing faster cell elongation there. The shoot bends towards the window.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Insulin → Glucose uptake by cells → Blood sugar decreases',
    label: 'Insulin Action',
    symbols: 'Insulin = hormone from pancreas, Glucose = blood sugar, Cells = body cells that take up glucose',
    units: 'No SI units — biological mechanism',
    usedFor: 'Explaining how insulin regulates blood sugar levels',
    conditions: 'Insulin must be produced by the pancreas and cells must have insulin receptors. Deficiency causes diabetes.',
    commonMistakes: 'Confusing insulin (lowers blood sugar) with glucagon (raises blood sugar).',
    example: 'After a meal, blood glucose rises. The pancreas secretes insulin, which signals cells to take up glucose, bringing blood sugar back to normal. In diabetes, insulin is deficient, so blood sugar stays high.',
    signConvention: 'Not applicable',
  },
];

export const reproductionFlashcards: Flashcard[] = [
  {
    front: 'What is asexual reproduction? Name 5 methods with examples.',
    back: 'Reproduction involving a single parent producing genetically identical offspring. Methods: binary fission (Amoeba), budding (Hydra), fragmentation (Spirogyra), spore formation (fungi), vegetative propagation (potato).',
    definition: 'Asexual reproduction: Single parent produces clones (genetically identical offspring).',
    explanation: 'No fusion of gametes. Offspring are identical to the parent. It is faster but produces no variation.',
    keyword: 'Single parent, clones',
    commonMistake: 'Confusing binary fission (parent splits into two) with budding (new individual grows as an outgrowth).',
    examTip: 'Know all 5 methods with examples: binary fission (Amoeba), budding (Hydra/Yeast), fragmentation (Spirogyra), spore (Rhizopus), vegetative (potato/Bryophyllum).',
    memoryTrick: '"BBF SV" — Binary, Budding, Fragmentation, Spore, Vegetative.',
  },
  {
    front: 'What is double fertilisation in flowering plants?',
    back: 'Two male gametes from one pollen tube: one fuses with the egg to form the zygote (2n), the other fuses with two polar nuclei to form the endosperm (3n).',
    definition: 'Double fertilisation: One male gamete + egg = zygote; other male gamete + 2 polar nuclei = endosperm.',
    explanation: 'This is unique to flowering plants (angiosperms). The zygote becomes the embryo; the endosperm nourishes the embryo.',
    keyword: 'Zygote (2n) + Endosperm (3n)',
    commonMistake: 'Thinking only one fertilisation occurs — two happen simultaneously in flowering plants.',
    examTip: 'Know the products: zygote → embryo, endosperm → food for embryo, ovule → seed, ovary → fruit.',
    memoryTrick: '"Two gametes, two targets: egg → baby, polar nuclei → food."',
  },
  {
    front: 'What happens to the ovule and ovary after fertilisation?',
    back: 'The ovule develops into a seed, and the ovary develops into a fruit.',
    definition: 'Post-fertilisation: Ovule → Seed, Ovary → Fruit.',
    explanation: 'After fertilisation, the zygote in the ovule develops into an embryo (seed). The ovary wall thickens and becomes the fruit, protecting the seeds.',
    keyword: 'OSOF',
    commonMistake: 'Reversing the two — ovule becomes seed, ovary becomes fruit (not the other way around).',
    examTip: 'Know that the seed contains the embryo and the fruit contains the seeds.',
    memoryTrick: '"OSOF" — Ovule → Seed, Ovary → Fruit.',
  },
  {
    front: 'Where does fertilisation occur in humans? Why?',
    back: 'In the fallopian tube (oviduct), not the uterus. The sperm meets the ovum here, forming a zygote which then travels to the uterus for implantation.',
    definition: 'Fertilisation site: Fallopian tube (oviduct) in humans.',
    explanation: 'The ovum is released from the ovary into the fallopian tube. Sperm travel through the uterus to reach the fallopian tube, where fertilisation occurs. The zygote then moves to the uterus.',
    keyword: 'Fallopian tube',
    commonMistake: 'Saying fertilisation occurs in the uterus — it occurs in the fallopian tube.',
    examTip: 'Know the journey: ovary → fallopian tube (fertilisation) → uterus (implantation).',
    memoryTrick: '"Fertilisation in the Tube, Implantation in the Uterus."',
  },
  {
    front: 'Why are testes located outside the body in the scrotum?',
    back: 'Sperm production requires a temperature about 2°C below body temperature. The scrotum keeps the testes outside, maintaining this lower temperature.',
    definition: 'Testes location: Outside the body in the scrotum for temperature regulation.',
    explanation: 'Body temperature (~37°C) is too high for healthy sperm production. The scrotum (~35°C) provides the optimal temperature.',
    keyword: '2°C below body temperature',
    commonMistake: 'Saying testes are outside for "protection" — it is for temperature regulation.',
    examTip: 'Know that the scrotum can move closer/farther from the body to regulate temperature.',
    memoryTrick: '"Cool sperm = Healthy sperm" — 2°C below body temp.',
  },
  {
    front: 'On which day does ovulation occur in a 28-day menstrual cycle? What happens if fertilisation does not occur?',
    back: 'Ovulation occurs on day 14. If the egg is not fertilised, the thickened uterine lining breaks down and is discharged as menstrual blood (days 1-5).',
    definition: 'Ovulation: Day 14 of a 28-day cycle. No fertilisation → menstruation.',
    explanation: 'The ovary releases an egg on day 14. If no sperm fertilises it, the corpus luteum degenerates, progesterone drops, and the uterine lining sheds.',
    keyword: 'Day 14',
    commonMistake: 'Writing day 1 or day 28 for ovulation — it is day 14 (mid-cycle).',
    examTip: 'Know the cycle: days 1-5 = menstruation, day 14 = ovulation, days 15-28 = luteal phase.',
    memoryTrick: '"14 = Egg release" — mid-cycle ovulation.',
  },
  {
    front: 'Name four contraceptive methods and how they work.',
    back: '(1) Barrier: condom (blocks sperm). (2) Chemical: pills (prevent ovulation). (3) IUCD: copper-T (prevents implantation). (4) Surgical: vasectomy/tubectomy (blocks tubes).',
    definition: 'Contraception: Methods to prevent pregnancy — barrier, chemical, IUCD, surgical.',
    explanation: 'Each method works differently: condoms block sperm, pills prevent ovulation, IUCDs prevent implantation, surgical methods cut or block the vas deferens or fallopian tubes.',
    keyword: 'Barrier, Chemical, IUCD, Surgical',
    commonMistake: 'Forgetting that condoms also prevent STIs — they are the only method that does.',
    examTip: 'Know that condoms are the only contraceptive that prevents both pregnancy and STIs.',
    memoryTrick: '"BCIS" — Barrier, Chemical, IUCD, Surgical.',
  },
  {
    front: 'What is pollination? Differentiate self and cross-pollination.',
    back: 'Pollination is the transfer of pollen from anther to stigma. Self-pollination: within the same flower. Cross-pollination: between different flowers (requires agents like wind, water, insects).',
    definition: 'Pollination: Transfer of pollen from anther to stigma.',
    explanation: 'Self-pollination occurs in the same flower (bisexual). Cross-pollination requires a pollinating agent (wind, water, insects) to transfer pollen between flowers.',
    keyword: 'Anther → Stigma',
    commonMistake: 'Confusing pollination (pollen transfer) with fertilisation (gamete fusion). Pollination happens first.',
    examTip: 'Know that cross-pollination produces more variation (genetically diverse offspring).',
    memoryTrick: '"Pollination = Pollen moves, Fertilisation = Gametes fuse."',
  },
];

export const reproductionFormulas: FormulaCard[] = [
  {
    formula: 'Pollen + Egg → Zygote → Embryo → Seed (in ovule)',
    label: 'Plant Fertilisation and Development',
    symbols: 'Pollen = male gamete, Egg = female gamete, Zygote = fertilised cell (2n), Embryo = developing organism, Seed = mature ovule containing embryo',
    units: 'No SI units — biological process',
    usedFor: 'Describing the sequence from fertilisation to seed formation in flowering plants',
    conditions: 'Requires successful pollination (pollen reaching stigma) and fertilisation (gamete fusion in ovary).',
    commonMistakes: 'Confusing pollination (pollen transfer) with fertilisation (gamete fusion).',
    example: 'A bee transfers pollen from flower A to the stigma of flower B. The pollen tube grows to the ovary. Male gamete fuses with the egg to form a zygote, which develops into an embryo within the seed.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Ovule → Seed | Ovary → Fruit',
    label: 'Post-Fertilisation Changes',
    symbols: 'Ovule = structure containing the egg, Seed = mature ovule with embryo, Ovary = structure containing ovules, Fruit = mature ovary containing seeds',
    units: 'No SI units — biological process',
    usedFor: 'Remembering what happens to flower parts after fertilisation',
    conditions: 'Requires successful fertilisation. Without fertilisation, the flower parts wither and fall off.',
    commonMistakes: 'Reversing the two — ovule becomes seed, ovary becomes fruit (not the other way around).',
    example: 'After fertilisation in a tomato flower, the ovules develop into tomato seeds, and the ovary swells and becomes the tomato fruit.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Sperm + Ovum → Zygote (in fallopian tube)',
    label: 'Human Fertilisation',
    symbols: 'Sperm = male gamete (n), Ovum = female gamete (n), Zygote = fertilised cell (2n)',
    units: 'No SI units — biological process',
    usedFor: 'Describing human fertilisation and its location',
    conditions: 'Fertilisation occurs in the fallopian tube (oviduct), not the uterus. Requires ovulation (egg release on day 14).',
    commonMistakes: 'Saying fertilisation occurs in the uterus — it occurs in the fallopian tube.',
    example: 'During intercourse, sperm travel through the uterus to the fallopian tube. One sperm fuses with the ovum (released on day 14) to form a zygote, which then travels to the uterus for implantation.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Ovulation: Day 14 of 28-day cycle',
    label: 'Menstrual Cycle Timing',
    symbols: 'Day 14 = mid-cycle, when the ovary releases an egg',
    units: 'Days (of menstrual cycle)',
    usedFor: 'Determining when ovulation occurs in a standard 28-day menstrual cycle',
    conditions: 'Applies to a standard 28-day cycle. In shorter or longer cycles, ovulation typically occurs 14 days before the next period.',
    commonMistakes: 'Writing day 1 or day 28 for ovulation — it is day 14 (mid-cycle).',
    example: 'In a 28-day cycle: days 1-5 = menstruation, day 14 = ovulation (egg released), days 15-28 = luteal phase. If no fertilisation, the cycle repeats.',
    signConvention: 'Not applicable',
  },
];

export const heredityEvolutionFlashcards: Flashcard[] = [
  {
    front: 'What is heredity? Who is called the Father of Genetics?',
    back: 'Heredity is the transmission of traits from parents to offspring through genes. Gregor Mendel is the Father of Genetics.',
    definition: 'Heredity: Transmission of traits from parents to offspring via genes.',
    explanation: 'Genes on chromosomes carry traits. Mendel discovered the laws of inheritance using pea plants.',
    keyword: 'Genes on chromosomes',
    commonMistake: 'Confusing heredity (transmission) with evolution (change over generations).',
    examTip: 'Know that Mendel used pea plants (Pisum sativum) with 7 contrasting traits.',
    memoryTrick: '"Heredity = Hand-me-downs" — traits are passed from parents to children.',
  },
  {
    front: 'What is the F₂ phenotypic ratio of a monohybrid cross? What is the genotypic ratio?',
    back: 'Phenotypic ratio: 3:1 (3 tall : 1 short). Genotypic ratio: 1:2:1 (1 TT : 2 Tt : 1 tt).',
    definition: 'Monohybrid F₂: Phenotype = 3:1, Genotype = 1:2:1.',
    explanation: 'In a Tt × Tt cross, 3 out of 4 show the dominant phenotype (tall) and 1 shows the recessive (short). Genotypically, 1 is TT, 2 are Tt, 1 is tt.',
    keyword: '3:1 phenotype, 1:2:1 genotype',
    commonMistake: 'Confusing phenotype (3:1) with genotype (1:2:1) — they are different ratios.',
    examTip: 'Be able to draw a Punnett square for Tt × Tt and derive both ratios.',
    memoryTrick: '"Pheno = 3:1 (what you see), Geno = 1:2:1 (what genes are)."',
  },
  {
    front: 'What is the F₂ phenotypic ratio of a dihybrid cross?',
    back: '9:3:3:1 (9 round-yellow : 3 round-green : 3 wrinkled-yellow : 1 wrinkled-green).',
    definition: 'Dihybrid F₂ phenotypic ratio: 9:3:3:1.',
    explanation: 'In a RrYy × RrYy cross, 9/16 show both dominant traits, 3/16 show one dominant + one recessive (two combinations), and 1/16 shows both recessive.',
    keyword: '9:3:3:1',
    commonMistake: 'Writing 3:1 for dihybrid — that is monohybrid. Dihybrid is 9:3:3:1.',
    examTip: 'Be able to draw a 4×4 Punnett square for RrYy × RrYy.',
    memoryTrick: '"9-3-3-1" — nine dominant, three and three mixed, one double recessive.',
  },
  {
    front: 'How is sex determined in humans? Who determines the sex of the child?',
    back: 'Females are XX, males are XY. The father determines the sex: if sperm carries X → daughter (XX), if Y → son (XY). The mother always gives X.',
    definition: 'Sex determination: XX = female, XY = male. Father determines sex.',
    explanation: 'The mother\'s egg always carries an X chromosome. The father\'s sperm can carry either X or Y. X sperm + X egg = XX (daughter); Y sperm + X egg = XY (son).',
    keyword: 'Father decides (X or Y)',
    commonMistake: 'Blaming the mother for the child\'s sex — the father\'s sperm determines it.',
    examTip: 'Know the ratio: 50% chance of boy, 50% chance of girl.',
    memoryTrick: '"Mom gives X, Dad gives X or Y — Dad decides."',
  },
  {
    front: 'Differentiate between homologous and analogous organs with examples.',
    back: 'Homologous: same structure, different function (forelimbs of human, frog, bird — common ancestor). Analogous: different structure, same function (wings of butterfly, bird — convergent evolution).',
    definition: 'Homologous = same structure, different function (divergent evolution). Analogous = different structure, same function (convergent evolution).',
    explanation: 'Homologous organs indicate common ancestry. Analogous organs show that different organisms independently evolved similar features for the same function.',
    keyword: 'Homologous = common ancestor, Analogous = convergent',
    commonMistake: 'Mixing them up — homologous = same structure; analogous = same function.',
    examTip: 'Know examples: Homologous = forelimbs of human/frog/bird. Analogous = wings of butterfly/bird/bat.',
    memoryTrick: '"Same structure = Homologous (common ancestor). Same function = Analogous (adaptation)."',
  },
  {
    front: 'Are acquired traits inherited? Why or why not?',
    back: 'No. Acquired traits (like muscle growth, tail-cutting) do not change the DNA of germ cells (sperm/egg). Only changes in germ cell DNA are inherited.',
    definition: 'Acquired traits are NOT inherited — only germ cell DNA changes are passed on.',
    explanation: 'Acquired traits affect body (somatic) cells only. Inheritance requires changes in the reproductive cells (germ cells) that carry DNA to the next generation.',
    keyword: 'Germ cell DNA only',
    commonMistake: 'Thinking that cutting a mouse\'s tail for generations will produce tailless offspring — it will not (Weismann\'s experiment).',
    examTip: 'Know that only changes in the DNA of germ cells (gametes) are inherited.',
    memoryTrick: '"Body changes stay with the body; Germ changes go to children."',
  },
  {
    front: 'What is speciation? What are its causes?',
    back: 'Speciation is the formation of new species from existing ones. Causes: geographical isolation, genetic variation (mutation), natural selection, and reproductive isolation.',
    definition: 'Speciation: Formation of new species due to isolation and genetic divergence.',
    explanation: 'When populations are separated (geographically), they cannot interbreed. Over time, mutations and natural selection cause them to diverge genetically until they can no longer produce fertile offspring.',
    keyword: 'Isolation + genetic divergence',
    commonMistake: 'Saying speciation happens within one generation — it takes many generations.',
    examTip: 'Know the four causes: geographical isolation, mutation, natural selection, reproductive isolation.',
    memoryTrick: '"Separate + Change = New Species" — isolation + genetic divergence = speciation.',
  },
  {
    front: 'What are fossils? How is their age determined?',
    back: 'Fossils are preserved remains or traces of ancient organisms. Age is determined by: (1) carbon-14 dating (radioactive isotope), (2) depth of the rock layer (deeper = older).',
    definition: 'Fossils: Preserved remains of ancient organisms; dated by carbon-14 or rock depth.',
    explanation: 'When an organism dies, it may be buried in sediment. Over millions of years, hard parts are replaced by minerals (fossilisation). Carbon-14 decays at a known rate, allowing age estimation.',
    keyword: 'Carbon-14 dating',
    commonMistake: 'Saying fossils are formed from soft tissues — usually only hard parts (bones, shells) fossilise.',
    examTip: 'Know Archaeopteryx as a missing link between reptiles and birds (has feathers + teeth).',
    memoryTrick: '"Fossils = Ancient photos" — preserved snapshots of past life.',
  },
];

export const heredityEvolutionFormulas: FormulaCard[] = [
  {
    formula: 'Monohybrid F₂ ratio: 3:1 (phenotype), 1:2:1 (genotype)',
    label: 'Monohybrid Cross Ratio',
    symbols: '3:1 = 3 dominant phenotype : 1 recessive phenotype; 1:2:1 = 1 homozygous dominant : 2 heterozygous : 1 homozygous recessive',
    units: 'Dimensionless (ratios)',
    usedFor: 'Predicting the outcome of a monohybrid cross in the F₂ generation',
    conditions: 'Requires a cross between two heterozygous individuals (Tt × Tt). Complete dominance must apply.',
    commonMistakes: 'Confusing phenotype (3:1) with genotype (1:2:1) — they are different ratios.',
    example: 'Cross: Tt × Tt (both heterozygous tall). F₂: 1 TT (tall) : 2 Tt (tall) : 1 tt (short). Phenotype: 3 tall : 1 short = 3:1. Genotype: 1 TT : 2 Tt : 1 tt = 1:2:1.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Dihybrid F₂ ratio: 9:3:3:1 (phenotype)',
    label: 'Dihybrid Cross Ratio',
    symbols: '9 = both dominant traits, 3 = first dominant + second recessive, 3 = first recessive + second dominant, 1 = both recessive',
    units: 'Dimensionless (ratio)',
    usedFor: 'Predicting the outcome of a dihybrid cross in the F₂ generation',
    conditions: 'Requires a cross between two double heterozygotes (RrYy × RrYy). Genes must assort independently (Mendel\'s law).',
    commonMistakes: 'Writing 3:1 for dihybrid — that is monohybrid. Dihybrid is 9:3:3:1.',
    example: 'Cross: RrYy × RrYy (round-yellow seeds). F₂: 9 round-yellow : 3 round-green : 3 wrinkled-yellow : 1 wrinkled-green = 9:3:3:1.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Sex determination: XX (female) × XY (male) → 50% XX : 50% XY',
    label: 'Sex Determination in Humans',
    symbols: 'XX = female sex chromosomes, XY = male sex chromosomes, 50% = probability of each sex',
    units: 'Dimensionless (probability)',
    usedFor: 'Determining the probability of having a male or female child',
    conditions: 'Mother always provides X. Father provides X or Y with equal probability (50% each).',
    commonMistakes: 'Saying the mother determines sex — the father does (X or Y from sperm).',
    example: 'Mother (XX) produces eggs with X. Father (XY) produces sperm with X or Y. X sperm + X egg = XX (daughter, 50%). Y sperm + X egg = XY (son, 50%).',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Homologous organs → Divergent evolution (common ancestry)',
    label: 'Homologous Organs and Evolution',
    symbols: 'Homologous organs = same basic structure, different functions; Divergent evolution = common ancestor gives rise to different forms',
    units: 'Not applicable — biological concept',
    usedFor: 'Using homologous organs as evidence for evolution from a common ancestor',
    conditions: 'Organs must have the same fundamental anatomical structure but different functions in different species.',
    commonMistakes: 'Confusing homologous (same structure) with analogous (same function).',
    example: 'Forelimbs of humans (grasping), frogs (jumping), birds (flying), and bats (flying) have the same bone structure (humerus, radius, ulna, carpals) but different functions. This indicates they evolved from a common ancestor.',
    signConvention: 'Not applicable',
  },
];
