import type { Flashcard, FormulaCard } from '../revision-content';

export const chemicalReactionsFlashcards: Flashcard[] = [
  {
    front: 'What is a chemical reaction?',
    back: 'A process where reactants undergo bond breaking and bond forming to produce new substances (products) with different properties.',
    definition: 'Chemical reaction: A process where reactants transform into products with new chemical properties.',
    explanation: 'In a chemical reaction, the atoms are rearranged — bonds between atoms are broken and new bonds are formed, creating substances with different properties from the reactants.',
    keyword: 'Reactants → Products',
    commonMistake: 'Confusing a physical change (no new substance) with a chemical change (new substance formed). Melting ice is physical; burning paper is chemical.',
    examTip: 'Always identify the reactants and products first, then balance the equation.',
    memoryTrick: '"Old bonds break, new bonds make" — a chemical reaction is all about bond rearrangement.',
  },
  {
    front: 'State the Law of Conservation of Mass.',
    back: 'Mass can neither be created nor destroyed in a chemical reaction. The total mass of reactants equals the total mass of products.',
    definition: 'Law of Conservation of Mass: The total mass of reactants equals the total mass of products in a chemical reaction.',
    explanation: 'This is why we balance chemical equations — the number of atoms of each element must be the same on both sides.',
    keyword: 'Balanced equation',
    commonMistake: 'Forgetting to balance the equation — always count atoms of each element on both sides.',
    examTip: 'Start balancing with the most complex compound and balance H and O last.',
    memoryTrick: '"What goes in must come out" — atoms are conserved, just rearranged.',
  },
  {
    front: 'What is a balanced chemical equation? Why is it important?',
    back: 'An equation having equal numbers of atoms of each element on both sides. It is important because it obeys the Law of Conservation of Mass.',
    definition: 'Balanced equation: An equation having equal numbers of atoms of each element on both sides.',
    explanation: 'Balancing ensures that the Law of Conservation of Mass is satisfied — no atoms are created or destroyed.',
    keyword: 'Atom count equal on both sides',
    commonMistake: 'Changing subscript numbers instead of coefficients to balance — never change subscripts, only coefficients.',
    examTip: 'Always add state symbols (s), (l), (g), (aq) and conditions above the arrow.',
  },
  {
    front: 'Define oxidation and reduction.',
    back: 'Oxidation is the gain of oxygen or loss of electrons. Reduction is the loss of oxygen or gain of electrons.',
    definition: 'Oxidation: Gain of oxygen or loss of electrons. Reduction: Loss of oxygen or gain of electrons.',
    explanation: 'In a redox reaction, one substance is oxidised (loses electrons/gains O) while another is reduced (gains electrons/loses O). Both happen simultaneously.',
    keyword: 'OIL RIG',
    commonMistake: 'Confusing the oxidising agent (gets reduced) with the reducing agent (gets oxidised).',
    examTip: 'Identify which substance gains O (oxidised) and which loses O (reduced) in the given reaction.',
    memoryTrick: '"OIL RIG" — Oxidation Is Loss, Reduction Is Gain (of electrons).',
  },
  {
    front: 'What is the thermite reaction? Write its equation.',
    back: 'A displacement reaction where aluminium reduces iron oxide to iron, releasing large heat. Fe₂O₃ + 2Al → 2Fe + Al₂O₃. Used for welding railway tracks.',
    definition: 'Thermite reaction: A highly exothermic displacement reaction where aluminium displaces iron from iron oxide.',
    explanation: 'Aluminium is more reactive than iron, so it displaces iron from Fe₂O₃. The large heat released melts the iron, which can join broken railway tracks.',
    keyword: 'Displacement + Exothermic',
    commonMistake: 'Writing the products in the wrong order or forgetting it is a displacement reaction.',
    examTip: 'Mention the application (welding railway tracks) — it is frequently asked.',
    memoryTrick: '"Al takes O from Fe" — aluminium is the reducing agent, iron oxide is the oxidising agent.',
  },
  {
    front: 'Why is respiration considered an exothermic reaction?',
    back: 'Because glucose breaks down in the presence of oxygen to release a large amount of energy. C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy.',
    definition: 'Exothermic reaction: A reaction that releases heat energy into the surroundings.',
    explanation: 'During respiration, glucose is oxidised and energy is released. Since heat/energy is released, it is exothermic.',
    keyword: 'Energy released',
    commonMistake: 'Confusing exothermic (releases heat) with endothermic (absorbs heat).',
    examTip: 'Also know that electrolysis of water is endothermic — a common contrast question.',
    memoryTrick: '"Exo = Exit" — energy exits the reaction (released). "Endo = Enter" — energy enters (absorbed).',
  },
  {
    front: 'Why does silver chloride turn grey in sunlight? Write the equation.',
    back: 'Silver chloride decomposes in sunlight to form silver metal and chlorine gas. 2AgCl → 2Ag + Cl₂. This is photodecomposition.',
    definition: 'Photodecomposition: Decomposition of a compound by sunlight.',
    explanation: 'Light energy breaks the Ag-Cl bond, depositing silver metal (grey colour) and releasing chlorine gas.',
    keyword: 'Photodecomposition',
    commonMistake: 'Writing AgCl₂ instead of AgCl — silver has valency 1.',
    examTip: 'Also know that AgBr (silver bromide) decomposes similarly and is used in black-and-white photography.',
    memoryTrick: '"Sunlight splits silver salt" — both AgCl and AgBr decompose in light.',
  },
  {
    front: 'What is corrosion? Give one example and two prevention methods.',
    back: 'Corrosion is the slow degradation of metals by air and moisture. Example: rusting of iron (Fe₂O₃·xH₂O). Prevention: painting, galvanising, oiling, alloying.',
    definition: 'Corrosion: The slow degradation of metals by the action of air and moisture.',
    explanation: 'Iron reacts with oxygen and water to form rust (hydrated ferric oxide). It weakens the metal over time.',
    keyword: 'Fe₂O₃·xH₂O',
    commonMistake: 'Writing the rust formula as Fe₂O₃ without the water of crystallisation (xH₂O).',
    examTip: 'Know at least 3-4 prevention methods: painting, galvanising, oiling, alloying, tinning.',
    memoryTrick: '"Air + Water = Rust" — keep either away and iron will not rust.',
  },
  {
    front: 'What is rancidity? How can it be prevented?',
    back: 'Rancidity is the oxidation of fats and oils producing unpleasant smell and taste. Prevention: antioxidants, airtight containers, refrigeration, nitrogen flushing.',
    definition: 'Rancidity: The oxidation of fats and oils producing unpleasant smell and taste.',
    explanation: 'When fats/oils are exposed to air, they undergo oxidation and become rancid. This spoils food.',
    keyword: 'Oxidation of fats',
    commonMistake: 'Confusing rancidity (fats) with corrosion (metals) — both are oxidation but affect different materials.',
    examTip: 'Nitrogen flushing is a common prevention method asked in exams — chips packets are flushed with N₂.',
    memoryTrick: '"Rancid = Rot" — fats go bad when oxygen attacks them.',
  },
];

export const chemicalReactionsFormulas: FormulaCard[] = [
  {
    formula: '4Fe + 3O₂ + xH₂O → 2Fe₂O₃·xH₂O',
    label: 'Rusting of Iron',
    symbols: 'Fe = Iron, O₂ = Oxygen, H₂O = Water, x = variable number of water molecules, Fe₂O₃·xH₂O = hydrated ferric oxide (rust)',
    units: 'No SI units — this is a chemical equation, not a numerical formula',
    usedFor: 'Describing the formation of rust when iron is exposed to moist air',
    conditions: 'Requires both oxygen and moisture (water). In pure water or dry air, rusting does not occur.',
    commonMistakes: 'Writing Fe₂O₃ without xH₂O — rust is hydrated ferric oxide, not just ferric oxide.',
    example: 'An iron nail left in moist air for several days develops a reddish-brown coating of Fe₂O₃·xH₂O (rust). A nail in boiled water (no air) or oil-coated (no water) does not rust.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Fe₂O₃ + 2Al → 2Fe + Al₂O₃',
    label: 'Thermite Reaction',
    symbols: 'Fe₂O₃ = Iron(III) oxide, Al = Aluminium, Fe = Iron, Al₂O₃ = Aluminium oxide',
    units: 'No SI units — chemical equation',
    usedFor: 'Welding broken railway tracks; demonstrates displacement and exothermic reaction',
    conditions: 'Aluminium must be more reactive than iron (it is, in the reactivity series). Reaction is initiated by heat.',
    commonMistakes: 'Writing Al₂O₃ as the product that gets reduced — Al is oxidised (gains O), Fe₂O₃ is reduced (loses O).',
    example: 'A mixture of Fe₂O₃ and Al powder is ignited at a railway track joint. The intense heat melts the iron produced, welding the tracks together.',
    signConvention: 'Not applicable',
  },
  {
    formula: '2AgCl → 2Ag + Cl₂ (in sunlight)',
    label: 'Photodecomposition of Silver Chloride',
    symbols: 'AgCl = Silver chloride, Ag = Silver, Cl₂ = Chlorine gas',
    units: 'No SI units — chemical equation',
    usedFor: 'Demonstrates decomposition by light; silver chloride turns grey due to silver metal formation',
    conditions: 'Requires sunlight (light energy). Does not occur in the dark.',
    commonMistakes: 'Writing AgCl₂ — silver has a valency of 1, so it is AgCl, not AgCl₂.',
    example: 'White silver chloride powder is placed in sunlight. After some time, it turns grey due to the formation of silver metal.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy',
    label: 'Aerobic Respiration (Exothermic)',
    symbols: 'C₆H₁₂O₆ = Glucose, O₂ = Oxygen, CO₂ = Carbon dioxide, H₂O = Water',
    units: 'No SI units — chemical equation',
    usedFor: 'Explains why respiration is exothermic — energy is released',
    conditions: 'Requires oxygen (aerobic). In the absence of O₂, anaerobic respiration occurs (lactic acid in muscles, ethanol in yeast).',
    commonMistakes: 'Forgetting to write "energy" as a product — it is what makes the reaction exothermic.',
    example: 'During respiration, 1 mole of glucose (180 g) reacts with 6 moles of O₂ to release 38 ATP of energy, CO₂, and water.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'CaCO₃ → CaO + CO₂ (heat)',
    label: 'Thermal Decomposition of Limestone',
    symbols: 'CaCO₃ = Calcium carbonate (limestone), CaO = Calcium oxide (quicklime), CO₂ = Carbon dioxide',
    units: 'No SI units — chemical equation',
    usedFor: 'Industrial production of quicklime (CaO) from limestone; demonstrates thermal decomposition',
    conditions: 'Requires strong heating. The CO₂ gas evolved turns limewater milky.',
    commonMistakes: 'Forgetting to write "heat" above the arrow — this is a thermal decomposition, not spontaneous.',
    example: 'Limestone (CaCO₃) is strongly heated in a kiln. It decomposes into quicklime (CaO) and CO₂ gas, which turns limewater milky.',
    signConvention: 'Not applicable',
  },
];

export const acidsBasesSaltsFlashcards: Flashcard[] = [
  {
    front: 'What is an acid? What ions does it release in water?',
    back: 'An acid is a sour substance that releases H⁺ (hydronium, H₃O⁺) ions in aqueous solution.',
    definition: 'Acid: A substance that releases H⁺ (hydronium, H₃O⁺) ions in aqueous solution.',
    explanation: 'Acids donate protons (H⁺) in water. The H⁺ ions combine with water to form hydronium ions (H₃O⁺).',
    keyword: 'H₃O⁺ (hydronium ion)',
    commonMistake: 'Writing H⁺ instead of H₃O⁺ — in water, H⁺ always exists as H₃O⁺.',
    examTip: 'Know examples: HCl, H₂SO₄, HNO₃ are strong acids; CH₃COOH (acetic acid) is a weak acid.',
    memoryTrick: '"Acids Add H⁺" — they donate hydrogen ions in water.',
  },
  {
    front: 'What is a base? What is an alkali?',
    back: 'A base releases OH⁻ ions in water. An alkali is a base that is soluble in water (e.g., NaOH, KOH).',
    definition: 'Base: Releases OH⁻ ions. Alkali: A water-soluble base.',
    explanation: 'All alkalis are bases, but not all bases are alkalis. NaOH and KOH are alkalis; CuO is a base but not an alkali (insoluble).',
    keyword: 'OH⁻ (hydroxide ion)',
    commonMistake: 'Confusing strong/weak with concentrated/dilute — strength = degree of ionisation, not concentration.',
    examTip: 'Know that NaOH, KOH are strong alkalis; NH₄OH is a weak alkali.',
    memoryTrick: '"Alkali = All bases that dissolve" — alkali is a soluble base.',
  },
  {
    front: 'What is the pH scale? What do pH 7, pH < 7, and pH > 7 indicate?',
    back: 'pH is the negative logarithm of H⁺ ion concentration, measuring acidity/basicity on a 0–14 scale. pH 7 = neutral, < 7 = acidic, > 7 = basic.',
    definition: 'pH = −log[H⁺]; measures acidity or basicity on a scale of 0–14.',
    explanation: 'Lower pH means higher H⁺ concentration (more acidic). Higher pH means lower H⁺ concentration (more basic).',
    keyword: '0–14 scale',
    commonMistake: 'Thinking pH 0 is neutral — pH 0 is strongly acidic; pH 7 is neutral.',
    examTip: 'Know that blood pH is ~7.4, pure water is 7, stomach acid is ~1.5, and lemon juice is ~2.',
    memoryTrick: '"7 is heaven (neutral), below 7 is hell (acidic), above 7 is high (basic)."',
  },
  {
    front: 'What is neutralisation? Write the general equation.',
    back: 'Neutralisation is the reaction of an acid with a base to form salt and water. HCl + NaOH → NaCl + H₂O.',
    definition: 'Neutralisation: Acid + Base → Salt + Water.',
    explanation: 'The H⁺ from the acid combines with OH⁻ from the base to form water (H₂O), and the remaining ions form a salt.',
    keyword: 'Salt + Water',
    commonMistake: 'Forgetting that neutralisation is exothermic — heat is always released.',
    examTip: 'Antacids (like Mg(OH)₂) neutralise excess stomach HCl — a common application question.',
    memoryTrick: '"Acid meets Base, Salt and Water take their place."',
  },
  {
    front: 'What is the chlor-alkali process? Name its three products and their uses.',
    back: 'Electrolysis of brine (NaCl solution): 2NaCl + 2H₂O → 2NaOH + Cl₂ + H₂. Products: NaOH (soap/paper), Cl₂ (water treatment), H₂ (fuel/rockets).',
    definition: 'Chlor-alkali process: Electrolysis of brine producing NaOH, Cl₂, and H₂.',
    explanation: 'When electricity is passed through brine, sodium chloride decomposes into sodium hydroxide, chlorine gas, and hydrogen gas.',
    keyword: '3 products from brine',
    commonMistake: 'Forgetting one of the three products — it is always NaOH, Cl₂, and H₂.',
    examTip: 'Know at least one use for each product: NaOH = soap/detergent, Cl₂ = disinfectant/water treatment, H₂ = fuel.',
    memoryTrick: '"Chlor = Cl₂, Alkali = NaOH, H₂ = Hydrogen" — the name tells you the products.',
  },
  {
    front: 'What is Plaster of Paris? Write its formula and why it must be stored in a moisture-proof container.',
    back: 'PoP is calcium sulphate hemihydrate (CaSO₄·½H₂O). It must be stored airtight because it absorbs moisture and sets into hard gypsum (CaSO₄·2H₂O).',
    definition: 'Plaster of Paris: Calcium sulphate hemihydrate, CaSO₄·½H₂O.',
    explanation: 'When PoP absorbs water, it undergoes a setting reaction: CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O (gypsum), becoming hard.',
    keyword: 'CaSO₄·½H₂O',
    commonMistake: 'Confusing PoP (½H₂O) with gypsum (2H₂O) — the water of crystallisation is different.',
    examTip: 'Know uses: casts for broken bones, statues, decorative ceiling designs.',
    memoryTrick: '"Half water = PoP, Two waters = Gypsum" — ½H₂O vs 2H₂O.',
  },
  {
    front: 'How does baking soda differ from washing soda? Give formulas and uses.',
    back: 'Baking soda = NaHCO₃ (sodium hydrogen carbonate, used in baking/antacid). Washing soda = Na₂CO₃·10H₂O (sodium carbonate decahydrate, used in glass/soap/cleaning).',
    definition: 'Baking soda: NaHCO₃. Washing soda: Na₂CO₃·10H₂O.',
    explanation: 'Baking soda releases CO₂ on heating, making batter rise. Washing soda is used to remove permanent hardness of water and in glass/soap manufacturing.',
    keyword: 'NaHCO₃ vs Na₂CO₃·10H₂O',
    commonMistake: 'Mixing up the two — baking soda has 1 H (NaHCO₃), washing soda has 10 H₂O (Na₂CO₃·10H₂O).',
    examTip: 'Baking soda on heating: 2NaHCO₃ → Na₂CO₃ + H₂O + CO₂. This CO₂ makes cakes fluffy.',
    memoryTrick: '"Baking = Bread (NaHCO₃), Washing = Water (Na₂CO₃·10H₂O)."',
  },
  {
    front: 'What happens when an acid reacts with a metal carbonate? Give the general reaction and a test for the gas evolved.',
    back: 'Acid + Metal carbonate → Salt + Water + CO₂. Example: CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. CO₂ turns limewater milky.',
    definition: 'Acid + Metal carbonate → Salt + Water + Carbon dioxide.',
    explanation: 'The CO₂ gas evolved can be tested by passing it through limewater (Ca(OH)₂), which turns milky due to CaCO₃ formation.',
    keyword: 'CO₂ → limewater milky',
    commonMistake: 'Forgetting that water is also produced — it is not just salt + CO₂.',
    examTip: 'Also know: Acid + Metal → Salt + H₂ (pop test). Acid + Metal bicarbonate → Salt + Water + CO₂.',
    memoryTrick: '"Carbonate gives CO₂, Metal gives H₂" — carbonate → limewater test, metal → pop test.',
  },
  {
    front: 'What is bleaching powder? How is it prepared and what are its uses?',
    back: 'Bleaching powder is CaOCl₂ (calcium oxychloride). Prepared: Ca(OH)₂ + Cl₂ → CaOCl₂ + H₂O. Uses: bleaching cotton/linen, disinfecting drinking water, making chloroform.',
    definition: 'Bleaching powder: Calcium oxychloride, CaOCl₂.',
    explanation: 'It is produced by the action of chlorine on dry slaked lime. It releases chlorine when exposed to air, which bleaches and disinfects.',
    keyword: 'CaOCl₂',
    commonMistake: 'Writing CaCl₂ instead of CaOCl₂ — bleaching powder is calcium oxychloride, not calcium chloride.',
    examTip: 'Know at least 3 uses: bleaching cotton/linen, disinfecting water, manufacturing chloroform.',
    memoryTrick: '"Ca + O + Cl₂ = Bleach" — CaOCl₂ has both O and Cl.',
  },
];

export const acidsBasesSaltsFormulas: FormulaCard[] = [
  {
    formula: 'pH = −log[H⁺]',
    label: 'pH of a solution',
    symbols: 'pH = acidity/basicity measure, [H⁺] = concentration of hydrogen (hydronium) ions in mol/L',
    units: 'pH is dimensionless (logarithmic scale); [H⁺] in mol/L (M)',
    usedFor: 'Measuring how acidic or basic a solution is on a 0–14 scale',
    conditions: 'Applies to aqueous solutions at 25°C. pH 7 = neutral, <7 = acidic, >7 = basic.',
    commonMistakes: 'Thinking pH 0 means no acid — pH 0 means 1 mol/L H⁺ (very strong acid). pH 14 means 1 mol/L OH⁻.',
    example: 'If [H⁺] = 10⁻³ mol/L, then pH = −log(10⁻³) = 3 (acidic). If [H⁺] = 10⁻⁹, pH = 9 (basic).',
    signConvention: 'Not applicable',
  },
  {
    formula: 'HCl + NaOH → NaCl + H₂O',
    label: 'Neutralisation Reaction',
    symbols: 'HCl = Hydrochloric acid, NaOH = Sodium hydroxide, NaCl = Sodium chloride (salt), H₂O = Water',
    units: 'No SI units — chemical equation',
    usedFor: 'Demonstrates neutralisation: acid + base → salt + water (exothermic)',
    conditions: 'Acid and base must be in proper mole ratio (1:1 for strong acid + strong base).',
    commonMistakes: 'Forgetting that heat is evolved — neutralisation is always exothermic.',
    example: 'When 36.5 g HCl reacts with 40 g NaOH, 58.5 g NaCl and 18 g H₂O are produced, along with heat (ΔH = −57.1 kJ/mol).',
    signConvention: 'Not applicable',
  },
  {
    formula: '2NaCl + 2H₂O → 2NaOH + Cl₂↑ + H₂↑',
    label: 'Chlor-Alkali Process',
    symbols: 'NaCl = Sodium chloride (brine), H₂O = Water, NaOH = Sodium hydroxide, Cl₂ = Chlorine, H₂ = Hydrogen',
    units: 'No SI units — chemical equation',
    usedFor: 'Industrial production of NaOH, Cl₂, and H₂ from brine via electrolysis',
    conditions: 'Requires electricity (electrolysis). Brine must be concentrated NaCl solution.',
    commonMistakes: 'Forgetting one of the three products — always NaOH, Cl₂, and H₂.',
    example: 'When electricity is passed through brine in an electrolytic cell, chlorine is released at the anode, hydrogen at the cathode, and NaOH is left in the solution.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O',
    label: 'Setting of Plaster of Paris',
    symbols: 'CaSO₄·½H₂O = Plaster of Paris, H₂O = Water, CaSO₄·2H₂O = Gypsum (hard solid)',
    units: 'No SI units — chemical equation',
    usedFor: 'Explains why PoP sets hard when mixed with water; used in casts and moulds',
    conditions: 'PoP must be mixed with the right amount of water. It must be stored dry to prevent premature setting.',
    commonMistakes: 'Confusing PoP (½H₂O) with gypsum (2H₂O) — they have different water of crystallisation.',
    example: 'A doctor mixes PoP powder with water and applies it around a broken bone. Within minutes, it sets into hard gypsum (CaSO₄·2H₂O), forming a rigid cast.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Ca(OH)₂ + Cl₂ → CaOCl₂ + H₂O',
    label: 'Preparation of Bleaching Powder',
    symbols: 'Ca(OH)₂ = Slaked lime, Cl₂ = Chlorine gas, CaOCl₂ = Bleaching powder (calcium oxychloride), H₂O = Water',
    units: 'No SI units — chemical equation',
    usedFor: 'Industrial preparation of bleaching powder',
    conditions: 'Chlorine gas is passed over dry slaked lime. The reaction occurs at room temperature.',
    commonMistakes: 'Writing CaCl₂ as the product — bleaching powder is CaOCl₂ (calcium oxychloride), not CaCl₂.',
    example: 'When chlorine gas is passed over dry slaked lime (Ca(OH)₂), bleaching powder (CaOCl₂) is formed. It is used for bleaching cotton and disinfecting water.',
    signConvention: 'Not applicable',
  },
];

export const metalsNonMetalsFlashcards: Flashcard[] = [
  {
    front: 'What is the reactivity series? Write the order of common metals.',
    back: 'A list of metals arranged in order of decreasing reactivity: K > Na > Ca > Mg > Al > Zn > Fe > Pb > Cu > H > Ag > Au.',
    definition: 'Reactivity series: A list of metals arranged in order of decreasing reactivity.',
    explanation: 'A more reactive metal can displace a less reactive metal from its salt solution. K is most reactive; Au is least reactive.',
    keyword: 'K Na Ca Mg Al Zn Fe Pb Cu H Ag Au',
    commonMistake: 'Placing H (hydrogen) in the wrong position — H is between Pb and Cu. Metals above H can displace H from acids.',
    examTip: 'Memorise the full series — it is essential for predicting displacement reactions.',
    memoryTrick: '"K Na Ca Mg Al Zn Fe Pb [H] Cu Ag Au" — metals above H react with acids to give H₂.',
  },
  {
    front: 'Why is sodium stored in kerosene?',
    back: 'Sodium is highly reactive and reacts violently with air (oxygen) and water, potentially catching fire. Kerosene prevents contact with air and moisture.',
    definition: 'Sodium storage: Stored under kerosene to prevent reaction with air and water.',
    explanation: 'Sodium reacts vigorously with cold water (2Na + 2H₂O → 2NaOH + H₂ + heat). The heat can ignite the H₂ gas. Kerosene cuts off air and water.',
    keyword: 'Highly reactive + water-sensitive',
    commonMistake: 'Writing that sodium is stored in water — sodium reacts explosively with water.',
    examTip: 'Also know: potassium is stored in kerosene for the same reason.',
    memoryTrick: '"Na and K love water too much" — so we keep them away in kerosene.',
  },
  {
    front: 'What is an ionic compound? Why does it conduct electricity only in molten or aqueous state?',
    back: 'A compound formed by electron transfer from a metal to a non-metal. In solid state, ions are fixed in a lattice and cannot move. In molten/aqueous state, ions are free to move and conduct.',
    definition: 'Ionic compound: A compound formed by the transfer of electrons from a metal to a non-metal.',
    explanation: 'In solid ionic compounds, ions are locked in a crystal lattice. When melted or dissolved, ions become free to move and carry charge.',
    keyword: 'Free ions = conductivity',
    commonMistake: 'Saying ionic compounds conduct in solid state — they do NOT. Only molten or dissolved.',
    examTip: 'Also know: ionic compounds have high melting points due to strong electrostatic forces between ions.',
    memoryTrick: '"Fixed ions = no conduction; Free ions = conduction" — solid = fixed, molten/aqueous = free.',
  },
  {
    front: 'What is the thermite reaction and where is it used?',
    back: 'Fe₂O₃ + 2Al → 2Fe + Al₂O₃. Aluminium displaces iron from iron oxide. The large heat melts iron, used for welding railway tracks.',
    definition: 'Thermite reaction: A displacement reaction where Al reduces Fe₂O₃ to Fe.',
    explanation: 'Aluminium is more reactive than iron. It takes oxygen from Fe₂O₃, releasing iron and enormous heat.',
    keyword: 'Displacement + welding',
    commonMistake: 'Confusing this with a regular oxidation — it is a displacement reaction.',
    examTip: 'Always mention the application (welding railway tracks) — it is frequently asked.',
    memoryTrick: '"Al steals O from Fe" — aluminium is the thief (reducing agent).',
  },
  {
    front: 'Differentiate between roasting and calcination.',
    back: 'Roasting: heating ore in excess air (used for sulphide ores, e.g., ZnS → ZnO + SO₂). Calcination: heating ore in limited/no air (used for carbonate ores, e.g., CaCO₃ → CaO + CO₂).',
    definition: 'Roasting: ore heated in excess air. Calcination: ore heated in absence/limited air.',
    explanation: 'Roasting converts sulphide ores to oxides by adding oxygen. Calcination removes CO₂ or water from carbonate/hydrated ores.',
    keyword: 'Roasting = sulphide, Calcination = carbonate',
    commonMistake: 'Mixing up which process is used for which ore type — roasting = sulphide, calcination = carbonate.',
    examTip: 'Know examples: Roasting: 2ZnS + 3O₂ → 2ZnO + 2SO₂. Calcination: ZnCO₃ → ZnO + CO₂.',
    memoryTrick: '"Roast in air (sulphide), Calcine without air (carbonate)."',
  },
  {
    front: 'What is galvanisation? Why is it done?',
    back: 'Coating iron or steel with a layer of zinc to prevent rusting. Zinc is more reactive than iron, so it gets oxidised first (sacrificial protection).',
    definition: 'Galvanisation: Coating iron/steel with zinc to prevent corrosion.',
    explanation: 'Zinc is above iron in the reactivity series. Even if the coating is scratched, zinc corrodes first, protecting iron.',
    keyword: 'Zn coating + sacrificial',
    commonMistake: 'Thinking galvanisation uses tin — tin (Sn) is below iron and would not protect it sacrificially.',
    examTip: 'Know that zinc continues to protect iron even if scratched, but tin does not.',
    memoryTrick: '"Zn takes the bullet for Fe" — zinc sacrifices itself to protect iron.',
  },
  {
    front: 'Name three alloys with their composition and uses.',
    back: 'Brass = Cu + Zn (decorative items). Bronze = Cu + Sn (statues, coins). Stainless steel = Fe + Ni + Cr (corrosion-resistant utensils).',
    definition: 'Alloy: A homogeneous mixture of two or more metals (or a metal and non-metal).',
    explanation: 'Alloys are made to improve properties like hardness, corrosion resistance, and low melting point compared to pure metals.',
    keyword: 'Homogeneous metal mixture',
    commonMistake: 'Confusing brass (Cu+Zn) with bronze (Cu+Sn) — brass has zinc, bronze has tin.',
    examTip: 'Also know: Solder = Pb + Sn (low melting point, used for electrical welding). Amalgam = any alloy with mercury.',
    memoryTrick: '"Brass = Zinky, Bronze = Tinny" — brass has Zn, bronze has Sn.',
  },
  {
    front: 'Why do ionic compounds have high melting points?',
    back: 'Because of the strong electrostatic forces of attraction between oppositely charged ions in the crystal lattice. Large energy is needed to break these bonds.',
    definition: 'Ionic compounds have high MP due to strong electrostatic attraction between ions.',
    explanation: 'The positive and negative ions are held together by strong Coulombic forces. Breaking these requires a lot of heat energy.',
    keyword: 'Strong electrostatic forces',
    commonMistake: 'Saying ionic compounds have low melting points — they actually have very high melting points.',
    examTip: 'Also know: ionic compounds are hard but brittle, and soluble in water but insoluble in organic solvents.',
    memoryTrick: '"Strong bonds = High heat needed" — electrostatic attraction is very strong in ionic lattices.',
  },
];

export const metalsNonMetalsFormulas: FormulaCard[] = [
  {
    formula: '2K + 2H₂O → 2KOH + H₂↑',
    label: 'Reaction of Potassium with Cold Water',
    symbols: 'K = Potassium, H₂O = Water, KOH = Potassium hydroxide, H₂ = Hydrogen gas',
    units: 'No SI units — chemical equation',
    usedFor: 'Demonstrates that highly reactive metals react with cold water to produce H₂ gas',
    conditions: 'Potassium is highly reactive; reaction is violent and exothermic. H₂ can catch fire.',
    commonMistakes: 'Writing K₂O instead of KOH — potassium forms a hydroxide, not just an oxide, with cold water.',
    example: 'A small piece of potassium is dropped into cold water. It reacts violently, producing H₂ gas which catches fire with a lilac flame (K characteristic).',
    signConvention: 'Not applicable',
  },
  {
    formula: '3Fe + 4H₂O → Fe₃O₄ + 4H₂↑',
    label: 'Reaction of Iron with Steam',
    symbols: 'Fe = Iron, H₂O = Steam, Fe₃O₄ = Iron(II,III) oxide (magnetite), H₂ = Hydrogen',
    units: 'No SI units — chemical equation',
    usedFor: 'Shows that iron does not react with cold water but reacts with steam to produce H₂',
    conditions: 'Requires steam (high temperature). Iron does not react with cold water.',
    commonMistakes: 'Writing Fe₂O₃ instead of Fe₃O₄ — iron with steam forms Fe₃O₄ (magnetite), not Fe₂O₃.',
    example: 'Heated iron wool is placed in a stream of steam. Hydrogen gas is collected, and a black coating of Fe₃O₄ forms on the iron.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Fe₂O₃ + 2Al → 2Fe + Al₂O₃',
    label: 'Thermite Reaction (Displacement)',
    symbols: 'Fe₂O₃ = Iron(III) oxide, Al = Aluminium, Fe = Iron, Al₂O₃ = Aluminium oxide',
    units: 'No SI units — chemical equation',
    usedFor: 'Welding railway tracks; demonstrates displacement and exothermic reaction',
    conditions: 'Al must be more reactive than Fe (it is). Reaction is initiated by a magnesium fuse/heat.',
    commonMistakes: 'Identifying the wrong reducing agent — Al is the reducing agent (gets oxidised), Fe₂O₃ is the oxidising agent (gets reduced).',
    example: 'A thermite mixture of 160 g Fe₂O₃ and 54 g Al is ignited. The reaction produces 112 g Fe and 102 g Al₂O₃, with enough heat to melt the iron for welding.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Zn + CuSO₄ → ZnSO₄ + Cu',
    label: 'Displacement Reaction',
    symbols: 'Zn = Zinc, CuSO₄ = Copper sulphate, ZnSO₄ = Zinc sulphate, Cu = Copper',
    units: 'No SI units — chemical equation',
    usedFor: 'Demonstrates that a more reactive metal (Zn) displaces a less reactive metal (Cu) from its salt solution',
    conditions: 'Zn must be above Cu in the reactivity series (it is). The reaction occurs in aqueous solution.',
    commonMistakes: 'Writing Cu + ZnSO₄ → CuSO₄ + Zn — copper cannot displace zinc because Cu is less reactive.',
    example: 'A zinc strip is placed in blue copper sulphate solution. The blue colour fades as ZnSO₄ (colourless) forms, and a reddish-brown deposit of Cu appears on the zinc.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Cu + ZnSO₄ → No reaction',
    label: 'No Displacement (Cu is less reactive than Zn)',
    symbols: 'Cu = Copper, ZnSO₄ = Zinc sulphate',
    units: 'No SI units — chemical equation',
    usedFor: 'Demonstrates that a less reactive metal cannot displace a more reactive metal from its salt',
    conditions: 'Cu is below Zn in the reactivity series, so no reaction occurs.',
    commonMistakes: 'Writing that Cu displaces Zn — it cannot, because Cu is less reactive than Zn.',
    example: 'A copper strip is placed in zinc sulphate solution. No visible change occurs because copper is less reactive than zinc and cannot displace it.',
    signConvention: 'Not applicable',
  },
];

export const carbonCompoundsFlashcards: Flashcard[] = [
  {
    front: 'Why does carbon form covalent bonds and not ionic bonds?',
    back: 'Carbon has 4 valence electrons. It cannot lose 4 electrons (too much energy) or gain 4 electrons (too much repulsion). So it shares electrons, forming covalent bonds.',
    definition: 'Covalent bond: A bond formed by the sharing of electron pairs between atoms.',
    explanation: 'Carbon is tetravalent (4 valence electrons). Losing or gaining 4 electrons is energetically unfavourable, so carbon shares electrons with other atoms.',
    keyword: 'Tetravalency + sharing',
    commonMistake: 'Saying carbon "loses" or "gains" 4 electrons — it shares them.',
    examTip: 'Always mention: carbon cannot lose 4e⁻ (too much energy) or gain 4e⁻ (too much repulsion).',
    memoryTrick: '"Carbon Shares, Never Loses or Gains" — 4 electrons are shared, not transferred.',
  },
  {
    front: 'What is catenation? Why is it important?',
    back: 'Catenation is the ability of carbon to bond with other carbon atoms, forming long chains, branches, and rings. It is the basis of organic chemistry.',
    definition: 'Catenation: The ability of an element to form bonds with atoms of the same element.',
    explanation: 'Carbon-carbon bonds are strong and stable, allowing carbon to form millions of compounds with long chains, branches, and rings.',
    keyword: 'C-C bond formation',
    commonMistake: 'Thinking only carbon shows catenation — silicon also shows it, but to a much lesser extent.',
    examTip: 'Catenation + tetravalency together explain why carbon forms so many compounds.',
    memoryTrick: '"Catenation = Chain-making" — carbon links to carbon, making endless chains.',
  },
  {
    front: 'Write the general formulas for alkanes, alkenes, and alkynes.',
    back: 'Alkanes: CₙH₂ₙ₊₂ (single bonds, saturated). Alkenes: CₙH₂ₙ (double bond, unsaturated). Alkynes: CₙH₂ₙ₋₂ (triple bond, unsaturated).',
    definition: 'Alkanes: CₙH₂ₙ₊₂. Alkenes: CₙH₂ₙ. Alkynes: CₙH₂ₙ₋₂.',
    explanation: 'Alkanes have only single bonds (saturated). Alkenes have one C=C double bond. Alkynes have one C≡C triple bond.',
    keyword: 'Anes +2, Enes keep n, Ynes −2',
    commonMistake: 'Confusing alkene (CₙH₂ₙ) with alkane (CₙH₂ₙ₊₂) — alkenes have 2 fewer H.',
    examTip: 'Know examples: Methane CH₄, Ethene C₂H₄, Ethyne C₂H₂.',
    memoryTrick: '"Anes add 2, Enes keep n, Ynes subtract 2" — CₙH₂ₙ₊₂, CₙH₂ₙ, CₙH₂ₙ₋₂.',
  },
  {
    front: 'What is esterification? Write the reaction.',
    back: 'Esterification is the reaction of a carboxylic acid with an alcohol to form a sweet-smelling ester and water. CH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O (conc. H₂SO₄ catalyst).',
    definition: 'Esterification: Acid + Alcohol → Ester + Water (catalyst: conc. H₂SO₄).',
    explanation: 'The −OH of the acid and −H of the alcohol combine to form water, and the remaining parts join to form an ester (sweet-smelling).',
    keyword: 'Sweet-smelling ester',
    commonMistake: 'Confusing esterification with saponification — esterification makes an ester; saponification breaks an ester with base.',
    examTip: 'Esters are used in perfumes and flavourings due to their sweet smell.',
    memoryTrick: '"Acid + Alcohol = Ester (sweet smell) + Water."',
  },
  {
    front: 'What is saponification? Write the reaction.',
    back: 'Saponification is the reaction of an ester with a base (NaOH) to produce soap (sodium salt of fatty acid) and alcohol. CH₃COOC₂H₅ + NaOH → CH₃COONa + C₂H₅OH.',
    definition: 'Saponification: Ester + Base → Soap (salt of fatty acid) + Alcohol.',
    explanation: 'The base (NaOH) breaks the ester bond, producing the sodium salt of the acid (soap) and the alcohol.',
    keyword: 'Ester + NaOH → Soap',
    commonMistake: 'Confusing saponification (ester + base) with esterification (acid + alcohol).',
    examTip: 'Saponification is the reverse of esterification — esterification makes esters, saponification breaks them.',
    memoryTrick: '"Saponification = Soap-making" — ester + base = soap + alcohol.',
  },
  {
    front: 'Why do soaps not work in hard water? How do detergents differ?',
    back: 'Soaps form insoluble scum with Ca²⁺ and Mg²⁺ ions in hard water, wasting soap. Detergents are sodium salts of sulphonic acids that do not form scum and work in hard water.',
    definition: 'Soap: Na/K salt of long-chain fatty acid. Detergent: Na salt of sulphonic acid.',
    explanation: 'Hard water has Ca²⁺ and Mg²⁺ ions. Soaps react with these to form insoluble scum (Ca/Mg salts of fatty acids). Detergents form soluble salts, so no scum.',
    keyword: 'Scum in hard water',
    commonMistake: 'Saying detergents are "stronger" — they are not stronger, they just do not form scum.',
    examTip: 'This is one of the most frequently asked questions — know the scum formation explanation.',
    memoryTrick: '"Soap = Scum, Detergent = Dissolves" — in hard water.',
  },
  {
    front: 'What is hydrogenation? Write the reaction and give its application.',
    back: 'Hydrogenation is the addition of hydrogen to unsaturated oils to make them saturated (solid fats). Vegetable oil + H₂ →(Ni catalyst, 200°C)→ Vegetable ghee.',
    definition: 'Hydrogenation: Unsaturated oil + H₂ → Saturated fat (Ni catalyst, 200°C).',
    explanation: 'The C=C double bond in unsaturated oils is broken and H atoms are added, converting liquid oil to solid fat (ghee).',
    keyword: 'Ni catalyst + H₂',
    commonMistake: 'Forgetting the Ni catalyst and temperature — both are essential conditions.',
    examTip: 'Application: making vanaspati ghee from vegetable oil. Also used to make margarine.',
    memoryTrick: '"Oil + H₂ = Ghee" — hydrogen turns liquid oil into solid fat.',
  },
  {
    front: 'Name the three allotropes of carbon and give one property of each.',
    back: 'Diamond (hardest natural substance, tetrahedral). Graphite (good conductor, layered structure, lubricant). Fullerene (C₆₀, football-shaped, used in nanotechnology).',
    definition: 'Allotropes: Different physical forms of the same element with different structures.',
    explanation: 'In diamond, each C is bonded to 4 others (tetrahedral, no free electrons = insulator). In graphite, each C is bonded to 3 others (layers, one free electron = conductor).',
    keyword: 'Same element, different structures',
    commonMistake: 'Saying graphite is hard — graphite is soft and used as a lubricant because layers slide.',
    examTip: 'Know why diamond is hard (tetrahedral, strong bonds) and why graphite conducts (free electron in each C).',
    memoryTrick: '"Diamond = Hard (4 bonds), Graphite = Slippery (3 bonds + layers), Fullerene = Football (C₆₀)."',
  },
];

export const carbonCompoundsFormulas: FormulaCard[] = [
  {
    formula: 'CₙH₂ₙ₊₂ (Alkanes), CₙH₂ₙ (Alkenes), CₙH₂ₙ₋₂ (Alkynes)',
    label: 'General Formulas of Hydrocarbons',
    symbols: 'C = Carbon, H = Hydrogen, n = number of carbon atoms',
    units: 'No SI units — molecular formula pattern',
    usedFor: 'Determining the molecular formula of any alkane, alkene, or alkyne',
    conditions: 'n must be a positive integer. For alkenes and alkynes, n ≥ 2 (need at least 2 C for a double/triple bond).',
    commonMistakes: 'Confusing the three: Alkanes (CₙH₂ₙ₊₂, saturated), Alkenes (CₙH₂ₙ, one C=C), Alkynes (CₙH₂ₙ₋₂, one C≡C).',
    example: 'For n=3: Propane (alkane) = C₃H₈, Propene (alkene) = C₃H₆, Propyne (alkyne) = C₃H₄.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'CH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O',
    label: 'Esterification Reaction',
    symbols: 'CH₃COOH = Ethanoic acid (acetic acid), C₂H₅OH = Ethanol, CH₃COOC₂H₅ = Ethyl ethanoate (ester), H₂O = Water',
    units: 'No SI units — chemical equation',
    usedFor: 'Producing sweet-smelling esters used in perfumes and flavourings',
    conditions: 'Requires concentrated H₂SO₄ as catalyst and heat. The reaction is reversible.',
    commonMistakes: 'Forgetting the H₂SO₄ catalyst or writing it as a reactant instead of above the arrow.',
    example: 'When 60 g CH₃COOH reacts with 46 g C₂H₅OH (with conc. H₂SO₄), 88 g of ethyl ethanoate (sweet-smelling) and 18 g water are produced.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'C₂H₅OH →(H₂SO₄, 170°C)→ C₂H₄ + H₂O',
    label: 'Dehydration of Ethanol',
    symbols: 'C₂H₅OH = Ethanol, H₂SO₄ = Concentrated sulphuric acid (dehydrating agent), C₂H₄ = Ethene, H₂O = Water',
    units: 'No SI units — chemical equation',
    usedFor: 'Producing ethene from ethanol; demonstrates elimination/dehydration',
    conditions: 'Requires conc. H₂SO₄ at 170°C. At 140°C, a different product (diethyl ether) forms.',
    commonMistakes: 'Writing the wrong temperature — 170°C gives ethene, 140°C gives diethyl ether.',
    example: 'When ethanol is heated with conc. H₂SO₄ at 170°C, ethene gas is produced, which decolourises bromine water (test for unsaturation).',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Vegetable oil + H₂ →(Ni, 200°C)→ Vegetable ghee',
    label: 'Hydrogenation of Oils',
    symbols: 'Vegetable oil = unsaturated fat (contains C=C), H₂ = Hydrogen, Ni = Nickel catalyst, Vegetable ghee = saturated fat (solid)',
    units: 'No SI units — chemical equation',
    usedFor: 'Converting liquid vegetable oils to solid fats (vanaspati ghee, margarine)',
    conditions: 'Requires Ni catalyst at ~200°C and high pressure. The C=C double bond must be present (unsaturated).',
    commonMistakes: 'Forgetting the Ni catalyst or the temperature — both are essential.',
    example: 'Vegetable oil (liquid, unsaturated) is heated with H₂ in the presence of Ni catalyst at 200°C. The product is vegetable ghee (solid, saturated), used as cooking fat.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'CH₃COOC₂H₅ + NaOH → CH₃COONa + C₂H₅OH',
    label: 'Saponification Reaction',
    symbols: 'CH₃COOC₂H₅ = Ethyl ethanoate (ester), NaOH = Sodium hydroxide, CH₃COONa = Sodium ethanoate (soap), C₂H₅OH = Ethanol',
    units: 'No SI units — chemical equation',
    usedFor: 'Soap-making: breaking an ester with a base to produce soap and alcohol',
    conditions: 'Requires NaOH (base). The reaction is the reverse of esterification.',
    commonMistakes: 'Confusing saponification (ester + base) with esterification (acid + alcohol → ester).',
    example: 'When ethyl ethanoate is heated with NaOH, sodium ethanoate (a soap) and ethanol are produced. This is how soaps are manufactured from fats/oils.',
    signConvention: 'Not applicable',
  },
];

export const periodicClassificationFlashcards: Flashcard[] = [
  {
    front: 'What is Dobereiner\'s triads? Give one example.',
    back: 'Dobereiner arranged elements in groups of three (triads) where the atomic mass of the middle element was approximately the mean of the other two. Example: Li(7) - Na(23) - K(39); mean of 7 and 39 = 23.',
    definition: 'Dobereiner\'s triads: Groups of 3 elements where the middle element\'s atomic mass ≈ mean of the other two.',
    explanation: 'This was one of the earliest attempts at classification but worked for only a few triads.',
    keyword: 'Mean of first and third = second',
    commonMistake: 'Thinking Dobereiner classified all known elements — he could find only a few triads.',
    examTip: 'Know the Li-Na-K triad with atomic masses 7, 23, 39.',
    memoryTrick: '"Triad = Three" — the middle mass is the average of the outer two.',
  },
  {
    front: 'What was Newlands\' law of octaves?',
    back: 'When elements were arranged in order of increasing atomic mass, every 8th element repeated properties similar to the 1st, like musical octaves.',
    definition: 'Newlands\' law of octaves: Every 8th element repeats properties when arranged by increasing atomic mass.',
    explanation: 'Newlands was the first to note periodicity. However, the law worked only up to calcium (atomic mass 40) and failed for heavier elements.',
    keyword: 'Every 8th element repeats',
    commonMistake: 'Thinking the law worked for all elements — it failed beyond calcium.',
    examTip: 'Know the limitation: it did not work for elements beyond Ca and did not accommodate then-undiscovered elements.',
    memoryTrick: '"Octaves = 8" — like musical notes, every 8th element repeats.',
  },
  {
    front: 'What were the achievements and limitations of Mendeleev\'s periodic table?',
    back: 'Achievements: left gaps for undiscovered elements (eka-silicon=Ge, eka-aluminium=Ga), predicted their properties. Limitations: position of hydrogen, isotopes not placed, some elements ordered by mass not properties.',
    definition: 'Mendeleev\'s table: Elements arranged by increasing atomic mass, with gaps for undiscovered elements.',
    explanation: 'Mendeleev left gaps for elements he predicted would be discovered. When germanium and gallium were found, their properties matched his predictions.',
    keyword: 'Gaps for undiscovered elements',
    commonMistake: 'Saying Mendeleev arranged by atomic number — he arranged by atomic mass.',
    examTip: 'Know both achievements (gaps, predictions) and limitations (H position, isotopes, Co/Ni, Te/I anomalies).',
    memoryTrick: '"Mendeleev = Mass + Missing gaps" — arranged by mass, left gaps for missing elements.',
  },
  {
    front: 'State the Modern Periodic Law. Who proposed it?',
    back: 'Henry Moseley (1913) proposed: "Properties of elements are a periodic function of their atomic number."',
    definition: 'Modern Periodic Law: Properties of elements are a periodic function of their atomic number.',
    explanation: 'Moseley showed that atomic number (number of protons), not atomic mass, is the fundamental basis for periodicity. This removed all anomalies of Mendeleev\'s table.',
    keyword: 'Atomic number, not atomic mass',
    commonMistake: 'Confusing atomic number (protons) with atomic mass (protons + neutrons).',
    examTip: 'Know that the modern table is based on electronic configuration, which depends on atomic number.',
    memoryTrick: '"Moseley = Number" — modern law uses atomic number, not mass.',
  },
  {
    front: 'How does atomic size vary across a period and down a group? Why?',
    back: 'Across a period (L→R): atomic size decreases (nuclear charge increases, same shell, pulls electrons closer). Down a group: atomic size increases (new shell added each period).',
    definition: 'Atomic size: Across period = decreases. Down group = increases.',
    explanation: 'Across a period, protons increase but shells stay the same, so the nucleus pulls electrons closer. Down a group, a new shell is added, making the atom larger.',
    keyword: 'Period = smaller, Group = larger',
    commonMistake: 'Saying atomic size increases across a period — it actually decreases.',
    examTip: 'Be able to explain WHY: across a period, nuclear charge increases with same shell; down a group, new shells are added.',
    memoryTrick: '"Across = Shrink (more protons, same shell). Down = Grow (new shells)."',
  },
  {
    front: 'How does metallic character vary across a period and down a group?',
    back: 'Across a period (L→R): metallic character decreases (electronegativity increases). Down a group: metallic character increases (easier to lose electrons from larger atoms).',
    definition: 'Metallic character: Across period = decreases. Down group = increases.',
    explanation: 'Metals lose electrons easily. Across a period, atomic size decreases and nuclear charge increases, making it harder to lose electrons. Down a group, atomic size increases, making it easier to lose electrons.',
    keyword: 'Metals = lose electrons',
    commonMistake: 'Saying metallic character increases across a period — it decreases.',
    examTip: 'Know that non-metallic character is the opposite: increases across a period, decreases down a group.',
    memoryTrick: '"Left = Metal, Right = Non-metal. Down = More metallic."',
  },
  {
    front: 'Why are noble gases (Group 18) inert?',
    back: 'Noble gases have completely filled outer shells (octet: ns²np⁶). With no tendency to lose, gain, or share electrons, they do not react under normal conditions.',
    definition: 'Noble gases: Group 18 elements with completely filled outer shells, making them inert.',
    explanation: 'A full octet (8 electrons in the outermost shell) is the most stable configuration. Noble gases have no need to react.',
    keyword: 'Full octet = inert',
    commonMistake: 'Saying noble gases have 8 valence electrons — He has only 2 (duplet, which is also stable for K shell).',
    examTip: 'Know that He has 2 valence electrons (K shell full), while Ne, Ar, Kr, Xe, Rn have 8.',
    memoryTrick: '"Full shell = No reaction" — noble gases are happy with their complete octet/duplet.',
  },
  {
    front: 'How many elements are there in each period of the modern periodic table?',
    back: 'Period 1: 2, Period 2: 8, Period 3: 8, Period 4: 18, Period 5: 18, Period 6: 32, Period 7: incomplete.',
    definition: 'Period elements: 2, 8, 8, 18, 18, 32, rest.',
    explanation: 'The number of elements in a period follows the electron shell capacity: 2n² where n = shell number (Period 1: 2×1²=2, Period 2: 2×2²=8, etc.).',
    keyword: '2, 8, 8, 18, 18, 32',
    commonMistake: 'Writing 2, 8, 18, 32 — the pattern is 2, 8, 8, 18, 18, 32 (not simply 2n²).',
    examTip: 'Know that period number = number of electron shells.',
    memoryTrick: '"2-8-8-18-18-32" — the pattern repeats: 2, then 8 twice, then 18 twice, then 32.',
  },
];

export const periodicClassificationFormulas: FormulaCard[] = [
  {
    formula: 'Maximum electrons in a shell = 2n²',
    label: 'Electron Shell Capacity',
    symbols: 'n = shell number (1 for K, 2 for L, 3 for M, 4 for N)',
    units: 'n is dimensionless (shell number); result is number of electrons',
    usedFor: 'Determining the maximum number of electrons in each shell and the number of elements in each period',
    conditions: 'n must be a positive integer (1, 2, 3, 4...). Applies to Bohr\'s model of the atom.',
    commonMistakes: 'Confusing shell number with period number — they are the same, but the formula gives maximum electrons, not the number of elements in every period (periods 4-5 hold 18, not 32).',
    example: 'K shell (n=1): 2(1)² = 2 electrons. L shell (n=2): 2(2)² = 8 electrons. M shell (n=3): 2(3)² = 18 electrons.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Period number = Number of electron shells',
    label: 'Period-Shells Relationship',
    symbols: 'Period number = horizontal row number in the periodic table',
    units: 'Dimensionless (count of shells)',
    usedFor: 'Determining the number of electron shells an element has based on its period',
    conditions: 'Applies to the modern periodic table based on atomic number.',
    commonMistakes: 'Confusing period (horizontal) with group (vertical) — period = shells, group = valence electrons.',
    example: 'Sodium (Na, atomic no. 11) is in Period 3, so it has 3 electron shells. Its configuration is 2, 8, 1.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Group number = Number of valence electrons (for Groups 1-2 and 13-18)',
    label: 'Group-Valence Electron Relationship',
    symbols: 'Group number = vertical column number in the periodic table',
    units: 'Dimensionless (count of valence electrons)',
    usedFor: 'Determining the number of valence electrons from the group number',
    conditions: 'Applies to main group elements (Groups 1-2 = s-block, Groups 13-18 = p-block). Transition metals (Groups 3-12) follow different rules.',
    commonMistakes: 'Forgetting that Groups 3-12 (transition metals) do not follow this simple rule.',
    example: 'Magnesium (Mg) is in Group 2, so it has 2 valence electrons. Configuration: 2, 8, 2. Chlorine (Cl) is in Group 17, so it has 7 valence electrons.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Valency across a period: 1, 2, 3, 4, 3, 2, 1, 0',
    label: 'Valency Trend Across a Period',
    symbols: 'Valency = combining capacity of an element',
    units: 'Dimensionless',
    usedFor: 'Predicting the valency of elements across a period',
    conditions: 'Applies to periods 2 and 3 of the modern periodic table (Li to Ne, Na to Ar).',
    commonMistakes: 'Writing valency as continuously increasing — it increases from 1 to 4, then decreases from 4 to 0.',
    example: 'Period 2: Li(1), Be(2), B(3), C(4), N(3), O(2), F(1), Ne(0). Carbon has the maximum valency of 4.',
    signConvention: 'Not applicable',
  },
];
