import type { Flashcard, FormulaCard } from '../revision-content';

export const ourEnvironmentFlashcards: Flashcard[] = [
  {
    front: 'What is an ecosystem? Name its two main components.',
    back: 'A self-contained unit of living (biotic: producers, consumers, decomposers) and non-living (abiotic: air, water, soil, sunlight) components that interact and function together.',
    definition: 'Ecosystem: Biotic (living) + abiotic (non-living) components interacting as a unit.',
    explanation: 'Producers make food, consumers eat, decomposers break down dead matter. Abiotic factors like sunlight, water, and soil support life. Together they form a functioning ecosystem.',
    keyword: 'Biotic + Abiotic',
    commonMistake: 'Forgetting decomposers as a biotic component — they are essential for nutrient cycling.',
    examTip: 'Know examples: a pond, a forest, a garden are all ecosystems.',
    memoryTrick: '"Eco = Living + Non-living" — biotic + abiotic = ecosystem.',
  },
  {
    front: 'What is a food chain? Give an example with 4 trophic levels.',
    back: 'A sequence showing energy flow from the sun through producers to consumers. Example: Grass (T1) → Grasshopper (T2) → Frog (T3) → Snake (T4) → Hawk (T5).',
    definition: 'Food chain: Sun → Producer → Primary consumer → Secondary consumer → Tertiary consumer.',
    explanation: 'Energy flows from the sun to producers (plants) who make food by photosynthesis. Primary consumers (herbivores) eat plants. Secondary consumers eat herbivores. Tertiary consumers eat secondary consumers.',
    keyword: 'Sun → T1 → T2 → T3 → T4',
    commonMistake: 'Forgetting to include the sun as the ultimate energy source.',
    examTip: 'Know that decomposers are NOT a trophic level — they break down all levels.',
    memoryTrick: '"Sun feeds Grass, Grass feeds Bug, Bug feeds Frog, Frog feeds Snake."',
  },
  {
    front: 'What is the 10% law of energy transfer? Who proposed it?',
    back: 'Only about 10% of energy at one trophic level is available to the next. The rest (90%) is lost as heat in metabolic processes. Proposed by Lindeman.',
    definition: '10% law: Only 10% of energy transfers to the next trophic level.',
    explanation: 'At each level, organisms use most energy for their own life processes (respiration, movement, growth) and lose it as heat. Only ~10% becomes body mass that the next level can eat.',
    keyword: '10% up, 90% lost as heat',
    commonMistake: 'Saying 90% transfers — it is the opposite: only 10% transfers, 90% is lost.',
    examTip: 'This explains why food chains have only 4-5 levels — not enough energy remains.',
    memoryTrick: '"Ten percent travels, rest is lost as heat."',
  },
  {
    front: 'What is the difference between a food chain and a food web?',
    back: 'A food chain is a single linear pathway of energy flow. A food web is a network of interconnected food chains showing all possible feeding relationships in an ecosystem.',
    definition: 'Food chain: linear. Food web: interconnected network of food chains.',
    explanation: 'In nature, organisms eat multiple things and are eaten by multiple predators. A food web shows all these connections, making it more realistic than a single chain.',
    keyword: 'Chain = linear, Web = network',
    commonMistake: 'Saying a food web is simpler — it is more complex and realistic than a single chain.',
    examTip: 'Know that food webs provide stability — if one food source fails, organisms have alternatives.',
    memoryTrick: '"Chain = One path, Web = Many paths."',
  },
  {
    front: 'Differentiate between biodegradable and non-biodegradable waste with examples.',
    back: 'Biodegradable: can be decomposed by microorganisms (vegetable peels, paper, cloth). Non-biodegradable: cannot be decomposed (plastic, glass, metal, DDT).',
    definition: 'Biodegradable: rot naturally. Non-biodegradable: do not rot.',
    explanation: 'Biodegradable waste is broken down by bacteria/fungi into harmless substances. Non-biodegradable waste persists in the environment for hundreds of years, causing pollution.',
    keyword: 'Can rot vs Cannot rot',
    commonMistake: 'Classifying paper as non-biodegradable — paper is biodegradable (made from plant fibres).',
    examTip: 'Know that non-biodegradable waste accumulates and causes soil/water pollution.',
    memoryTrick: '"Bio = Rot, Non-bio = Not."',
  },
  {
    front: 'What is the ozone layer? How is it formed and depleted?',
    back: 'A layer of ozone (O₃) in the stratosphere (15-35 km) that absorbs UV radiation. Formed: O₂ + O → O₃. Depleted by CFCs which release chlorine atoms that destroy ozone.',
    definition: 'Ozone layer: O₃ in stratosphere, absorbs UV. CFCs deplete it.',
    explanation: 'UV light splits O₂ into oxygen atoms. O + O₂ → O₃ (ozone). CFCs release chlorine (Cl) which reacts with O₃: Cl + O₃ → ClO + O₂, destroying the ozone layer.',
    keyword: 'O₃ absorbs UV, CFCs destroy O₃',
    commonMistake: 'Saying CFCs form ozone — CFCs destroy ozone, not form it.',
    examTip: 'Know the Montreal Protocol (1987) — an international agreement to reduce CFC production.',
    memoryTrick: '"O₃ saves from UV, CFC kills O₃."',
  },
  {
    front: 'What is biological magnification? Explain with an example.',
    back: 'The accumulation of non-biodegradable toxins in increasing concentrations at higher trophic levels. Example: DDT sprayed on crops → plants → small fish → large fish → hawks (highest concentration).',
    definition: 'Biological magnification: Toxins increase in concentration at higher trophic levels.',
    explanation: 'Non-biodegradable toxins like DDT cannot be excreted. They accumulate in the body. At each trophic level, the consumer eats many organisms from the level below, concentrating the toxin. Top predators have the highest levels.',
    keyword: 'Toxins concentrate upward',
    commonMistake: 'Saying toxins decrease at higher levels — they increase (concentrate).',
    examTip: 'Know that biological magnification affects only non-biodegradable substances, not all substances.',
    memoryTrick: '"Higher up the chain = Higher the toxin" — top predators are most affected.',
  },
  {
    front: 'Why is energy flow in an ecosystem unidirectional?',
    back: 'Energy enters from the sun, flows through producers to consumers to decomposers, and is ultimately lost as heat. It does not cycle back — only nutrients cycle.',
    definition: 'Energy flow: unidirectional (sun → producers → consumers → heat). Nutrients: cyclic.',
    explanation: 'Solar energy is captured by producers, passed to consumers, and eventually released as heat through respiration. This heat cannot be recaptured. In contrast, nutrients (C, N, O) cycle between biotic and abiotic components.',
    keyword: 'Energy = one-way, Nutrients = cycle',
    commonMistake: 'Saying energy cycles back to the sun — it does not. Energy flow is one-way.',
    examTip: 'Know the difference: energy is unidirectional, nutrients are cyclic.',
    memoryTrick: '"Energy goes one way, Nutrients go round and round."',
  },
];

export const ourEnvironmentFormulas: FormulaCard[] = [
  {
    formula: 'Energy transfer: ~10% per trophic level',
    label: '10% Law of Energy Transfer',
    symbols: '10% = fraction of energy available to the next trophic level; remaining 90% is lost as heat',
    units: 'Percentage (%) or fraction',
    usedFor: 'Calculating how much energy is available at each trophic level in a food chain',
    conditions: 'Applies to all ecosystems. The 90% lost is used for metabolic processes (respiration, movement) and lost as heat.',
    commonMistakes: 'Saying 90% transfers — only 10% transfers. The rest is lost as heat.',
    example: 'If producers have 10,000 J of energy: T1 (producers) = 10,000 J. T2 (primary consumers) = 1,000 J (10%). T3 (secondary consumers) = 100 J (10%). T4 (tertiary consumers) = 10 J (10%). Only 10 J reaches the top predator.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'O₂ + O → O₃ (ozone formation)',
    label: 'Ozone Layer Formation',
    symbols: 'O₂ = Oxygen molecule, O = Oxygen atom (from UV splitting of O₂), O₃ = Ozone',
    units: 'No SI units — chemical equation',
    usedFor: 'Describing how the ozone layer is formed in the stratosphere',
    conditions: 'Occurs in the stratosphere (15-35 km altitude). UV light splits O₂ into two O atoms. Each O atom combines with O₂ to form O₃.',
    commonMistakes: 'Saying CFCs form ozone — CFCs destroy ozone. Ozone forms naturally from O₂ + O.',
    example: 'UV radiation from the sun splits an O₂ molecule into two oxygen atoms. One oxygen atom combines with another O₂ molecule to form O₃ (ozone), which then absorbs more UV radiation.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Cl + O₃ → ClO + O₂ (ozone depletion by CFCs)',
    label: 'Ozone Depletion Reaction',
    symbols: 'Cl = Chlorine atom (from CFC breakdown), O₃ = Ozone, ClO = Chlorine monoxide, O₂ = Oxygen',
    units: 'No SI units — chemical equation',
    usedFor: 'Explaining how CFCs destroy the ozone layer',
    conditions: 'CFCs (chlorofluorocarbons) release chlorine atoms when they break down in the stratosphere. One Cl atom can destroy up to 100,000 O₃ molecules.',
    commonMistakes: 'Saying CFCs form ozone — they destroy it. Also, not knowing that one Cl atom can destroy many O₃ molecules.',
    example: 'A CFC molecule releases a chlorine atom. The Cl atom reacts with O₃ to form ClO and O₂. The ClO then reacts with another O atom to release Cl again, which destroys more O₃. One Cl atom can destroy up to 100,000 ozone molecules.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Food chain: Sun → Producer (T1) → Primary consumer (T2) → Secondary consumer (T3) → Tertiary consumer (T4)',
    label: 'Trophic Levels in a Food Chain',
    symbols: 'T1 = producers (plants), T2 = primary consumers (herbivores), T3 = secondary consumers (carnivores), T4 = tertiary consumers (top predators)',
    units: 'No SI units — biological hierarchy',
    usedFor: 'Describing the flow of energy through trophic levels in a food chain',
    conditions: 'Energy decreases at each level due to the 10% law. Most food chains have 4-5 levels because energy runs out.',
    commonMistakes: 'Including decomposers as a trophic level — they are not. They operate at all levels, breaking down dead organisms.',
    example: 'Grass (T1, 10,000 J) → Grasshopper (T2, 1,000 J) → Frog (T3, 100 J) → Snake (T4, 10 J) → Hawk (T5, 1 J). Energy decreases at each level.',
    signConvention: 'Not applicable',
  },
];

export const sustainableManagementFlashcards: Flashcard[] = [
  {
    front: 'What is sustainable development?',
    back: 'Development that meets the needs of the present without compromising the ability of future generations to meet their own needs.',
    definition: 'Sustainable development: Present needs met without harming future generations.',
    explanation: 'We must use resources at a rate that allows them to regenerate. Over-exploitation of water, forests, and fossil fuels harms future generations.',
    keyword: 'Present + Future',
    commonMistake: 'Saying sustainable development means stopping all development — it means responsible development.',
    examTip: 'Know the quote: "We have not inherited the Earth from our ancestors; we have borrowed it from our children."',
    memoryTrick: '"Borrowed from our children" — use responsibly so future generations have enough.',
  },
  {
    front: 'What are the 3Rs of waste management? State their order of priority.',
    back: 'Reduce (use less), Reuse (use again), Recycle (process into new). Priority: Reduce > Reuse > Recycle. Reducing is best because it prevents waste creation.',
    definition: '3Rs: Reduce > Reuse > Recycle (in order of priority).',
    explanation: 'Reduce means using less in the first place (best). Reuse means using items again instead of throwing them away. Recycle means processing waste into new products (last resort).',
    keyword: 'Reduce first, then Reuse, then Recycle',
    commonMistake: 'Saying recycle is the best option — reducing is better because it prevents waste creation.',
    examTip: 'Know why: reducing saves resources, reusing saves energy and materials, recycling uses energy to process.',
    memoryTrick: '"Reduce before you Reuse, Reuse before you Recycle."',
  },
  {
    front: 'Why are coal and petroleum called non-renewable resources?',
    back: 'Because they were formed from dead organisms over millions of years and cannot be replenished on a human timescale. Once used, they are gone forever.',
    definition: 'Non-renewable: formed over millions of years, cannot be replenished.',
    explanation: 'Coal formed from dead plant matter buried millions of years ago. Petroleum formed from dead marine organisms. The rate of formation is extremely slow compared to the rate of consumption.',
    keyword: 'Millions of years to form',
    commonMistake: 'Saying coal and petroleum are renewable because they come from nature — they take millions of years to form.',
    examTip: 'Know that burning them also produces CO₂ (greenhouse gas) and SO₂ (acid rain).',
    memoryTrick: '"Fossil fuels = Finite fuels" — they took millions of years and will run out.',
  },
  {
    front: 'What is rainwater harvesting? Why is it important?',
    back: 'Collecting and storing rainwater for reuse or to recharge groundwater. Important because India has 16% of world population but only 4% of water resources.',
    definition: 'Rainwater harvesting: Collect rainwater for reuse or groundwater recharge.',
    explanation: 'Rainwater is collected from rooftops, filtered, and either stored in tanks or directed into the ground to recharge aquifers. This helps maintain groundwater levels.',
    keyword: 'Collect + recharge',
    commonMistake: 'Saying rainwater harvesting only means storing water in tanks — it also includes recharging groundwater.',
    examTip: 'Know that India has 16% of world population but only 4% of water resources — a common exam point.',
    memoryTrick: '"Harvest rain, recharge aquifer" — collect and store or send underground.',
  },
  {
    front: 'What was the Chipko Movement? Who led it?',
    back: 'A forest conservation movement where villagers in Uttarakhand hugged trees to prevent them from being felled. Led by Sundarlal Bahuguna.',
    definition: 'Chipko Movement: Villagers hugged trees to prevent felling. Led by Sundarlal Bahuguna.',
    explanation: 'In the 1970s, villagers in Uttarakhand literally hugged trees when contractors came to cut them. The word "Chipko" means "to hug". This non-violent movement saved thousands of trees.',
    keyword: 'Hug trees',
    commonMistake: 'Confusing Chipko with the Green Revolution — Chipko is about forest conservation.',
    examTip: 'Know the leader (Sundarlal Bahuguna) and location (Uttarakhand).',
    memoryTrick: '"Chipko = Hug" — villagers hugged trees to save them.',
  },
  {
    front: 'Who was Amrita Devi Bishnoi? What was her sacrifice?',
    back: 'A woman from Rajasthan who sacrificed her life along with 363 others to protect Khejri trees from being cut by the king\'s men. The Bishnoi community continues to protect nature.',
    definition: 'Amrita Devi Bishnoi: Sacrificed her life to protect Khejri trees in Rajasthan.',
    explanation: 'In 1730, Amrita Devi hugged a Khejri tree and was killed. 363 Bishnoi villagers followed, each hugging a tree and being killed. The king eventually stopped the felling. This is one of the earliest environmental movements.',
    keyword: '363 sacrificed for Khejri trees',
    commonMistake: 'Confusing this with the Chipko Movement — Amrita Devi Bishnoi was in Rajasthan (1730), Chipko was in Uttarakhand (1970s).',
    examTip: 'Know the tree (Khejri), the state (Rajasthan), and the number (363).',
    memoryTrick: '"Bishnoi = Brave" — 363 people died protecting trees in 1730.',
  },
  {
    front: 'What is the Ganga Action Plan? When was it launched?',
    back: 'A plan launched in 1985 to reduce pollution in the Ganga by treating domestic and industrial waste before it enters the river.',
    definition: 'Ganga Action Plan: Launched 1985 to clean the Ganga by treating waste.',
    explanation: 'The Ganga is polluted by domestic sewage, industrial effluents, and agricultural runoff. The plan aims to set up treatment plants so that waste is treated before being discharged into the river.',
    keyword: '1985 + waste treatment',
    commonMistake: 'Saying it was launched in 2000 or later — it was launched in 1985.',
    examTip: 'Know that the plan involves setting up sewage treatment plants (STPs) along the river.',
    memoryTrick: '"Ganga Action = 1985" — India\'s first major river cleaning project.',
  },
  {
    front: 'What is drip irrigation? Why is it important?',
    back: 'A method of watering plants drop by drop at the roots using pipes and emitters. It reduces water wastage by minimizing evaporation and delivering water only where needed.',
    definition: 'Drip irrigation: Drop-by-drop watering at roots, minimizing waste.',
    explanation: 'Traditional flooding wastes 50-70% of water through evaporation and runoff. Drip irrigation delivers water directly to the root zone, saving up to 70% of water and increasing crop yield.',
    keyword: 'Drop by drop at roots',
    commonMistake: 'Saying drip irrigation uses sprinklers — it uses emitters at the roots, not sprinklers.',
    examTip: 'Know advantages: saves water, reduces weed growth, increases yield, suitable for dry areas.',
    memoryTrick: '"Drip = Drop at the root" — water goes where it is needed, not wasted.',
  },
];

export const sustainableManagementFormulas: FormulaCard[] = [
  {
    formula: '3Rs: Reduce > Reuse > Recycle',
    label: 'Waste Management Hierarchy',
    symbols: 'Reduce = use less resources, Reuse = use items again, Recycle = process waste into new products',
    units: 'Not applicable — priority order',
    usedFor: 'Guiding waste management practices in order of environmental benefit',
    conditions: 'Reduce is always the best option (prevents waste). Reuse is second best (saves energy). Recycle is last (uses energy to process).',
    commonMistakes: 'Saying recycle is the best option — reducing is better because it prevents waste creation in the first place.',
    example: 'Instead of buying 5 plastic bottles and recycling them (recycle), buy 1 reusable bottle and use it daily (reuse). Even better: avoid buying bottles and use a glass from home (reduce).',
    signConvention: 'Not applicable',
  },
  {
    formula: '5Rs: Refuse, Reduce, Reuse, Recycle, Repurpose',
    label: 'Extended Waste Management',
    symbols: 'Refuse = say no to unnecessary items, Reduce = use less, Reuse = use again, Recycle = process waste, Repurpose = use items for a different purpose',
    units: 'Not applicable — priority order',
    usedFor: 'A more comprehensive waste management approach beyond the basic 3Rs',
    conditions: 'Refuse is the highest priority (avoid creating waste). Repurpose means using an old item for a new purpose (e.g., using jars as plant pots).',
    commonMistakes: 'Confusing refuse (say no) with reduce (use less). Refuse means not accepting unnecessary items at all.',
    example: 'Refuse: say no to plastic bags at the shop. Reduce: buy in bulk to reduce packaging. Reuse: use cloth bags. Recycle: recycle paper and plastic. Repurpose: turn old tires into garden planters.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Rainwater harvesting → Groundwater recharge',
    label: 'Rainwater Harvesting Process',
    symbols: 'Rainwater harvesting = collecting and storing rainwater; Groundwater recharge = directing rainwater into the ground to replenish aquifers',
    units: 'Not applicable — process description',
    usedFor: 'Conserving water by collecting rainwater for direct use or to recharge depleted groundwater',
    conditions: 'Requires a collection surface (rooftop), filtration system, and either a storage tank or a recharge pit. Most effective in areas with seasonal rainfall.',
    commonMistakes: 'Thinking rainwater harvesting only means storing water in tanks — it also includes recharging groundwater aquifers.',
    example: 'Rainwater from a 100 m² rooftop is collected through gutters, filtered to remove debris, and directed into a recharge pit. This water percolates into the ground, raising the water table by several metres over the monsoon season.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'India: 16% world population, 4% water resources',
    label: 'Water Scarcity in India',
    symbols: '16% = India\'s share of world population, 4% = India\'s share of world\'s water resources',
    units: 'Percentages',
    usedFor: 'Highlighting the need for water conservation in India',
    conditions: 'India has a large population but limited freshwater resources. This imbalance creates water stress, especially in arid regions.',
    commonMistakes: 'Reversing the numbers — it is 16% population, 4% water (not the other way around).',
    example: 'India has 1.4 billion people (16% of world) but only 4% of the world\'s freshwater. This means per capita water availability is very low, making water conservation essential through rainwater harvesting, drip irrigation, and reducing wastage.',
    signConvention: 'Not applicable',
  },
];
