import type { Flashcard, FormulaCard } from '../revision-content';

export const lightReflectionRefractionFlashcards: Flashcard[] = [
  {
    front: 'State the mirror formula and define each term.',
    back: '1/v + 1/u = 1/f. v = image distance from pole, u = object distance from pole, f = focal length from pole.',
    definition: 'Mirror formula: 1/v + 1/u = 1/f (with sign convention).',
    explanation: 'The formula relates the image distance (v), object distance (u), and focal length (f) of a spherical mirror. All distances are measured from the pole.',
    keyword: '1/v + 1/u = 1/f (note: PLUS sign)',
    commonMistake: 'Confusing the mirror formula (+) with the lens formula (−). Mirror uses 1/v + 1/u = 1/f; lens uses 1/v − 1/u = 1/f.',
    examTip: 'Always apply the sign convention before substituting values. Distances against incident light are negative.',
    memoryTrick: '"Mirror Plus, Lens Minus" — mirror formula has +, lens formula has −.',
  },
  {
    front: 'State the lens formula and define each term.',
    back: '1/v − 1/u = 1/f. v = image distance from optical centre, u = object distance from optical centre, f = focal length.',
    definition: 'Lens formula: 1/v − 1/u = 1/f (with sign convention).',
    explanation: 'The formula relates image distance, object distance, and focal length for a lens. Note the minus sign — this is the key difference from the mirror formula.',
    keyword: '1/v − 1/u = 1/f (note: MINUS sign)',
    commonMistake: 'Using + instead of − — the lens formula has a minus sign: 1/v − 1/u = 1/f.',
    examTip: 'Convex lens: f is positive. Concave lens: f is negative.',
    memoryTrick: '"Lens Minus" — 1/v − 1/u = 1/f.',
  },
  {
    front: 'What is the power of a lens? Give its formula and unit.',
    back: 'Power = 1/f (focal length in metres). Unit: dioptre (D). Convex lens = positive power, concave lens = negative power.',
    definition: 'Power of a lens: P = 1/f, where f is in metres. Unit: dioptre (D).',
    explanation: 'A lens with a shorter focal length bends light more, so it has higher power. 1 dioptre is the power of a lens with 1 metre focal length.',
    keyword: 'P = 1/f (metres), unit = D',
    commonMistake: 'Forgetting to convert focal length to metres — if f is in cm, divide by 100 first.',
    examTip: 'For combination of lenses in contact: P = P₁ + P₂.',
    memoryTrick: '"Short f = High power" — 1 m = 1 D, 0.5 m = 2 D, 2 m = 0.5 D.',
  },
  {
    front: 'What is magnification? Write the formula for mirrors and lenses.',
    back: 'm = height of image / height of object = −v/u. Positive m = erect/virtual image. Negative m = inverted/real image.',
    definition: 'Magnification: m = h\'/h = −v/u.',
    explanation: 'Magnification tells how much bigger or smaller the image is compared to the object. The sign indicates orientation: positive = erect, negative = inverted.',
    keyword: 'm = −v/u',
    commonMistake: 'Writing m = v/u without the negative sign — the sign is important for orientation.',
    examTip: '|m| > 1 = enlarged, |m| < 1 = diminished, |m| = 1 = same size.',
    memoryTrick: '"Minus v over u" — m = −v/u. Positive = upright, Negative = upside down.',
  },
  {
    front: 'What is the refractive index? Write the formula.',
    back: 'n = c/v, where c = speed of light in vacuum, v = speed of light in the medium. Also n = sin i / sin r (Snell\'s law).',
    definition: 'Refractive index: n = c/v = speed of light in vacuum / speed in medium.',
    explanation: 'The refractive index tells how much light slows down in a medium. Higher n = light slows more = more bending. For water n=1.33, glass n=1.5, diamond n=2.42.',
    keyword: 'n = c/v',
    commonMistake: 'Writing n = v/c (reversed) — it is c/v (vacuum speed divided by medium speed, always ≥ 1).',
    examTip: 'Know common values: n_water = 1.33, n_glass = 1.5, n_diamond = 2.42.',
    memoryTrick: '"c over v" — vacuum speed is always faster, so n ≥ 1.',
  },
  {
    front: 'What type of image is always formed by a convex mirror?',
    back: 'A convex mirror always forms a virtual, erect, and diminished image, regardless of the object position.',
    definition: 'Convex mirror: Always virtual, erect, diminished image.',
    explanation: 'The convex mirror diverges light rays. The reflected rays appear to come from behind the mirror, forming a virtual image that is always smaller than the object.',
    keyword: 'Always virtual + erect + diminished',
    commonMistake: 'Saying a convex mirror can form a real image — it cannot, ever.',
    examTip: 'Know uses: rear-view mirrors (wider field of view), blind corner mirrors.',
    memoryTrick: '"Convex = Always virtual" — no matter where the object is.',
  },
  {
    front: 'What is the relationship between focal length (f) and radius of curvature (R)?',
    back: 'f = R/2. The focal length is half the radius of curvature for a spherical mirror.',
    definition: 'f = R/2 (focal length = radius of curvature / 2).',
    explanation: 'For a spherical mirror, the focus lies midway between the pole and the centre of curvature. So f = R/2.',
    keyword: 'f = R/2',
    commonMistake: 'Writing f = R or f = 2R — it is f = R/2 (half).',
    examTip: 'If R = 20 cm, then f = 10 cm. This is a quick calculation often asked in MCQs.',
    memoryTrick: '"Half the radius" — f is always R/2.',
  },
  {
    front: 'What are the uses of concave and convex mirrors?',
    back: 'Concave: shaving mirror, dentist\'s mirror, torch reflector, solar furnace. Convex: rear-view mirror, blind corner mirrors.',
    definition: 'Concave mirror uses: magnification, focusing. Convex mirror uses: wider field of view.',
    explanation: 'Concave mirrors converge light and can form magnified images (shaving mirror). Convex mirrors diverge light and provide a wider field of view (rear-view).',
    keyword: 'Concave = converge, Convex = diverge',
    commonMistake: 'Saying a convex mirror is used as a shaving mirror — that is a concave mirror.',
    examTip: 'Know at least 2 uses for each type of mirror.',
    memoryTrick: '"Concave = Close-up (shaving), Convex = Wide-view (rear-view)."',
  },
];

export const lightReflectionRefractionFormulas: FormulaCard[] = [
  {
    formula: '1/v + 1/u = 1/f',
    label: 'Mirror Formula',
    symbols: 'v = image distance from pole, u = object distance from pole, f = focal length from pole',
    units: 'v, u, f all in metres (m) or centimetres (cm) — must be consistent',
    usedFor: 'Finding the image distance or focal length of a spherical mirror (concave or convex)',
    conditions: 'New Cartesian sign convention: distances measured against incident light are negative. Concave mirror: f is negative. Convex mirror: f is positive.',
    commonMistakes: 'Confusing with lens formula (which has a minus sign). For mirrors, it is 1/v + 1/u = 1/f (plus).',
    example: 'Concave mirror, f = −10 cm, object at u = −15 cm. 1/v = 1/f − 1/u = 1/(−10) − 1/(−15) = −1/10 + 1/15 = (−3+2)/30 = −1/30. So v = −30 cm (real image, 30 cm in front of mirror).',
    signConvention: 'New Cartesian: All distances measured from pole. Against incident light = negative. Concave mirror f < 0, convex mirror f > 0.',
  },
  {
    formula: '1/v − 1/u = 1/f',
    label: 'Lens Formula',
    symbols: 'v = image distance from optical centre, u = object distance from optical centre, f = focal length',
    units: 'v, u, f all in metres (m) or centimetres (cm) — must be consistent',
    usedFor: 'Finding the image distance or focal length of a lens (convex or concave)',
    conditions: 'New Cartesian sign convention: Convex lens: f is positive. Concave lens: f is negative. Object is on the left (u is negative).',
    commonMistakes: 'Using + instead of − — the lens formula has a MINUS sign: 1/v − 1/u = 1/f. Also forgetting sign convention.',
    example: 'Convex lens, f = +20 cm, object at u = −30 cm. 1/v = 1/f + 1/u = 1/20 + 1/(−30) = 1/20 − 1/30 = (3−2)/60 = 1/60. So v = +60 cm (real image, 60 cm on the other side).',
    signConvention: 'New Cartesian: Distances measured from optical centre. Against incident light = negative. Convex lens f > 0, concave lens f < 0.',
  },
  {
    formula: 'P = 1/f',
    label: 'Power of a Lens',
    symbols: 'P = power of lens (in dioptres, D), f = focal length in metres (m)',
    units: 'P: dioptre (D), where 1 D = 1 m⁻¹. f must be in metres.',
    usedFor: 'Calculating the converging or diverging ability of a lens',
    conditions: 'f must be in metres. Convex lens: P is positive. Concave lens: P is negative. For lenses in contact: P = P₁ + P₂.',
    commonMistakes: 'Forgetting to convert f from cm to m. If f = 50 cm, then P = 1/0.5 = 2 D, not 1/50.',
    example: 'A convex lens has f = 25 cm = 0.25 m. P = 1/0.25 = +4 D. A concave lens has f = −50 cm = −0.5 m. P = 1/(−0.5) = −2 D.',
    signConvention: 'Convex lens: P > 0 (positive). Concave lens: P < 0 (negative).',
  },
  {
    formula: 'm = −v/u = h\'/h',
    label: 'Magnification',
    symbols: 'm = magnification (dimensionless), v = image distance, u = object distance, h\' = image height, h = object height',
    units: 'm is dimensionless (ratio). v, u, h\', h must be in consistent units.',
    usedFor: 'Determining the size and orientation of the image relative to the object',
    conditions: 'Same sign convention as the mirror/lens formula. Positive m = erect/virtual image. Negative m = inverted/real image.',
    commonMistakes: 'Writing m = v/u without the negative sign — the sign determines image orientation.',
    example: 'If v = −30 cm and u = −15 cm (concave mirror), m = −(−30)/(−15) = −2. Image is inverted and twice the size of the object (|m| = 2).',
    signConvention: 'Positive m = erect image (virtual). Negative m = inverted image (real). |m| > 1 = enlarged, |m| < 1 = diminished.',
  },
  {
    formula: 'n = c/v',
    label: 'Refractive Index',
    symbols: 'n = refractive index (dimensionless), c = speed of light in vacuum (3 × 10⁸ m/s), v = speed of light in the medium (m/s)',
    units: 'n is dimensionless. c and v in m/s. n ≥ 1 always.',
    usedFor: 'Measuring how much light slows down in a medium compared to vacuum',
    conditions: 'c is always ≥ v, so n ≥ 1. For vacuum, n = 1. For air, n ≈ 1.0003 ≈ 1.',
    commonMistakes: 'Writing n = v/c (reversed) — it is c/v. Also, n is always ≥ 1 for any medium.',
    example: 'Speed of light in glass = 2 × 10⁸ m/s. n_glass = c/v = (3 × 10⁸)/(2 × 10⁸) = 1.5. This means light travels 1.5 times slower in glass than in vacuum.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'f = R/2',
    label: 'Focal Length and Radius of Curvature',
    symbols: 'f = focal length, R = radius of curvature (distance from pole to centre of curvature)',
    units: 'f and R in the same units (m or cm)',
    usedFor: 'Relating the focal length of a spherical mirror to its radius of curvature',
    conditions: 'Applies to spherical mirrors (concave and convex). For concave: f and R are negative. For convex: f and R are positive.',
    commonMistakes: 'Writing f = R or f = 2R — it is f = R/2 (half the radius).',
    example: 'A concave mirror has radius of curvature R = 30 cm. Then f = R/2 = 30/2 = 15 cm. Since it is concave, f = −15 cm (by sign convention).',
    signConvention: 'Concave mirror: f < 0, R < 0. Convex mirror: f > 0, R > 0.',
  },
];

export const humanEyeFlashcards: Flashcard[] = [
  {
    front: 'What is accommodation? How does the eye focus on near and distant objects?',
    back: 'Accommodation is the ability of the eye lens to change its focal length via ciliary muscles. Near: muscles contract, lens thickens, f decreases. Far: muscles relax, lens thins, f increases.',
    definition: 'Accommodation: The eye lens changes focal length to focus on objects at different distances.',
    explanation: 'The ciliary muscles control the curvature of the lens. For near objects, the lens becomes thicker (more curved, shorter f). For distant objects, it becomes thinner (less curved, longer f).',
    keyword: 'Ciliary muscles + lens curvature',
    commonMistake: 'Saying the retina changes — it is the lens that changes shape, not the retina.',
    examTip: 'Know: ciliary muscles contract for near vision, relax for far vision.',
    memoryTrick: '"Near = Thick lens (contract), Far = Thin lens (relax)."',
  },
  {
    front: 'What is myopia? How is it corrected?',
    back: 'Myopia (short-sightedness): the image of a distant object forms in front of the retina. Corrected with a concave (diverging) lens of suitable focal length.',
    definition: 'Myopia: Distant objects focus in front of the retina. Correction: concave lens.',
    explanation: 'The eyeball is too long or the lens is too curved. Light from distant objects converges before reaching the retina. A concave lens diverges the light so it focuses on the retina.',
    keyword: 'Concave lens',
    commonMistake: 'Using a convex lens for myopia — myopia needs a concave (diverging) lens.',
    examTip: 'Know the power formula: if far point = d, then f = −d, P = −1/d.',
    memoryTrick: '"Myopia = Minus (concave lens)" — short-sighted = diverging lens.',
  },
  {
    front: 'What is hypermetropia? How is it corrected?',
    back: 'Hypermetropia (long-sightedness): the image of a near object forms behind the retina. Corrected with a convex (converging) lens.',
    definition: 'Hypermetropia: Near objects focus behind the retina. Correction: convex lens.',
    explanation: 'The eyeball is too short or the lens is too flat. Light from near objects converges behind the retina. A convex lens adds extra convergence so the image falls on the retina.',
    keyword: 'Convex lens',
    commonMistake: 'Using a concave lens for hypermetropia — it needs a convex (converging) lens.',
    examTip: 'Know: if near point = d, then f = +d, P = +1/d.',
    memoryTrick: '"Hypermetropia = High/Plus (convex lens)" — long-sighted = converging lens.',
  },
  {
    front: 'What is dispersion? Which colour bends most and least?',
    back: 'Dispersion is the splitting of white light into its constituent colours by a prism. Violet bends most (shortest wavelength), red bends least (longest wavelength).',
    definition: 'Dispersion: Splitting of white light into VIBGYOR spectrum by a prism.',
    explanation: 'Different colours have different wavelengths and hence different refractive indices. Violet (shortest λ) has the highest n and bends most. Red (longest λ) has the lowest n and bends least.',
    keyword: 'VIBGYOR: Violet most, Red least',
    commonMistake: 'Saying red bends most — red bends least; violet bends most.',
    examTip: 'Know the order: VIBGYOR (Violet, Indigo, Blue, Green, Yellow, Orange, Red).',
    memoryTrick: '"Violet = Violent (bends most), Red = Relaxed (bends least)."',
  },
  {
    front: 'Why is the sky blue? Why is the sunset red?',
    back: 'Sky blue: air molecules scatter shorter wavelengths (blue) more (Rayleigh scattering ∝ 1/λ⁴). Sunset red: at sunset, light travels more atmosphere; blue is scattered away, leaving red/orange.',
    definition: 'Sky blue: Rayleigh scattering (shorter λ scattered more). Sunset red: blue scattered away, red reaches eye.',
    explanation: 'Scattering intensity ∝ 1/λ⁴. Blue (short λ) scatters ~10× more than red. During the day, scattered blue reaches us from all directions. At sunset, light passes through more atmosphere, so most blue is scattered away and only red/orange reaches us.',
    keyword: '1/λ⁴ (Rayleigh scattering)',
    commonMistake: 'Saying the sky is blue because of reflection from the ocean — it is due to scattering by air molecules.',
    examTip: 'Know the formula: scattering ∝ 1/λ⁴. Shorter wavelength = more scattering.',
    memoryTrick: '"Blue scatters, Red passes" — short wavelengths scatter, long pass through.',
  },
  {
    front: 'Why do stars twinkle but planets do not?',
    back: 'Stars are point sources; atmospheric refraction changes continuously, causing the star image to shift (twinkle). Planets are disc-like (extended) sources; the shifts average out, so no twinkling.',
    definition: 'Stars twinkle (point source, atmospheric refraction). Planets don\'t (extended source, shifts average out).',
    explanation: 'Atmospheric density varies constantly, causing the path of starlight to bend slightly differently each moment. For point sources (stars), this causes the image to flicker. For extended sources (planets), the many point sources on the disc average out the variation.',
    keyword: 'Point vs extended source',
    commonMistake: 'Saying planets don\'t twinkle because they are closer — it is because they are extended (disc) sources.',
    examTip: 'Also know: advanced sunrise and delayed sunset (~2 min each) are caused by atmospheric refraction.',
    memoryTrick: '"Stars = Points (flicker), Planets = Discs (steady)."',
  },
  {
    front: 'What is the Tyndall effect? Give one example.',
    back: 'The scattering of light by particles in a colloid or fine suspension, making the light beam visible. Example: sunlight visible through dust in a dark room.',
    definition: 'Tyndall effect: Scattering of light by colloidal particles, making the beam visible.',
    explanation: 'When light passes through a colloid (dust, fog, smoke), the particles are large enough to scatter light but small enough to stay suspended. This makes the light path visible.',
    keyword: 'Colloidal scattering',
    commonMistake: 'Confusing Tyndall effect with refraction — Tyndall is scattering, not bending.',
    examTip: 'Know that the blue colour of the sky is also due to scattering (but by air molecules, not Tyndall effect in the strict sense).',
    memoryTrick: '"Tyndall = See the beam" — you can see the light path through a colloid.',
  },
  {
    front: 'What is presbyopia? How is it corrected?',
    back: 'Presbyopia is an age-related defect where the eye lens loses flexibility, affecting both near and far vision. Corrected with bifocal lenses (convex for near, concave for far).',
    definition: 'Presbyopia: Age-related vision defect; corrected with bifocal lenses.',
    explanation: 'With age, the ciliary muscles weaken and the lens becomes less flexible. The near point recedes. Bifocal lenses have the upper part (concave) for distant vision and lower part (convex) for reading.',
    keyword: 'Bifocal lenses',
    commonMistake: 'Confusing presbyopia with hypermetropia — presbyopia affects both near and far vision with age.',
    examTip: 'Know that bifocal lenses have two regions: upper = concave (distance), lower = convex (reading).',
    memoryTrick: '"Presbyopia = Old age, Bifocal = Two-in-one."',
  },
];

export const humanEyeFormulas: FormulaCard[] = [
  {
    formula: 'P = 1/f (for corrective lens)',
    label: 'Power of Corrective Lens',
    symbols: 'P = power in dioptres (D), f = focal length in metres (m)',
    units: 'P: dioptre (D). f: metres (m).',
    usedFor: 'Calculating the power of a lens needed to correct myopia or hypermetropia',
    conditions: 'For myopia: f = −d (d = far point distance), P is negative. For hypermetropia: f = +d (d = near point distance), P is positive.',
    commonMistakes: 'Forgetting the sign: myopia = negative power (concave), hypermetropia = positive power (convex). Also, f must be in metres.',
    example: 'Myopia: A person cannot see beyond 2 m. f = −2 m. P = 1/(−2) = −0.5 D (concave lens). Hypermetropia: Near point = 50 cm = 0.5 m. f = +0.5 m. P = 1/0.5 = +2 D (convex lens).',
    signConvention: 'Myopia: P < 0 (concave lens). Hypermetropia: P > 0 (convex lens).',
  },
  {
    formula: 'n = c/v',
    label: 'Refractive Index',
    symbols: 'n = refractive index, c = speed of light in vacuum (3 × 10⁸ m/s), v = speed in medium',
    units: 'n is dimensionless. c, v in m/s.',
    usedFor: 'Determining how much light slows in a medium (relevant to eye lens and cornea)',
    conditions: 'n ≥ 1 always. For the cornea, n ≈ 1.38; for the eye lens, n ≈ 1.40.',
    commonMistakes: 'Writing n = v/c (reversed) — it is c/v.',
    example: 'The refractive index of the cornea is about 1.38. Speed of light in the cornea = c/n = (3 × 10⁸)/1.38 ≈ 2.17 × 10⁸ m/s.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Scattering intensity ∝ 1/λ⁴',
    label: 'Rayleigh Scattering Law',
    symbols: 'Scattering intensity = amount of light scattered, λ = wavelength of light',
    units: 'Dimensionless proportionality (λ in nm or m)',
    usedFor: 'Explaining why the sky is blue and sunsets are red',
    conditions: 'Applies when particles are much smaller than the wavelength of light (air molecules). For larger particles (clouds, fog), scattering is less wavelength-dependent.',
    commonMistakes: 'Saying longer wavelengths scatter more — it is the opposite. Shorter λ (blue) scatters more.',
    example: 'Blue light (λ ≈ 400 nm) scatters (400/700)⁴ ≈ 10.7 times more than red light (λ ≈ 700 nm). This is why the sky appears blue — blue is scattered in all directions by air molecules.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Advanced sunrise / Delayed sunset ≈ 2 minutes',
    label: 'Atmospheric Refraction Effect',
    symbols: '2 minutes = time difference between actual and apparent sunrise/sunset',
    units: 'Minutes (time)',
    usedFor: 'Explaining why the sun is visible before actual sunrise and after actual sunset',
    conditions: 'Due to atmospheric refraction — the atmosphere bends sunlight downward. When the sun is just below the horizon, its light is refracted so we still see it.',
    commonMistakes: 'Saying the sun actually rises earlier — it does not. The apparent (visible) sunrise is ~2 min before the actual (geometric) sunrise.',
    example: 'The sun appears to rise about 2 minutes before it actually crosses the horizon, and appears to set about 2 minutes after it actually goes below the horizon. This is due to atmospheric refraction bending the light.',
    signConvention: 'Not applicable',
  },
];

export const electricityFlashcards: Flashcard[] = [
  {
    front: 'State Ohm\'s law. Write the formula.',
    back: 'The current through a conductor is directly proportional to the potential difference across it, at constant temperature. V = IR.',
    definition: 'Ohm\'s law: V = IR (at constant temperature).',
    explanation: 'V = potential difference (volts), I = current (amperes), R = resistance (ohms). If you double the voltage, the current doubles (at constant R).',
    keyword: 'V = IR',
    commonMistake: 'Forgetting the condition "at constant temperature" — resistance increases with temperature.',
    examTip: 'Know the V-I graph: a straight line through the origin for an ohmic resistor.',
    memoryTrick: '"V = I times R" — voltage equals current times resistance.',
  },
  {
    front: 'What is the formula for resistance in terms of resistivity?',
    back: 'R = ρL/A. R = resistance, ρ = resistivity, L = length, A = cross-sectional area.',
    definition: 'R = ρL/A — resistance depends on material (ρ), length (L), and area (A).',
    explanation: 'Resistance increases with length (longer wire = more R) and decreases with area (thicker wire = less R). Resistivity (ρ) is a property of the material.',
    keyword: 'R ∝ L, R ∝ 1/A',
    commonMistake: 'Forgetting that resistivity depends on material and temperature, NOT on length or area.',
    examTip: 'Know that ρ is in Ω·m. Copper has low ρ (good conductor); nichrome has high ρ (heating element).',
    memoryTrick: '"Longer = More R, Thicker = Less R" — R ∝ L/A.',
  },
  {
    front: 'Write the formulas for equivalent resistance in series and parallel.',
    back: 'Series: R = R₁ + R₂ + R₃ (add directly). Parallel: 1/R = 1/R₁ + 1/R₂ + 1/R₃ (add reciprocals).',
    definition: 'Series: R_eq = R₁ + R₂ + R₃. Parallel: 1/R_eq = 1/R₁ + 1/R₂ + 1/R₃.',
    explanation: 'In series, the same current flows through all resistors, and resistances add up. In parallel, the same voltage is across all resistors, and reciprocals add up.',
    keyword: 'Series = add, Parallel = reciprocals',
    commonMistake: 'Adding resistances directly in parallel — for parallel, you add reciprocals, not resistances.',
    examTip: 'Series R_eq is always greater than the largest resistor. Parallel R_eq is always less than the smallest resistor.',
    memoryTrick: '"Series = Sum, Parallel = Reciprocal sum."',
  },
  {
    front: 'Write the three formulas for electric power.',
    back: 'P = VI = I²R = V²/R. P = power (watts), V = voltage, I = current, R = resistance.',
    definition: 'Electric power: P = VI = I²R = V²/R.',
    explanation: 'Use P = VI when V and I are known. Use P = I²R when I and R are known. Use P = V²/R when V and R are known.',
    keyword: 'P = VI = I²R = V²/R',
    commonMistake: 'Using the wrong formula for the given data — choose based on what values you know.',
    examTip: 'Know the commercial unit: 1 kWh = 3.6 × 10⁶ J. Electricity bills use kWh.',
    memoryTrick: '"PVI squared R" — P = VI = I²R = V²/R.',
  },
  {
    front: 'State Joule\'s law of heating. Write the formula.',
    back: 'The heat produced in a conductor is directly proportional to the square of current, resistance, and time. H = I²Rt.',
    definition: 'Joule\'s law: H = I²Rt (heat = current² × resistance × time).',
    explanation: 'More current = much more heat (I² relationship). This is why heating elements use high-resistance alloys like nichrome.',
    keyword: 'H = I²Rt',
    commonMistake: 'Writing H = IRt instead of H = I²Rt — it is I squared, not I.',
    examTip: 'Know applications: electric heater, iron, toaster, fuse (melts when I is too high).',
    memoryTrick: '"I squared R t" — current is squared, so doubling current quadruples heat.',
  },
  {
    front: 'What is the commercial unit of electric energy? Convert it to joules.',
    back: '1 kWh (kilowatt-hour). 1 kWh = 1000 W × 3600 s = 3.6 × 10⁶ J.',
    definition: '1 kWh = 3.6 × 10⁶ J. It is the energy used when 1 kW power runs for 1 hour.',
    explanation: 'Electricity bills are measured in kWh (called "units"). 1 unit = 1 kWh. To convert to joules: 1000 W × 3600 s = 3,600,000 J.',
    keyword: '1 kWh = 3.6 × 10⁶ J',
    commonMistake: 'Writing 1 kWh = 3600 J — it is 3.6 × 10⁶ J (1000 × 3600).',
    examTip: 'To calculate bill: Energy (kWh) = Power (kW) × Time (h). Then multiply by rate per unit.',
    memoryTrick: '"1 kW for 1 hour = 1 unit = 3.6 million joules."',
  },
  {
    front: 'Why are alloys used in heating elements instead of pure metals?',
    back: 'Alloys like nichrome have high resistivity and do not oxidise at high temperatures. Pure metals would oxidise and break.',
    definition: 'Heating elements use alloys (nichrome) for high resistivity and oxidation resistance.',
    explanation: 'Nichrome (Ni + Cr) has high resistivity (more heat for same current) and a high melting point. It does not oxidise even when red-hot, making it ideal for heaters.',
    keyword: 'High ρ + no oxidation',
    commonMistake: 'Saying alloys are used because they are cheap — they are used for high resistivity and oxidation resistance.',
    examTip: 'Know that tungsten is used in bulbs (high melting point 3380°C) and nichrome in heaters.',
    memoryTrick: '"Nichrome = Heat without burning" — high ρ + no oxidation.',
  },
  {
    front: 'How are ammeters and voltmeters connected in a circuit?',
    back: 'Ammeter: connected in series (low resistance, measures current). Voltmeter: connected in parallel (high resistance, measures voltage).',
    definition: 'Ammeter: series, low resistance. Voltmeter: parallel, high resistance.',
    explanation: 'An ammeter must let all current pass through it, so it has very low resistance and is in series. A voltmeter must not draw current, so it has very high resistance and is in parallel.',
    keyword: 'Ammeter = series, Voltmeter = parallel',
    commonMistake: 'Connecting a voltmeter in series or an ammeter in parallel — this would give wrong readings or damage the meter.',
    examTip: 'Know why: ammeter has low R (so it doesn\'t reduce current), voltmeter has high R (so it doesn\'t draw current).',
    memoryTrick: '"Ammeter in Series (low R), Voltmeter in Parallel (high R)."',
  },
];

export const electricityFormulas: FormulaCard[] = [
  {
    formula: 'V = IR',
    label: 'Ohm\'s Law',
    symbols: 'V = potential difference (volts, V), I = current (amperes, A), R = resistance (ohms, Ω)',
    units: 'V: volt (V), I: ampere (A), R: ohm (Ω). 1 V = 1 A × 1 Ω.',
    usedFor: 'Calculating voltage, current, or resistance in a circuit',
    conditions: 'Valid at constant temperature. Resistance increases with temperature for metals. Applies to ohmic (linear) resistors only.',
    commonMistakes: 'Forgetting the "constant temperature" condition. Also, not using SI units consistently.',
    example: 'A resistor of 10 Ω has a current of 2 A flowing through it. V = IR = 2 × 10 = 20 V. The potential difference across the resistor is 20 volts.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'R = ρL/A',
    label: 'Resistance Formula',
    symbols: 'R = resistance (Ω), ρ = resistivity (Ω·m), L = length (m), A = cross-sectional area (m²)',
    units: 'R: ohm (Ω), ρ: ohm-metre (Ω·m), L: metre (m), A: square metre (m²)',
    usedFor: 'Calculating resistance of a wire based on its material, length, and thickness',
    conditions: 'ρ depends on material and temperature, NOT on L or A. R is proportional to L and inversely proportional to A.',
    commonMistakes: 'Thinking ρ depends on L or A — it does not. ρ is a material property. Also, confusing area with diameter — A = πr², not πd.',
    example: 'A copper wire has L = 2 m, A = 1 × 10⁻⁶ m², ρ = 1.68 × 10⁻⁸ Ω·m. R = (1.68 × 10⁻⁸ × 2)/(1 × 10⁻⁶) = 3.36 × 10⁻² = 0.0336 Ω.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Series: R_eq = R₁ + R₂ + R₃ | Parallel: 1/R_eq = 1/R₁ + 1/R₂ + 1/R₃',
    label: 'Equivalent Resistance',
    symbols: 'R_eq = equivalent resistance, R₁, R₂, R₃ = individual resistances',
    units: 'All in ohms (Ω)',
    usedFor: 'Calculating the total resistance of resistors connected in series or parallel',
    conditions: 'Series: same current through all. Parallel: same voltage across all. Series R_eq > largest resistor. Parallel R_eq < smallest resistor.',
    commonMistakes: 'Adding resistances directly in parallel — for parallel, add reciprocals, then take the reciprocal of the sum.',
    example: 'Series: 2Ω + 3Ω + 5Ω = 10Ω. Parallel: 1/R = 1/2 + 1/3 + 1/6 = (3+2+1)/6 = 6/6 = 1. So R_eq = 1Ω. For two resistors in parallel: R = R₁R₂/(R₁+R₂).',
    signConvention: 'Not applicable',
  },
  {
    formula: 'P = VI = I²R = V²/R',
    label: 'Electric Power',
    symbols: 'P = power (watts, W), V = voltage (V), I = current (A), R = resistance (Ω)',
    units: 'P: watt (W), where 1 W = 1 V × 1 A. Also 1 kW = 1000 W.',
    usedFor: 'Calculating the rate at which electrical energy is consumed',
    conditions: 'Use P = VI when V and I are known. Use P = I²R when I and R are known. Use P = V²/R when V and R are known.',
    commonMistakes: 'Using the wrong variant for the given data. Also, forgetting that 1 kW = 1000 W.',
    example: 'A bulb rated 220 V, 100 W. I = P/V = 100/220 = 0.45 A. R = V²/P = 220²/100 = 48400/100 = 484 Ω. If used for 10 hours: Energy = P × t = 0.1 kW × 10 h = 1 kWh = 1 unit.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'H = I²Rt',
    label: 'Joule\'s Law of Heating',
    symbols: 'H = heat energy (joules, J), I = current (A), R = resistance (Ω), t = time (s)',
    units: 'H: joule (J), I: ampere (A), R: ohm (Ω), t: second (s)',
    usedFor: 'Calculating the heat produced when current flows through a resistor',
    conditions: 'All energy is converted to heat (no other work done). Applies to purely resistive circuits.',
    commonMistakes: 'Writing H = IRt instead of H = I²Rt — it is I squared. Also, t must be in seconds.',
    example: 'A heater has R = 20 Ω and carries I = 5 A for t = 60 s. H = (5)² × 20 × 60 = 25 × 20 × 60 = 30,000 J = 30 kJ of heat produced.',
    signConvention: 'Not applicable',
  },
  {
    formula: '1 kWh = 3.6 × 10⁶ J',
    label: 'Commercial Unit of Energy',
    symbols: 'kWh = kilowatt-hour, J = joule',
    units: '1 kWh = 1000 W × 3600 s = 3,600,000 J = 3.6 × 10⁶ J',
    usedFor: 'Calculating electricity bills (measured in "units" = kWh)',
    conditions: '1 kWh = energy consumed when 1 kW (1000 W) power is used for 1 hour.',
    commonMistakes: 'Writing 1 kWh = 3600 J — it is 3.6 × 10⁶ J (1000 × 3600). Also, time must be in hours for kWh calculation.',
    example: 'A 100 W bulb is used for 5 hours/day for 30 days. Energy = 0.1 kW × 5 h × 30 = 15 kWh = 15 units. At ₹8/unit, bill = 15 × 8 = ₹120.',
    signConvention: 'Not applicable',
  },
];

export const magneticEffectsFlashcards: Flashcard[] = [
  {
    front: 'State the right-hand thumb rule.',
    back: 'If you hold a current-carrying conductor in your right hand with the thumb pointing in the direction of current, your fingers curl in the direction of the magnetic field.',
    definition: 'Right-hand thumb rule: Thumb = current direction, Fingers = magnetic field direction.',
    explanation: 'The magnetic field around a straight current-carrying conductor is in the form of concentric circles. The direction of these circles is given by the right-hand thumb rule.',
    keyword: 'Thumb = I, Fingers = B',
    commonMistake: 'Using the left hand instead of the right — it is the RIGHT hand for field direction.',
    examTip: 'Know that reversing the current reverses the field direction.',
    memoryTrick: '"Right hand: Thumb = Current, Fingers = Field" — like grabbing the wire.',
  },
  {
    front: 'State Fleming\'s left-hand rule. Where is it used?',
    back: 'Thumb = force/motion, forefinger = magnetic field, middle finger = current. Used in electric motors (force on a current-carrying conductor in a magnetic field).',
    definition: 'Fleming\'s left-hand rule: FBI — Force (thumb), B-field (forefinger), I-current (middle finger). Used for motors.',
    explanation: 'When a current-carrying conductor is placed in a magnetic field, it experiences a force. The direction of this force is given by the left-hand rule.',
    keyword: 'Left = Motor',
    commonMistake: 'Confusing left-hand (motor) with right-hand (generator) rule.',
    examTip: 'Know: LEFT hand for motors (force → motion), RIGHT hand for generators (motion → current).',
    memoryTrick: '"Left for Motors, Right for Generators" — FBI: Force, B, I.',
  },
  {
    front: 'State Fleming\'s right-hand rule. Where is it used?',
    back: 'Thumb = motion of conductor, forefinger = magnetic field, middle finger = induced current. Used in electric generators (electromagnetic induction).',
    definition: 'Fleming\'s right-hand rule: Thumb = motion, Forefinger = field, Middle = induced current. Used for generators.',
    explanation: 'When a conductor moves in a magnetic field, an EMF is induced. The direction of the induced current is given by the right-hand rule.',
    keyword: 'Right = Generator',
    commonMistake: 'Confusing right-hand (generator) with left-hand (motor) rule.',
    examTip: 'Know: RIGHT hand for generators (motion → current), LEFT hand for motors (current → motion).',
    memoryTrick: '"Right for Generators, Left for Motors" — motion → current vs current → motion.',
  },
  {
    front: 'What is electromagnetic induction? Who discovered it?',
    back: 'The production of an induced EMF (and current) in a conductor due to a changing magnetic field. Discovered by Michael Faraday.',
    definition: 'Electromagnetic induction: Changing magnetic field → induced EMF/current. (Faraday)',
    explanation: 'When the magnetic field through a coil changes (by moving a magnet or changing current in a nearby coil), an EMF is induced, which can drive a current.',
    keyword: 'Changing flux → induced EMF',
    commonMistake: 'Saying a steady magnetic field induces current — only a CHANGING field does.',
    examTip: 'Know that generators use electromagnetic induction to convert mechanical energy to electrical energy.',
    memoryTrick: '"Change the field, get the current" — only changing flux induces EMF.',
  },
  {
    front: 'What is the difference between AC and DC generators?',
    back: 'AC generator uses slip rings (produces alternating current). DC generator uses a split-ring commutator (produces direct current in one direction).',
    definition: 'AC generator: slip rings → alternating current. DC generator: split-ring commutator → direct current.',
    explanation: 'Slip rings keep the same contact but the current reverses every half rotation (AC). The split-ring commutator reverses contacts every half rotation, keeping current in one direction (DC).',
    keyword: 'Slip rings = AC, Commutator = DC',
    commonMistake: 'Saying AC generators use a commutator — they use slip rings. DC generators use the commutator.',
    examTip: 'Know the AC supply in India: 220 V, 50 Hz (changes direction 100 times per second).',
    memoryTrick: '"AC = Slip (rings), DC = Split (commutator)."',
  },
  {
    front: 'What are the three wires in a domestic circuit? Give their colours and functions.',
    back: 'Live (red, 220V): carries current to appliance. Neutral (black, 0V): returns current. Earth (green): safety wire, carries leakage current to ground.',
    definition: 'Live (red) = supply, Neutral (black) = return, Earth (green) = safety.',
    explanation: 'The live wire carries current at 220V. The neutral wire completes the circuit at 0V. The earth wire connects the metal body of appliances to the ground, preventing electric shock if a fault occurs.',
    keyword: 'Red Live, Black Neutral, Green Earth',
    commonMistake: 'Saying the fuse is on the neutral wire — it is always on the LIVE wire.',
    examTip: 'Know that the earth wire prevents electric shock by providing a low-resistance path to ground.',
    memoryTrick: '"Red Live, Black Neutral, Green Earth" — R-N-G.',
  },
  {
    front: 'What is a short circuit? How does a fuse protect against it?',
    back: 'A short circuit occurs when live and neutral wires touch directly, causing very high current. The fuse (on the live wire) melts and breaks the circuit, protecting appliances.',
    definition: 'Short circuit: Live touches neutral → very high current. Fuse melts → circuit breaks.',
    explanation: 'When live and neutral wires touch, the resistance drops to near zero, causing a huge current surge. The fuse wire heats up and melts, breaking the circuit before damage occurs.',
    keyword: 'Fuse on live wire',
    commonMistake: 'Saying the fuse is on the neutral or earth wire — it is always on the LIVE wire.',
    examTip: 'Know that a fuse is made of an alloy with a low melting point (tin-lead) so it melts quickly.',
    memoryTrick: '"Live touches Neutral = Short circuit. Fuse takes the hit."',
  },
  {
    front: 'What is a solenoid? How does it behave?',
    back: 'A coil of many turns of insulated copper wire in a cylindrical shape. It behaves like a bar magnet when current flows, with a uniform magnetic field inside.',
    definition: 'Solenoid: A coil that produces a uniform magnetic field inside, like a bar magnet.',
    explanation: 'Inside a solenoid, the magnetic field is uniform and parallel to the axis. Outside, the field is similar to a bar magnet (N and S poles). Adding an iron core makes it an electromagnet.',
    keyword: 'Uniform field inside',
    commonMistake: 'Saying the field inside a solenoid is non-uniform — it is uniform inside.',
    examTip: 'Know that a solenoid with a soft iron core becomes an electromagnet (used in cranes, bells).',
    memoryTrick: '"Solenoid = Bar magnet in a coil" — uniform inside, bar magnet outside.',
  },
];

export const magneticEffectsFormulas: FormulaCard[] = [
  {
    formula: 'F = BIL sin θ',
    label: 'Force on a Current-Carrying Conductor',
    symbols: 'F = force (newtons, N), B = magnetic field strength (tesla, T), I = current (amperes, A), L = length of conductor in field (m), θ = angle between conductor and field',
    units: 'F: newton (N), B: tesla (T), I: ampere (A), L: metre (m)',
    usedFor: 'Calculating the force on a current-carrying conductor placed in a magnetic field (motor principle)',
    conditions: 'Force is maximum when conductor is perpendicular to field (θ = 90°, sin θ = 1). Force is zero when conductor is parallel to field (θ = 0°, sin θ = 0).',
    commonMistakes: 'Forgetting the sin θ term — if the wire is parallel to B, force is zero. Also, θ is the angle between the wire and the field, not between the wire and the normal.',
    example: 'A wire of L = 0.5 m carries I = 4 A perpendicular to a field of B = 2 T. F = BIL sin 90° = 2 × 4 × 0.5 × 1 = 4 N. If the wire is parallel to the field (θ = 0°), F = 0.',
    signConvention: 'Direction given by Fleming\'s left-hand rule (F = thumb, B = forefinger, I = middle finger).',
  },
  {
    formula: 'Left-hand rule: F (thumb), B (forefinger), I (middle finger) → Motor',
    label: 'Fleming\'s Left-Hand Rule',
    symbols: 'F = force/motion direction, B = magnetic field direction, I = current direction',
    units: 'Not a formula — a directional rule',
    usedFor: 'Determining the direction of force on a current-carrying conductor in a magnetic field (motor principle)',
    conditions: 'The three fingers must be mutually perpendicular. Used when current causes motion (motor).',
    commonMistakes: 'Using the right hand instead of the left — left hand is for motors (current → force).',
    example: 'A wire carries current upward (middle finger up) in a field pointing north (forefinger forward). The force (thumb) points to the left. The wire moves to the left.',
    signConvention: 'Left hand only. Thumb = Force, Forefinger = Field, Middle = Current.',
  },
  {
    formula: 'Right-hand rule: F (thumb), B (forefinger), I (middle finger) → Generator',
    label: 'Fleming\'s Right-Hand Rule',
    symbols: 'F = motion of conductor (thumb), B = magnetic field (forefinger), I = induced current (middle finger)',
    units: 'Not a formula — a directional rule',
    usedFor: 'Determining the direction of induced current when a conductor moves in a magnetic field (generator principle)',
    conditions: 'The three fingers must be mutually perpendicular. Used when motion causes current (generator).',
    commonMistakes: 'Using the left hand instead of the right — right hand is for generators (motion → current).',
    example: 'A wire is moved downward (thumb down) through a field pointing north (forefinger forward). The induced current (middle finger) points to the right.',
    signConvention: 'Right hand only. Thumb = Motion, Forefinger = Field, Middle = Induced Current.',
  },
  {
    formula: 'AC supply in India: 220 V, 50 Hz',
    label: 'Indian Domestic AC Supply',
    symbols: '220 V = RMS voltage, 50 Hz = frequency (50 cycles per second)',
    units: 'V: volt (V), Hz: hertz (cycles/second)',
    usedFor: 'Describing the standard domestic electricity supply in India',
    conditions: 'AC changes direction 100 times per second (2 × 50 Hz). The voltage alternates sinusoidally.',
    commonMistakes: 'Saying 110 V (that is the US standard). India uses 220 V, 50 Hz.',
    example: 'An electric fan in India operates at 220 V, 50 Hz. The current reverses direction 100 times per second (2 direction changes per cycle × 50 cycles/s).',
    signConvention: 'Not applicable',
  },
];

export const sourcesOfEnergyFlashcards: Flashcard[] = [
  {
    front: 'What are the characteristics of a good fuel?',
    back: 'High calorific value, low ignition temperature, low pollution, easy to transport and store, abundant supply, low cost.',
    definition: 'Good fuel: High calorific value, low ignition temperature, minimal pollution.',
    explanation: 'A good fuel should release a lot of energy per unit mass (high calorific value), ignite easily but not spontaneously (low ignition temperature), and produce minimal pollutants.',
    keyword: 'High CV, low IT, low pollution',
    commonMistake: 'Saying a good fuel should have a high ignition temperature — it should have a LOW ignition temperature (easy to ignite).',
    examTip: 'Be able to compare two fuels based on these characteristics.',
    memoryTrick: '"High energy, Easy start, Clean burn" — high CV, low IT, low pollution.',
  },
  {
    front: 'What is nuclear fission? Write the reaction.',
    back: 'The splitting of a heavy nucleus (U-235) into lighter nuclei, releasing energy and neutrons. ²³⁵U + ¹n → ¹⁴¹Ba + ⁹²Kr + 3¹n + energy.',
    definition: 'Nuclear fission: Splitting a heavy nucleus into lighter ones, releasing energy.',
    explanation: 'When a neutron hits U-235, it splits into Ba-141 and Kr-92, releasing 3 neutrons and enormous energy. The 3 neutrons can hit more U-235, causing a chain reaction.',
    keyword: 'Heavy → Light + neutrons + energy',
    commonMistake: 'Confusing fission (splitting) with fusion (combining).',
    examTip: 'Know that controlled fission is used in nuclear power plants; uncontrolled is used in atom bombs.',
    memoryTrick: '"Fission = Fission/Split" — heavy nucleus splits. "Fusion = Fuse/Join" — light nuclei combine.',
  },
  {
    front: 'What is nuclear fusion? Where does it occur naturally?',
    back: 'The combining of light nuclei (hydrogen) to form a heavier nucleus (helium), releasing enormous energy. Occurs naturally in the sun and stars.',
    definition: 'Nuclear fusion: Light nuclei combine → heavier nucleus + energy.',
    explanation: '4 hydrogen nuclei fuse to form 1 helium nucleus, releasing 26.7 MeV. This powers the sun. Requires extremely high temperature and pressure.',
    keyword: 'Light → Heavy + energy',
    commonMistake: 'Confusing fusion (combining) with fission (splitting).',
    examTip: 'Know that fusion releases more energy than fission but is hard to control (hydrogen bomb).',
    memoryTrick: '"Fusion = Fuse together" — sun uses fusion of H → He.',
  },
  {
    front: 'What is biogas? Give its composition and how it is produced.',
    back: 'Biogas is 60-70% methane (CH₄) and 30-40% CO₂, produced by anaerobic decomposition of organic waste (cow dung) by bacteria in a biogas plant.',
    definition: 'Biogas: 60-70% CH₄ + 30-40% CO₂, from anaerobic decomposition of organic waste.',
    explanation: 'In a biogas plant, anaerobic bacteria break down cow dung and organic waste in the absence of oxygen, producing methane-rich gas. The slurry left is used as manure.',
    keyword: 'CH₄ (60-70%) + CO₂ (30-40%)',
    commonMistake: 'Saying biogas is mainly CO₂ — it is mainly methane (CH₄).',
    examTip: 'Know advantages: clean fuel, renewable, produces manure as by-product, reduces waste.',
    memoryTrick: '"Biogas = Cow dung → Methane" — anaerobic bacteria do the work.',
  },
  {
    front: 'What is the greenhouse effect? Name the greenhouse gases.',
    back: 'The trapping of heat by greenhouse gases (CO₂, CH₄, water vapour, N₂O) in the atmosphere. It keeps Earth warm but excess causes global warming.',
    definition: 'Greenhouse effect: Gases trap heat in the atmosphere, warming the Earth.',
    explanation: 'Greenhouse gases allow sunlight to pass through but absorb the infrared radiation reflected by Earth\'s surface, trapping heat. Burning fossil fuels increases CO₂, enhancing this effect.',
    keyword: 'CO₂, CH₄, H₂O vapour, N₂O',
    commonMistake: 'Saying the greenhouse effect is entirely bad — it is natural and necessary; the problem is the ENHANCED effect from excess CO₂.',
    examTip: 'Know that CO₂ is the main greenhouse gas from fossil fuel burning.',
    memoryTrick: '"Greenhouse = Blanket of gases" — traps heat like a blanket.',
  },
  {
    front: 'Differentiate between renewable and non-renewable energy sources with examples.',
    back: 'Renewable: can be replenished naturally (solar, wind, hydro, biogas). Non-renewable: cannot be replenished, finite (coal, petroleum, natural gas, nuclear).',
    definition: 'Renewable: replenishable (solar, wind). Non-renewable: finite (coal, petroleum).',
    explanation: 'Renewable sources are continuously available or can be regenerated. Non-renewable sources took millions of years to form and will run out.',
    keyword: 'Renewable = infinite, Non-renewable = finite',
    commonMistake: 'Classifying nuclear energy as renewable — it is non-renewable (uranium is finite).',
    examTip: 'Know at least 3 examples of each type.',
    memoryTrick: '"Renewable = Repeats (sun, wind). Non-renewable = Runs out (coal, oil)."',
  },
  {
    front: 'What are solar cells? What are their advantages and limitations?',
    back: 'Solar cells (photovoltaic cells) convert sunlight directly into electricity using semiconductor materials (silicon). Advantages: clean, renewable. Limitations: expensive, weather-dependent, require large area.',
    definition: 'Solar cell: Converts sunlight to electricity using silicon semiconductors.',
    explanation: 'When sunlight hits a silicon solar cell, it excites electrons, creating a flow of current. No fuel, no pollution, but high cost and needs sunlight.',
    keyword: 'Photovoltaic effect',
    commonMistake: 'Saying solar cells work at night — they need sunlight and do not work in the dark.',
    examTip: 'Know uses: calculators, street lights, satellites, water heaters (solar panels).',
    memoryTrick: '"Sun = Electricity" — solar cells convert light directly to current.',
  },
  {
    front: 'Why is biogas considered better than wood as a fuel?',
    back: 'Biogas is clean (no smoke), renewable, high calorific value, produces manure as by-product. Wood produces smoke, causes deforestation, and has lower calorific value.',
    definition: 'Biogas > Wood: cleaner, renewable, higher CV, produces manure.',
    explanation: 'Burning wood produces CO₂, CO, and particulate matter (smoke), causing air pollution and health issues. Biogas burns cleanly with a blue flame and the slurry is excellent manure.',
    keyword: 'Clean + renewable + manure',
    commonMistake: 'Saying wood is a renewable fuel — while trees can regrow, burning wood causes deforestation and pollution.',
    examTip: 'Know that biogas plants solve two problems: waste disposal and fuel supply.',
    memoryTrick: '"Biogas = Clean + Manure, Wood = Smoke + Deforestation."',
  },
];

export const sourcesOfEnergyFormulas: FormulaCard[] = [
  {
    formula: '²³⁵U + ¹n → ¹⁴¹Ba + ⁹²Kr + 3¹n + energy',
    label: 'Nuclear Fission of Uranium-235',
    symbols: '²³⁵U = Uranium-235, ¹n = neutron, ¹⁴¹Ba = Barium-141, ⁹²Kr = Krypton-92, 3¹n = 3 neutrons',
    units: 'Energy in MeV (mega electron-volts) or joules (J)',
    usedFor: 'Describing the nuclear fission reaction used in nuclear power plants and atom bombs',
    conditions: 'Requires a neutron to initiate. The 3 released neutrons can cause a chain reaction. Controlled in reactors, uncontrolled in bombs.',
    commonMistakes: 'Confusing fission (splitting) with fusion (combining). Also, not balancing the neutrons — 3 neutrons are released.',
    example: 'When 1 neutron hits 1 U-235 nucleus, it splits into Ba-141, Kr-92, and 3 neutrons, releasing ~200 MeV of energy. The 3 neutrons can hit 3 more U-235 nuclei, causing a chain reaction.',
    signConvention: 'Not applicable',
  },
  {
    formula: '4 ¹H → ⁴He + 2e⁺ + 26.7 MeV',
    label: 'Nuclear Fusion in the Sun',
    symbols: '¹H = Hydrogen nucleus (proton), ⁴He = Helium nucleus, e⁺ = positron, 26.7 MeV = energy released',
    units: 'Energy in MeV (mega electron-volts)',
    usedFor: 'Describing the fusion reaction that powers the sun and stars',
    conditions: 'Requires extremely high temperature (~15 million °C) and pressure. This is why fusion is hard to achieve on Earth.',
    commonMistakes: 'Confusing fusion (combining light nuclei) with fission (splitting heavy nuclei).',
    example: 'In the sun\'s core, 4 hydrogen nuclei fuse to form 1 helium nucleus, releasing 26.7 MeV of energy. This energy powers all life on Earth through sunlight.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Biogas = 60-70% CH₄ + 30-40% CO₂',
    label: 'Biogas Composition',
    symbols: 'CH₄ = Methane (combustible component), CO₂ = Carbon dioxide (non-combustible)',
    units: 'Percentage by volume',
    usedFor: 'Describing the composition of biogas produced by anaerobic digestion',
    conditions: 'Produced by anaerobic bacteria in the absence of oxygen. Feedstock: cow dung, organic waste, crop residue.',
    commonMistakes: 'Saying biogas is mainly CO₂ — it is mainly CH₄ (methane). CO₂ is the secondary component.',
    example: 'A biogas plant processes 10 kg of cow dung. The resulting biogas contains ~65% methane and ~35% CO₂ by volume. The methane provides the energy when burned.',
    signConvention: 'Not applicable',
  },
  {
    formula: 'Energy = Power × Time (E = P × t)',
    label: 'Energy Consumption',
    symbols: 'E = energy (kWh or J), P = power (kW or W), t = time (hours or seconds)',
    units: 'E: kilowatt-hour (kWh) or joule (J). P: kilowatt (kW) or watt (W). t: hour (h) or second (s).',
    usedFor: 'Calculating energy consumed by an appliance over a period of time (electricity bill)',
    conditions: 'If P is in kW and t in hours, E is in kWh. If P is in W and t in seconds, E is in joules. 1 kWh = 3.6 × 10⁶ J.',
    commonMistakes: 'Mixing units — if P is in watts, convert to kW (divide by 1000) before using hours. Or keep P in W and t in seconds for joules.',
    example: 'A 2 kW heater runs for 3 hours. E = P × t = 2 × 3 = 6 kWh = 6 units. At ₹8/unit, cost = 6 × 8 = ₹48. In joules: E = 2000 W × 10800 s = 21,600,000 J = 21.6 MJ.',
    signConvention: 'Not applicable',
  },
];
