import type { NoteSection } from '../revision-content';

export const lifeProcessesNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Life processes are the essential functions that maintain life: nutrition, respiration, transportation, and excretion.',
      'Nutrition can be autotrophic (plants make food via photosynthesis) or heterotrophic (animals, fungi depend on others).',
      'Respiration is the breakdown of food to release energy; aerobic respiration uses oxygen and produces 38 ATP, anaerobic produces 2 ATP.',
      'Transportation in humans is via the circulatory system (heart, blood, vessels); in plants via xylem (water/minerals) and phloem (food).',
      'Excretion in humans is via the kidneys (nephrons filter blood to form urine); plants excrete through stomata, lenticels, and leaf shedding.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Life processes: The essential functions performed by living organisms to maintain their life.',
      'Nutrition: The process by which organisms obtain food (energy) for growth and repair.',
      'Photosynthesis: The process by which green plants make food from CO₂ and water using sunlight and chlorophyll.',
      'Respiration: The biochemical breakdown of food to release energy in the form of ATP.',
      'Aerobic respiration: Respiration using oxygen, occurring in mitochondria, producing CO₂, H₂O, and 38 ATP.',
      'Anaerobic respiration: Respiration without oxygen, occurring in cytoplasm, producing lactic acid (muscles) or ethanol + CO₂ (yeast) and 2 ATP.',
      'Transpiration: The loss of water vapour from the surface of leaves through stomata.',
      'Translocation: The transport of food (sucrose) from leaves to other parts of the plant via phloem using ATP energy.',
      'Nephron: The structural and functional unit of the kidney that filters blood and produces urine.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Autotrophic and heterotrophic nutrition',
      'Chlorophyll and chloroplast',
      'Stomata and guard cells',
      'Aerobic and anaerobic respiration',
      'ATP (Adenosine Triphosphate)',
      'Double circulation',
      'Xylem and phloem',
      'Nephron and glomerulus',
      'Transpiration and translocation',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      '6CO₂ + 6H₂O →(sunlight, chlorophyll)→ C₆H₁₂O₆ + 6O₂ (photosynthesis)',
      'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP (aerobic respiration)',
      'C₆H₁₂O₆ → 2C₃H₆O₃ + 2 ATP (anaerobic, muscles → lactic acid)',
      'C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ + 2 ATP (anaerobic, yeast → ethanol)',
      'Cardiac output = Heart Rate × Stroke Volume',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Photosynthesis: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (endothermic, requires sunlight)',
      'Aerobic respiration: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP (in mitochondria)',
      'Anaerobic in muscles: C₆H₁₂O₆ → lactic acid + 2 ATP (causes cramps)',
      'Anaerobic in yeast: C₆H₁₂O₆ → ethanol + CO₂ + 2 ATP (fermentation, used in brewing and baking)',
      'Dental plaque: Bacteria digest sugar → produce acid → tooth enamel decays',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Human digestive system showing mouth, oesophagus, stomach, small intestine, large intestine, liver, pancreas',
      'Cross-section of a leaf showing stomata, guard cells, chloroplasts, and vascular bundles',
      'Human heart showing four chambers, valves, and double circulation (pulmonary and systemic)',
      'Nephron diagram showing glomerulus, Bowman\'s capsule, tubules, and collecting duct',
      'Human respiratory system showing trachea, bronchi, bronchioles, and alveoli',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'When iodine solution is added to a leaf tested for starch, it turns blue-black, confirming photosynthesis has occurred.',
      'In humans, the right side of the heart carries deoxygenated blood and the left side carries oxygenated blood.',
      'Arteries have thick, elastic walls; veins have thin walls with valves to prevent backflow.',
      'Capillaries are the site of exchange of materials between blood and cells — they have walls only one cell thick.',
      'During heavy exercise, muscles respire anaerobically, producing lactic acid which causes cramps.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Salivary amylase breaks down starch into maltose in the mouth.',
      'Pepsin in the stomach digests proteins in the presence of HCl.',
      'Bile from the liver emulsifies fats (breaks large globules into smaller ones for enzyme action).',
      'Villi in the small intestine increase surface area for absorption of digested food.',
      'In plants, xylem transports water upward (no energy required); phloem transports food bidirectionally (uses ATP).',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing aerobic and anaerobic respiration — aerobic produces 38 ATP in mitochondria; anaerobic produces only 2 ATP in cytoplasm.',
      'Writing the photosynthesis equation without sunlight and chlorophyll above the arrow.',
      'Forgetting that the right side of the heart has deoxygenated blood and the left side has oxygenated blood.',
      'Confusing transpiration (water loss) with translocation (food transport in phloem).',
      'Not knowing that veins have valves but arteries do not.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Balanced equation for photosynthesis and aerobic respiration',
      'Difference between aerobic and anaerobic respiration (ATP, products, site)',
      'Human heart structure and double circulation',
      'Nephron structure and function',
      'Xylem vs phloem (direction, energy, substance transported)',
      'Role of bile in digestion (emulsification of fats, not enzyme)',
      'Why muscles cramp during heavy exercise (lactic acid from anaerobic respiration)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'Activity 6.1: Test a leaf for starch using iodine solution after keeping it in sunlight.',
      'The energy currency of the cell is ATP, released during respiration and used for all cellular processes.',
      'The transport of soluble products of photosynthesis is called translocation and it occurs in the phloem.',
      'Arteries divide into capillaries which are one-cell thick, enabling exchange of materials between blood and cells.',
      'The functional unit of the kidney is the nephron, which performs filtration, reabsorption, and secretion.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Digestive tract order: "Mouth → Stomach → Small → Large" — "MSSL."',
      'Nephron steps: "FRSU" — Filtration, Reabsorption, Secretion, Urine.',
      'Arteries vs veins: "Arteries Away (from heart), Veins Towards (heart)."',
      'Respiration: "Aerobic = 38 (lots), Anaerobic = 2 (little)."',
      'Plant transport: "Xylem Up (water), Phloem Both-ways (food)."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Always write the full balanced equation for photosynthesis and respiration with conditions above the arrow.',
      'For the heart: right = deoxygenated, left = oxygenated; arteries carry blood away, veins carry blood to the heart.',
      'Know the difference between aerobic and anaerobic respiration in a table (site, ATP, products, organisms).',
      'Be able to label the nephron and explain filtration, reabsorption, and secretion.',
      'Remember: bile emulsifies fats (not an enzyme); salivary amylase works in the mouth; pepsin works in the stomach with HCl.',
    ],
  },
];

export const controlCoordinationNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Control and coordination in animals is achieved by the nervous system (fast, electrical) and endocrine system (slow, chemical hormones).',
      'The nervous system consists of the brain, spinal cord, and nerves; neurons are the structural and functional units.',
      'A reflex arc is an involuntary, rapid response mediated by the spinal cord without involving the brain.',
      'The brain has three main parts: cerebrum (thinking, memory), cerebellum (balance, posture), and medulla (involuntary functions).',
      'Hormones are chemical messengers secreted by endocrine glands directly into the blood; they produce slow but long-lasting effects.',
      'In plants, coordination is controlled by phytohormones: auxin, gibberellin, cytokinin, abscisic acid, and ethylene.',
      'Plant movements include tropisms (growth movements towards/away from stimuli) and nastic movements (non-directional).',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Stimulus: A change in the environment that triggers a response in an organism.',
      'Neuron: The structural and functional unit of the nervous system, consisting of dendrites, cell body, and axon.',
      'Synapse: The junction between two neurons where electrical signals are converted to chemical signals (neurotransmitters).',
      'Reflex action: An involuntary, rapid response to a stimulus that does not involve the brain.',
      'Reflex arc: The pathway taken by nerve impulses during a reflex action (receptor → spinal cord → effector).',
      'Hormone: A chemical messenger secreted by endocrine glands into the blood, affecting target organs.',
      'Tropism: A growth movement of a plant part in response to a directional stimulus (e.g., phototropism, geotropism).',
      'Nastic movement: A non-directional movement of a plant part in response to a stimulus (e.g., touch in Mimosa).',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Neuron, dendrite, axon, synapse',
      'Reflex action and reflex arc',
      'Cerebrum, cerebellum, medulla, pons',
      'Endocrine glands and hormones',
      'Phytohormones (auxin, gibberellin, cytokinin, abscisic acid, ethylene)',
      'Phototropism, geotropism, hydrotropism, chemotropism',
      'Fight-or-flight response (adrenaline)',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Nervous pathway: Stimulus → Receptor → Sensory neuron → CNS → Motor neuron → Effector',
      'Reflex arc: Receptor → Sensory neuron → Spinal cord → Motor neuron → Effector (no brain)',
      'Auxin → Cell elongation → Phototropism (bending towards light)',
      'Insulin → Glucose uptake by cells → Blood sugar decreases',
      'Thyroxine → Metabolic rate increases',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Nerve impulse: Electrical signal travels along the axon; at the synapse, it triggers release of neurotransmitters.',
      'Insulin action: Insulin binds to cell receptors → cells take up glucose → blood glucose decreases.',
      'Adrenaline: Released in stress → increases heart rate, breathing rate, blood flow to muscles (fight-or-flight).',
      'Auxin action: Auxin accumulates on the shaded side of a stem → cells elongate more → stem bends towards light.',
      'Photosensitive auxin: When light hits one side of a plant shoot, auxin migrates to the shaded side, causing faster growth there.',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Structure of a neuron showing dendrites, cell body, axon, myelin sheath, and nerve endings',
      'Reflex arc diagram showing the pathway from receptor to effector via the spinal cord',
      'Human brain diagram showing cerebrum, cerebellum, medulla, and pons',
      'Human endocrine system showing all major glands (pituitary, thyroid, pancreas, adrenal, gonads)',
      'Plant tropism diagram showing phototropism (shoot bending towards light) and geotropism (root growing downwards)',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'When you touch a hot object, the hand is withdrawn immediately (reflex action) before the brain processes the pain.',
      'In a growing plant shoot, the side away from light grows faster due to auxin accumulation, causing the shoot to bend towards light.',
      'Roots grow downwards (positive geotropism) and shoots grow upwards (negative geotropism).',
      'The gap between two neurons (synapse) is crossed by chemical messengers called neurotransmitters, not electrical impulses.',
      'Adrenaline secretion increases during fear or excitement, preparing the body for rapid action.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Touching a hot plate → reflex action withdraws the hand before the brain registers pain.',
      'Iodine deficiency causes goitre (enlarged thyroid) due to low thyroxine production.',
      'Insulin deficiency causes diabetes (high blood sugar); treated with insulin injections.',
      'Mimosa pudica (touch-me-not) folds its leaves when touched (nastic movement).',
      'Auxin promotes cell elongation in stems; gibberellin promotes stem growth and seed germination.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing reflex action with voluntary action — reflexes bypass the brain and are involuntary.',
      'Mixing up cerebrum and cerebellum — cerebrum = thinking/memory; cerebellum = balance/posture.',
      'Forgetting that synapse is a gap, not a physical connection — signals cross via neurotransmitters.',
      'Confusing tropism (directional, growth) with nastic movement (non-directional, not growth-related).',
      'Not knowing that adrenaline is the fight-or-flight hormone, not thyroxine.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Reflex action and reflex arc pathway',
      'Structure and function of a neuron',
      'Parts of the brain and their functions',
      'Plant hormones and their functions (auxin, gibberellin, cytokinin, abscisic acid, ethylene)',
      'Difference between nervous and hormonal control (speed, duration, mode of transport)',
      'Cause of diabetes and goitre (insulin and thyroxine deficiency)',
      'Phototropism mechanism (auxin migration to shaded side)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'The thinking part of the brain is the cerebrum; it controls memory, reasoning, speech, and voluntary actions.',
      'The medulla controls involuntary functions such as breathing, heart rate, and blood pressure.',
      'The gap between two neurons is called a synapse; nerve impulses cross it via chemical messengers (neurotransmitters).',
      'Plant hormones help in coordinated growth and development; auxin promotes cell elongation.',
      'Iodine is essential for the synthesis of thyroxine; its deficiency causes goitre.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Brain parts: "CCM" — Cerebrum (Cognition), Cerebellum (Coordination/balance), Medulla (involuntary Maintenance).',
      'Plant hormones: "All Good Children Are Eating" — Auxin, Gibberellin, Cytokinin, Abscisic acid, Ethylene.',
      'Reflex arc: "Receptor → Spinal cord → Effector" — brain is bypassed.',
      'Nervous vs hormonal: "Nervous = Fast and Short, Hormonal = Slow and Long."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Be able to draw and label a neuron and a reflex arc.',
      'Know the three main parts of the brain and their specific functions (cerebrum, cerebellum, medulla).',
      'Memorise the five plant hormones and their main functions.',
      'Remember the difference between nervous and hormonal control in a table (speed, pathway, duration, target).',
      'Know the causes and treatments of diabetes (insulin) and goitre (iodine/thyroxine).',
    ],
  },
];

export const reproductionNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Reproduction is the process by which living organisms produce new individuals of the same species.',
      'Asexual reproduction involves a single parent and produces genetically identical offspring (clones).',
      'Sexual reproduction involves two parents, produces genetic variation, and involves the fusion of gametes.',
      'In flowering plants, the flower is the reproductive organ; pollination (transfer of pollen) is followed by fertilisation.',
      'In humans, the male reproductive system produces sperm and the female system produces eggs; fertilisation occurs in the fallopian tube.',
      'Puberty is the period when sexual maturity is reached; it is controlled by hormones.',
      'Reproductive health includes contraception methods to prevent unwanted pregnancy and STIs.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Reproduction: The biological process by which organisms produce offspring of the same kind.',
      'Asexual reproduction: Reproduction involving a single parent; offspring are genetically identical (clones).',
      'Sexual reproduction: Reproduction involving two parents and the fusion of male and female gametes.',
      'Pollination: The transfer of pollen grains from the anther to the stigma of a flower.',
      'Fertilisation: The fusion of male and female gametes to form a zygote.',
      'Puberty: The period during which adolescents reach sexual maturity and become capable of reproduction.',
      'Menstrual cycle: The monthly cycle of changes in the female reproductive system (approximately 28 days).',
      'Contraception: Methods used to prevent pregnancy (barrier, chemical, IUCD, surgical).',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Binary fission, budding, fragmentation, spore formation',
      'Vegetative propagation',
      'Stamen (anther, filament) and pistil (stigma, style, ovary)',
      'Self-pollination and cross-pollination',
      'Zygote, embryo, seed, fruit',
      'Testes, ovaries, fallopian tube, uterus',
      'Menstrual cycle and ovulation',
      'Contraceptive methods',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Pollen + Egg → Zygote → Embryo (plant fertilisation)',
      'Ovule → Seed | Ovary → Fruit (post-fertilisation changes)',
      'Sperm + Ovum → Zygote (in fallopian tube, human fertilisation)',
      'Ovulation: Day 14 of a 28-day menstrual cycle',
      'Binary fission: Parent → Two daughter cells (Amoeba, bacteria)',
      'Budding: Parent → Outgrowth → New individual (Hydra, yeast)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Binary fission in Amoeba: Parent cell elongates → nucleus divides → cytoplasm splits → two daughter cells.',
      'Budding in Hydra: A bud forms on the parent body → develops tentacles → detaches → becomes a new individual.',
      'Pollination in plants: Pollen lands on stigma → pollen tube grows down the style → male gamete reaches ovary → fertilisation.',
      'Double fertilisation in flowering plants: One male gamete + egg → zygote; other male gamete + two polar nuclei → endosperm.',
      'Menstrual cycle: If fertilisation does not occur, the thickened uterine lining breaks down and is discharged (menstruation).',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Longitudinal section of a flower showing stamen (anther, filament) and pistil (stigma, style, ovary, ovules)',
      'Diagram of binary fission in Amoeba and budding in Hydra/Yeast',
      'Human male reproductive system showing testes, vas deferens, seminal vesicle, urethra, penis',
      'Human female reproductive system showing ovaries, fallopian tubes, uterus, vagina',
      'Diagram of pollen tube growth from stigma through style to ovary',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'In binary fission in Amoeba, the parent cell divides into two equal daughter cells after nuclear division.',
      'In budding in Hydra, a small outgrowth (bud) develops on the parent body before detaching.',
      'After fertilisation in plants, the ovule develops into a seed and the ovary develops into a fruit.',
      'Testes are located outside the body in the scrotum because sperm production requires a temperature about 2°C below body temperature.',
      'If the released egg is not fertilised, the thickened uterine lining is shed during menstruation (days 1–5 of the cycle).',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Binary fission: Amoeba, Leishmania, bacteria.',
      'Budding: Hydra, yeast.',
      'Fragmentation: Spirogyra (a multicellular organism breaks into fragments that grow independently).',
      'Vegetative propagation: Potato (stem tuber), Bryophyllum (leaf buds), onion (bulb), jasmine (layering).',
      'STIs: HIV/AIDS, syphilis, gonorrhoea; prevented by using condoms.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing self-pollination (same flower) with cross-pollination (different flowers).',
      'Forgetting that the ovule becomes the seed and the ovary becomes the fruit.',
      'Writing that fertilisation occurs in the uterus — it occurs in the fallopian tube (oviduct).',
      'Not knowing that testes are outside the body for temperature regulation (2°C below body temperature).',
      'Confusing binary fission (parent splits into two) with budding (new individual grows as an outgrowth).',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Methods of asexual reproduction (binary fission, budding, fragmentation, spore formation, vegetative propagation)',
      'Parts of a flower and their functions (stamen, pistil, ovule, ovary)',
      'Post-fertilisation changes in plants (ovule → seed, ovary → fruit)',
      'Human male and female reproductive systems (organs and functions)',
      'Menstrual cycle and ovulation timing (day 14)',
      'Contraceptive methods and their mechanisms',
      'Why testes are located outside the body (temperature for sperm production)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'The flower is the reproductive organ of a plant; the stamen is the male part and the pistil is the female part.',
      'After fertilisation, the zygote divides several times to form an embryo within the seed.',
      'The transfer of pollen from one flower to another is called pollination; it can be self or cross-pollination.',
      'The testes produce sperm and the hormone testosterone; the ovaries produce eggs and the hormones oestrogen and progesterone.',
      'The use of condoms prevents both pregnancy and sexually transmitted infections.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Flower parts: "Stamen = Male (Anther + Filament), Pistil = Female (Stigma + Style + Ovary)."',
      'Asexual methods: "BBF SV" — Budding, Binary fission, Fragmentation, Spore, Vegetative propagation.',
      'Post-fertilisation: "Ovule → Seed, Ovary → Fruit" — "OSOF."',
      'Fertilisation site: "Fallopian Tube" — not the uterus.',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Be able to label the parts of a flower and the human male and female reproductive systems.',
      'Know all five methods of asexual reproduction with examples.',
      'Remember: ovule → seed, ovary → fruit, fertilisation in fallopian tube, ovulation on day 14.',
      'Know the four types of contraceptive methods (barrier, chemical, IUCD, surgical) with examples.',
      'Remember that condoms are the only contraceptive that also prevents STIs.',
    ],
  },
];

export const heredityEvolutionNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Heredity is the transmission of traits from parents to offspring through genes located on chromosomes.',
      'Gregor Mendel, through his experiments with pea plants, established the laws of inheritance.',
      'Mendel\'s three laws are: dominance, segregation, and independent assortment.',
      'Sex determination in humans is chromosomal: XX (female) and XY (male); the father determines the sex of the child.',
      'Evolution is the gradual change in heritable traits over successive generations; Darwin proposed natural selection as the mechanism.',
      'Speciation occurs when populations of a species become isolated and diverge genetically over time.',
      'Evidence for evolution comes from homologous organs (common ancestry), analogous organs (convergent evolution), and fossils.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Heredity: The transmission of traits from parents to offspring via genes.',
      'Gene: A segment of DNA that codes for a specific trait; located on chromosomes.',
      'Allele: An alternative form of a gene (e.g., T for tall, t for short).',
      'Genotype: The genetic makeup of an organism (e.g., TT, Tt, tt).',
      'Phenotype: The observable characteristics of an organism (e.g., tall or short).',
      'Homozygous: Having two identical alleles (TT or tt).',
      'Heterozygous: Having two different alleles (Tt).',
      'Dominant trait: The allele that is expressed even in the presence of a recessive allele.',
      'Recessive trait: The allele that is expressed only in the homozygous condition.',
      'Evolution: The gradual change in inherited traits over successive generations.',
      'Speciation: The formation of new species from existing ones due to isolation and genetic divergence.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Genes, alleles, chromosomes',
      'Dominant and recessive traits',
      'Monohybrid and dihybrid cross',
      'Genotype and phenotype ratio',
      'Sex determination (XX, XY)',
      'Natural selection',
      'Homologous and analogous organs',
      'Fossils and carbon dating',
      'Speciation',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Monohybrid F₂ ratio: 3:1 (phenotypic), 1:2:1 (genotypic)',
      'Dihybrid F₂ ratio: 9:3:3:1 (phenotypic)',
      'Female: XX | Male: XY',
      'Homologous organs → Divergent evolution (common ancestry)',
      'Analogous organs → Convergent evolution (same function, different origin)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Monohybrid cross: TT × tt → F₁: all Tt (tall) → F₂ (Tt × Tt): 3 tall : 1 short (1 TT : 2 Tt : 1 tt).',
      'Dihybrid cross: RRYY × rryy → F₁: all RrYy → F₂: 9 round-yellow : 3 round-green : 3 wrinkled-yellow : 1 wrinkled-green.',
      'Sex determination: XX (mother) × XY (father) → 50% XX (daughter) : 50% XY (son). Father determines sex.',
      'Natural selection: Variation → selection by environment → survival of fittest → reproduction → evolution.',
      'Fossil formation: Organism dies → buried in sediment → soft parts decay → hard parts mineralise over millions of years.',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Punnett square for a monohybrid cross (Tt × Tt) showing 3:1 ratio',
      'Punnett square for a dihybrid cross (RrYy × RrYy) showing 9:3:3:1 ratio',
      'Sex determination diagram showing XX (female) and XY (male) chromosomes',
      'Diagram of homologous organs (forelimbs of human, frog, bird, bat)',
      'Diagram of analogous organs (wings of butterfly, bird, bat)',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'In a monohybrid cross (Tt × Tt), the F₂ generation shows 3 tall : 1 short phenotypic ratio.',
      'In a dihybrid cross (RrYy × RrYy), the F₂ generation shows 9:3:3:1 phenotypic ratio.',
      'All F₁ offspring of a cross between homozygous dominant and homozygous recessive show the dominant phenotype.',
      'Forelimbs of humans, frogs, birds, and bats have the same basic bone structure but different functions — homologous organs.',
      'Wings of butterflies and birds have different structures but the same function (flight) — analogous organs.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Mendel used pea plants (Pisum sativum) with contrasting traits: tall/short, round/wrinkled seeds, yellow/green seeds.',
      'Homologous organs: Forelimbs of humans, frogs, lizards, birds — same structure, different functions.',
      'Analogous organs: Wings of butterflies, birds, bats — different structures, same function.',
      'Fossils: Archaeopteryx (link between reptiles and birds) shows feathered wings with teeth.',
      'Human evolution: Homo sapiens originated in Africa; evolved from Homo erectus.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing genotype ratio (1:2:1) with phenotype ratio (3:1) in a monohybrid cross.',
      'Forgetting that the father determines the sex of the child (X or Y chromosome from father).',
      'Mixing up homologous (same structure, different function) with analogous (different structure, same function).',
      'Writing that acquired traits are inherited — only changes in germ cell DNA are inherited, not somatic changes.',
      'Confusing convergent evolution (analogous organs) with divergent evolution (homologous organs).',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Mendel\'s monohybrid and dihybrid ratios (3:1 and 9:3:3:1)',
      'Sex determination in humans (XX, XY; father determines sex)',
      'Difference between homologous and analogous organs',
      'Acquired vs inherited traits (only germ cell changes are inherited)',
      'Speciation and its causes (geographical isolation, mutation, natural selection)',
      'Fossils as evidence of evolution (dating methods: carbon-14, depth of rock layer)',
      'Mendel\'s choice of pea plants and why (short life cycle, easy to grow, contrasting traits)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'Mendel conducted his experiments on garden pea plants (Pisum sativum) with several contrasting traits.',
      'The F₁ generation of a monohybrid cross shows all dominant traits; the F₂ shows a 3:1 ratio.',
      'In humans, females have XX sex chromosomes and males have XY; the father determines the sex of the child.',
      'Acquired changes are not inherited because they do not involve changes in the DNA of germ cells.',
      'Homologous organs indicate common ancestry (divergent evolution); analogous organs show convergent evolution.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Mendel ratios: "3:1 for one trait, 9:3:3:1 for two traits."',
      'Sex: "XX = girl, XY = boy — dad decides."',
      'Homologous vs analogous: "Same structure = Homologous (common ancestor); Same function = Analogous (adaptation)."',
      'Evolution evidence: "HAAA" — Homologous, Analogous, Anatomical, Ancestral fossils.',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Be able to draw Punnett squares for monohybrid and dihybrid crosses and state the ratios.',
      'Remember: sex is determined by the father\'s sperm (X or Y); the mother always provides X.',
      'Know the difference between homologous and analogous organs with examples.',
      'Understand that only inherited traits (germ cell DNA changes) contribute to evolution, not acquired traits.',
      'Know the causes of speciation: geographical isolation, genetic variation (mutation), natural selection, and reproductive isolation.',
    ],
  },
];
