import type { NoteSection } from '../revision-content';

export const chemicalReactionsNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'A chemical reaction is a process where reactants undergo bond breaking and bond forming to produce new substances (products) with different properties.',
      'Chemical reactions are represented by balanced chemical equations obeying the Law of Conservation of Mass.',
      'Main types: combination, decomposition, displacement, double displacement, and oxidation-reduction (redox).',
      'Oxidation is gain of oxygen or loss of electrons; reduction is loss of oxygen or gain of electrons. Both occur together in redox reactions.',
      'Corrosion (rusting of iron) and rancidity (spoilage of fats) are common effects of oxidation in daily life.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Chemical reaction: A process where reactants transform into products with new chemical properties.',
      'Balanced equation: An equation having equal numbers of atoms of each element on both sides.',
      'Oxidation: Gain of oxygen or loss of electrons by a substance.',
      'Reduction: Loss of oxygen or gain of electrons by a substance.',
      'Oxidising agent: The substance that gives oxygen (or accepts electrons) and gets reduced itself.',
      'Reducing agent: The substance that takes oxygen (or donates electrons) and gets oxidised itself.',
      'Corrosion: The slow degradation of metals by the action of air and moisture.',
      'Rancidity: The oxidation of fats and oils producing unpleasant smell and taste.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Reactants and products',
      'Law of Conservation of Mass',
      'Exothermic and endothermic reactions',
      'Combination and decomposition',
      'Displacement and double displacement',
      'Oxidation and reduction',
      'Redox reaction',
      'Corrosion and rancidity',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      '4Fe + 3O₂ + xH₂O → 2Fe₂O₃·xH₂O (rusting of iron)',
      '2AgCl → 2Ag + Cl₂ (in sunlight, photodecomposition)',
      '2AgBr → 2Ag + Br₂ (used in black-and-white photography)',
      'Fe₂O₃ + 2Al → 2Fe + Al₂O₃ (thermite reaction)',
      'CaCO₃ → CaO + CO₂ (thermal decomposition of limestone)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Zn + H₂SO₄ → ZnSO₄ + H₂↑ (displacement, exothermic)',
      'BaCl₂ + Na₂SO₄ → BaSO₄↓ + 2NaCl (double displacement, white precipitate)',
      'CaO + H₂O → Ca(OH)₂ (exothermic, used in whitewashing)',
      '2FeSO₄ → Fe₂O₃ + SO₂ + SO₃ (thermal decomposition of ferrous sulphate)',
      'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + energy (respiration, exothermic)',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Setup for reaction of zinc granules with dilute HCl in a test tube with gas delivery tube',
      'Silver chloride turning grey in sunlight (photodecomposition experiment)',
      'Thermite reaction apparatus used for welding railway tracks',
      'Rusting of iron nail experiment with oil-coated and boiled-water control tubes',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Gas evolved when zinc reacts with acid extinguishes a burning matchstick with a "pop" sound (hydrogen test).',
      'When CO₂ is passed through limewater, it turns milky due to insoluble CaCO₃ formation.',
      'Silver chloride turns from white to grey in sunlight due to silver metal formation.',
      'Ferrous sulphate crystals change from green to white then brown on heating (Fe₂O₃ forms).',
      'A white precipitate of BaSO₄ forms immediately when barium chloride is added to sodium sulphate.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Respiration is an exothermic reaction because glucose breaks down releasing energy.',
      'Digestion is a decomposition reaction where large food molecules break into smaller ones.',
      'Rusting of iron is a redox reaction where iron is oxidised and oxygen is reduced.',
      'Burning of natural gas (CH₄ + 2O₂ → CO₂ + 2H₂O) is an exothermic combustion reaction.',
      'Electrolysis of water (2H₂O → 2H₂ + O₂) is an endothermic decomposition reaction.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Forgetting to balance the equation — always count atoms of each element on both sides.',
      'Confusing oxidation with reduction — remember "OIL RIG" (Oxidation Is Loss, Reduction Is Gain of electrons).',
      'Writing wrong state symbols — (s) for solid, (l) for liquid, (g) for gas, (aq) for aqueous.',
      'Not adding (↑) for evolved gas or (↓) for precipitate.',
      'Mixing up oxidising and reducing agents — the oxidising agent gets reduced, the reducing agent gets oxidised.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Balancing chemical equations (asked almost every year)',
      'Identification of oxidation and reduction in a given reaction',
      'Why respiration is exothermic',
      'Why silver chloride turns grey in sunlight',
      'Thermite reaction and its application in welding',
      'Methods to prevent rancidity (antioxidants, airtight containers, nitrogen flushing)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'Activity 1.1: Observe the colour of FeSO₄ crystals before and after heating — green to reddish-brown.',
      'Activity 1.2: Reaction of BaCl₂ with Na₂SO₄ produces a white precipitate of BaSO₄.',
      'Activity 1.3: Zinc granules react with dilute HCl to produce H₂ gas (pop test).',
      'Activity 1.4: Silver chloride exposed to sunlight turns grey (photodecomposition).',
      'Why do we apply paint on iron articles? To prevent contact with air and moisture, preventing rusting.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      '"OIL RIG" — Oxidation Is Loss, Reduction Is Gain (of electrons).',
      '"LEO says GER" — Loss of Electrons = Oxidation, Gain of Electrons = Reduction.',
      'Types of reactions: "CDDDR" — Combination, Decomposition, Displacement, Double displacement, Redox.',
      'Rust formula: "4-3-x" — 4Fe, 3O₂, xH₂O.',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Always balance equations by starting with the most complex compound.',
      'Remember to include physical states and conditions (heat, sunlight, catalyst) above the arrow.',
      'For redox identification: the substance gaining oxygen is oxidised (reducing agent); the substance losing oxygen is reduced (oxidising agent).',
      'Rancidity prevention: antioxidants, vacuum packing, refrigeration, nitrogen flushing, airtight containers.',
      'Corrosion prevention: painting, galvanising, oiling, greasing, alloying, tinning.',
    ],
  },
];

export const acidsBasesSaltsNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Acids are sour substances that release H⁺ (H₃O⁺) ions in water; bases are bitter and release OH⁻ ions.',
      'The pH scale (0–14) measures acidity or basicity: pH 7 is neutral, below 7 is acidic, above 7 is basic.',
      'Indicators (litmus, methyl orange, phenolphthalein, natural indicators like turmeric) help identify acids and bases.',
      'Acids react with metals, metal carbonates, and metal hydrogen carbonates to produce salts and gases.',
      'Neutralisation is the reaction between an acid and a base to form salt and water.',
      'Important salts: common salt (NaCl), baking soda (NaHCO₃), washing soda (Na₂CO₃·10H₂O), bleaching powder (CaOCl₂), and Plaster of Paris (CaSO₄·½H₂O).',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Acid: A substance that releases H⁺ (hydronium, H₃O⁺) ions in aqueous solution.',
      'Base: A substance that releases OH⁻ (hydroxide) ions in aqueous solution.',
      'Alkali: A base that is soluble in water (e.g., NaOH, KOH).',
      'Indicator: A substance that changes colour or odour in acidic or basic medium.',
      'pH: The negative logarithm of H⁺ ion concentration; measures acidity or basicity on a 0–14 scale.',
      'Neutralisation: The reaction of an acid with a base to form salt and water.',
      'Strong acid/base: Ionises completely in water (e.g., HCl, NaOH).',
      'Weak acid/base: Ionises partially in water (e.g., CH₃COOH, NH₄OH).',
      'Salt: An ionic compound formed by replacing H⁺ of an acid with a metal ion or ammonium ion.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Hydronium ion (H₃O⁺)',
      'Hydroxide ion (OH⁻)',
      'Indicators (litmus, phenolphthalein, methyl orange)',
      'pH scale',
      'Neutralisation',
      'Strong and weak acids/bases',
      'Salt family (chloride, sulphate, nitrate, carbonate)',
      'Plaster of Paris',
      'Chlor-alkali process',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'pH = −log[H⁺]',
      'HCl + NaOH → NaCl + H₂O (neutralisation)',
      'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑ (acid + carbonate)',
      'CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O (PoP setting)',
      '2NaCl + 2H₂O → 2NaOH + Cl₂↑ + H₂↑ (chlor-alkali process)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Zn + 2HCl → ZnCl₂ + H₂↑ (acid + metal → salt + hydrogen)',
      'Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑ (acid + metal carbonate)',
      'NaOH + HCl → NaCl + H₂O (neutralisation, exothermic)',
      'CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄ (base + salt, blue precipitate)',
      'Ca(OH)₂ + Cl₂ → CaOCl₂ + H₂O (bleaching powder formation)',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'pH scale with colour bands from 0 (red, strong acid) to 14 (purple, strong base)',
      'Setup for testing gas evolved when Na₂CO₃ reacts with HCl (delivery tube into limewater)',
      'Chlor-alkali process electrolytic cell showing anode and cathode products',
      'Crystal structure comparison of Plaster of Paris (½H₂O) and gypsum (2H₂O)',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Blue litmus turns red in acid; red litmus turns blue in base.',
      'Phenolphthalein remains colourless in acid and turns pink in base.',
      'Methyl orange turns red in acid and yellow in base.',
      'CO₂ gas turns limewater milky due to CaCO₃ formation.',
      'Hydrogen gas burns with a "pop" sound when tested with a burning splint.',
      'Bleaching powder (CaOCl₂) smells of chlorine and bleaches coloured fabric.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Our stomach produces HCl for digestion; antacids (mild bases like Mg(OH)₂) neutralise excess acid.',
      'Tooth decay occurs when mouth bacteria produce acids lowering pH below 5.5; toothpastes are basic to neutralise this.',
      'Soil pH affects crop growth; farmers add lime (CaO) if soil is too acidic.',
      'Baking soda (NaHCO₃) is used in baking because it releases CO₂ on heating, making batter rise.',
      'Plaster of Paris is used in casts for broken bones because it sets hard quickly when mixed with water.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing strong/weak with concentrated/dilute — strength refers to degree of ionisation, not concentration.',
      'Writing H⁺ instead of H₃O⁺ in aqueous solutions — H⁺ ions exist as hydronium (H₃O⁺) in water.',
      'Forgetting that HNO₃ does not produce H₂ with metals (it is an oxidising acid).',
      'Confusing baking soda (NaHCO₃) with washing soda (Na₂CO₃·10H₂O).',
      'Not knowing that bleaching powder releases chlorine — it is CaOCl₂, not CaCl₂.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'pH scale and its importance in daily life (stomach, soil, tooth decay)',
      'Plaster of Paris formula and its uses',
      'Chlor-alkali process and its three products',
      'Bleaching powder preparation and uses',
      'Baking soda vs washing soda (formula and uses)',
      'Identification of acids/bases using indicators',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'Activity 2.1: Testing various substances with litmus paper and recording observations.',
      'Activity 2.3: Crystal of copper sulphate in water and adding dilute HCl — colour changes.',
      'Sodium hydrogen carbonate is a mild non-corrosive base; used as antacid to neutralise stomach acid.',
      'Plaster of Paris should be stored in a moisture-proof container because it sets into gypsum on absorbing moisture.',
      'The chlor-alkali process produces NaOH, Cl₂, and H₂ from brine (NaCl solution).',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'pH: "7 is heaven (neutral), below 7 is hell (acidic), above 7 is high (basic)."',
      'Indicators: "Litmus Red→Blue = Base; Phenolphthalein Colourless→Pink = Base."',
      'Salts: "Baking = NaHCO₃ (1H), Washing = Na₂CO₃·10H₂O (10H), PoP = CaSO₄·½H₂O (½H)."',
      'Chlor-alkali: "NaCl + H₂O → NaOH + Cl₂ + H₂" — three products from brine.',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Memorise the chemical formulas and common names of all important salts (NaCl, NaHCO₃, Na₂CO₃, CaOCl₂, CaSO₄·½H₂O).',
      'Remember the three products of the chlor-alkali process and their uses.',
      'Know which indicator gives which colour in acid and base.',
      'Acid + Metal carbonate always gives salt + water + CO₂; test CO₂ with limewater.',
      'Acid + Metal always gives salt + H₂; test H₂ with the pop test.',
    ],
  },
];

export const metalsNonMetalsNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Metals are lustrous, malleable, ductile, good conductors of heat and electricity, and have high melting points.',
      'Non-metals are brittle, poor conductors, and have low melting points; some exist as solids, some as liquids, some as gases.',
      'The reactivity series arranges metals in order of decreasing reactivity; a more reactive metal displaces a less reactive one from its salt solution.',
      'Metals form basic oxides; non-metals form acidic or neutral oxides.',
      'Ionic compounds are formed by the transfer of electrons from a metal to a non-metal; they have high melting points and conduct electricity in molten or aqueous state.',
      'Metals are extracted from ores based on their reactivity: electrolysis for highly reactive, reduction with carbon for moderately reactive, and roasting for least reactive.',
      'Alloys are homogeneous mixtures of metals with improved properties; corrosion (rusting) can be prevented by galvanising, painting, and alloying.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Malleability: The property of a metal being beaten into thin sheets.',
      'Ductility: The property of a metal being drawn into thin wires.',
      'Reactivity series: A list of metals arranged in order of decreasing reactivity.',
      'Ionic compound: A compound formed by the transfer of electrons from a metal to a non-metal.',
      'Ore: A naturally occurring mineral from which a metal can be extracted profitably.',
      'Gangue: Impurities (soil, sand, rocky material) present in ores.',
      'Alloy: A homogeneous mixture of two or more metals (or a metal and a non-metal).',
      'Corrosion: The deterioration of metals due to reaction with air and moisture.',
      'Galvanisation: Coating iron or steel with a layer of zinc to prevent rusting.',
      'Aqua regia: A 3:1 mixture of concentrated HCl and HNO₃ that can dissolve gold and platinum.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Reactivity series (K Na Ca Mg Al Zn Fe Pb Cu H Ag Au)',
      'Ionic bond and ionic compound',
      'Electrovalent bond',
      'Mineral and ore',
      'Gangue',
      'Roasting and calcination',
      'Smelting',
      'Thermite reaction',
      'Alloy and amalgam',
      'Corrosion and galvanisation',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      '2K + 2H₂O → 2KOH + H₂↑ (metal + cold water)',
      'Zn + 2HCl → ZnCl₂ + H₂↑ (metal + acid)',
      'Fe₂O₃ + 2Al → 2Fe + Al₂O₃ (thermite reaction)',
      'Fe + CuSO₄ → FeSO₄ + Cu (displacement)',
      'Cu + ZnSO₄ → No reaction (Cu less reactive than Zn)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      '2Na + 2H₂O → 2NaOH + H₂↑ (vigorous, sodium stored in kerosene)',
      '3Fe + 4H₂O → Fe₃O₄ + 4H₂↑ (iron reacts with steam)',
      '2Al + 3H₂SO₄ → Al₂(SO₄)₃ + 3H₂↑ (aluminium + dilute acid)',
      'Zn + CuSO₄ → ZnSO₄ + Cu (displacement, blue colour fades)',
      '2Cu + O₂ → 2CuO (copper oxide, black, basic)',
      'C + O₂ → CO₂ (non-metal oxide, acidic)',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Reactivity series of metals with hydrogen as reference',
      'Experiment showing reaction of different metals with water/steam (test tube setup)',
      'Electrolytic refining of copper (anode, cathode, electrolyte, impurities as anode mud)',
      'Structure of sodium chloride crystal showing Na⁺ and Cl⁻ ions in a lattice',
      'Thermite reaction apparatus for welding railway tracks',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Sodium and potassium react vigorously with cold water, catching fire; they are stored under kerosene.',
      'Iron does not react with cold water but reacts with steam to form Fe₃O₄ and H₂.',
      'Copper does not react with dilute HCl; it is below hydrogen in the reactivity series.',
      'When zinc is placed in copper sulphate solution, the blue colour fades and a reddish-brown deposit of copper forms.',
      'Ionic compounds are solid, hard, and brittle; they conduct electricity only in molten or aqueous state.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Brass = Cu + Zn (used for decorative items, hardware).',
      'Bronze = Cu + Sn (used for statues, coins).',
      'Stainless steel = Fe + Ni + Cr (corrosion-resistant).',
      'Solder = Pb + Sn (low melting point, used for electrical welding).',
      'Amalgam = any alloy containing mercury (used in dental fillings).',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Forgetting that HNO₃ does not produce H₂ with metals (it is an oxidising acid).',
      'Confusing roasting (in excess air, for sulphide ores) with calcination (in limited air, for carbonate ores).',
      'Writing that copper displaces zinc — copper is less reactive and cannot displace zinc.',
      'Forgetting that ionic compounds do not conduct electricity in solid state (ions are fixed in lattice).',
      'Mixing up brass (Cu+Zn) and bronze (Cu+Sn).',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Reactivity series and displacement reactions',
      'Why ionic compounds have high melting points and conduct electricity only in molten/aqueous state',
      'Extraction of metals based on reactivity (electrolysis vs carbon reduction vs roasting)',
      'Thermite reaction for welding railway tracks',
      'Why sodium is stored in kerosene',
      'Properties and uses of alloys (brass, bronze, stainless steel)',
      'Galvanisation and corrosion prevention',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'Activity 3.1: Testing the malleability and conductivity of various metal and non-metal samples.',
      'Activity 3.4: Reaction of zinc granules with dilute HCl — observe gas formation and temperature change.',
      'On the basis of reactivity, metals are classified into three categories for extraction.',
      'Sodium is so reactive that it reacts violently with air and water; stored under kerosene.',
      'Gold and silver are found in the native (free) state because they are the least reactive.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Reactivity series: "K Na Ca Mg Al Zn Fe Pb Cu H Ag Au" — "Kissable Naughty Cats May All Zink From Playing Cards Silly Aggravating Au-nties."',
      'Alloys: "Brass = Zinky, Bronze = Tinny, Steel = Chrome."',
      'Extraction: "Most reactive → Electrolysis, Middle → Carbon (smelting), Least → Roasting."',
      'Ionic: "Metal gives, non-metal takes — positive and negative attract."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Memorise the reactivity series in order — it is essential for predicting displacement reactions.',
      'Remember: metal + acid → salt + H₂ (except HNO₃); metal + water reactivity depends on position in series.',
      'For ionic compounds: high melting point, soluble in water, conduct only in molten/aqueous state.',
      'Extraction method depends on reactivity: Na/Al → electrolysis, Zn/Fe → carbon reduction, Cu/Hg → roasting, Au/Ag → native state.',
      'Alloys: Brass = Cu+Zn, Bronze = Cu+Sn, Stainless steel = Fe+Ni+Cr, Solder = Pb+Sn.',
    ],
  },
];

export const carbonCompoundsNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Carbon has 4 valence electrons and always forms covalent bonds by sharing electrons; it is tetravalent.',
      'Catenation — the ability of carbon to bond with other carbon atoms — enables it to form long chains, branches, and rings, making it the basis of organic chemistry.',
      'Hydrocarbons are compounds of carbon and hydrogen only: saturated (alkanes, single bonds) and unsaturated (alkenes with double bonds, alkynes with triple bonds).',
      'Functional groups are specific atoms or bonds in organic compounds that determine their chemical properties.',
      'IUPAC nomenclature provides a systematic way to name carbon compounds based on the longest carbon chain and functional group.',
      'Ethanol and ethanoic acid are two important carbon compounds with wide applications.',
      'Soaps are sodium/potassium salts of fatty acids that form micelles to clean oil; detergents work in hard water where soaps fail.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Covalent bond: A bond formed by the sharing of electron pairs between atoms.',
      'Catenation: The ability of an element to form bonds with atoms of the same element, creating chains and rings.',
      'Hydrocarbon: A compound made of only carbon and hydrogen.',
      'Functional group: An atom or group of atoms that determines the chemical properties of an organic compound.',
      'Homologous series: A series of carbon compounds with the same functional group and similar chemical properties, differing by −CH₂− unit.',
      'Isomerism: The phenomenon where compounds have the same molecular formula but different structural formulas.',
      'Esterification: The reaction of a carboxylic acid with an alcohol to form an ester (sweet-smelling) and water.',
      'Saponification: The reaction of an ester with a base (NaOH) to produce soap (salt of fatty acid) and alcohol.',
      'Micelle: A spherical aggregate of soap molecules in water with hydrophobic tails trapping oil and hydrophilic heads facing water.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Covalent bond',
      'Tetravalency and catenation',
      'Saturated and unsaturated hydrocarbons',
      'Functional groups (−OH, −CHO, >C=O, −COOH, −X, −NH₂)',
      'Homologous series',
      'IUPAC nomenclature',
      'Esterification and saponification',
      'Micelles',
      'Hydrogenation',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Alkanes: CₙH₂ₙ₊₂ (single bonds, saturated)',
      'Alkenes: CₙH₂ₙ (double bond, unsaturated)',
      'Alkynes: CₙH₂ₙ₋₂ (triple bond, unsaturated)',
      'CH₃COOH + C₂H₅OH → CH₃COOC₂H₅ + H₂O (esterification)',
      'C₂H₅OH + 2[O] → CH₃COOH + H₂O (oxidation of ethanol)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'C₂H₅OH + Na → C₂H₅ONa + ½H₂↑ (ethanol + sodium)',
      'C₂H₅OH →(H₂SO₄, 170°C)→ C₂H₄ + H₂O (dehydration of ethanol)',
      'CH₃COOH + NaHCO₃ → CH₃COONa + H₂O + CO₂↑ (ethanoic acid + baking soda)',
      'CH₃COOC₂H₅ + NaOH → CH₃COONa + C₂H₅OH (saponification)',
      'Vegetable oil + H₂ →(Ni catalyst)→ Vegetable ghee (hydrogenation)',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Electron dot structure of methane (CH₄), ethane (C₂H₆), ethene (C₂H₄), and ethyne (C₂H₂)',
      'Structure of a micelle showing hydrophilic head (COO⁻) and hydrophobic tail (hydrocarbon chain)',
      'Structural formulas of ethanol and ethanoic acid showing all bonds',
      'Structural isomers of butane (n-butane and isobutane)',
      'Allotropes of carbon: diamond (tetrahedral), graphite (layers), fullerene (C₆₀, football shape)',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Ethanol reacts with sodium to produce hydrogen gas (test: burning splint pops).',
      'When ethanol is heated with concentrated H₂SO₄ at 170°C, ethene gas is produced (decolourises bromine water).',
      'Ethanoic acid reacts with NaHCO₃ to produce brisk effervescence of CO₂ (turns limewater milky).',
      'Esterification produces a sweet-smelling ester; the mixture needs concentrated H₂SO₄ as catalyst.',
      'Soap does not form lather in hard water; it forms a sticky scum with Ca²⁺ and Mg²⁺ ions.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Ethanol (C₂H₅OH) is the active ingredient in alcoholic drinks and is used as a solvent and fuel.',
      'Ethanoic acid (CH₃COOH) is vinegar when diluted to 5–8%; used as a preservative in pickles.',
      'Hydrogenation converts liquid vegetable oils to solid fats (vanaspati/ghee) using Ni catalyst.',
      'Soaps are sodium salts of long-chain fatty acids; detergents are sodium salts of sulphonic acids.',
      'Diamond is the hardest natural substance; graphite is a good conductor and used as a lubricant.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing alkanes (CₙH₂ₙ₊₂) with alkenes (CₙH₂ₙ) and alkynes (CₙH₂ₙ₋₂).',
      'Forgetting that carbon always forms 4 bonds (tetravalent) — check all structures for 4 bonds per carbon.',
      'Mixing up esterification (acid + alcohol → ester + water) with saponification (ester + base → soap + alcohol).',
      'Not knowing that soaps fail in hard water due to scum formation with Ca²⁺/Mg²⁺.',
      'Writing wrong IUPAC names — identify the longest chain and the functional group first.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Why carbon forms covalent bonds (tetravalency, cannot lose/gain 4 electrons)',
      'Catenation and its importance in organic chemistry',
      'Difference between soaps and detergents (hard water behaviour)',
      'Esterification and saponification reactions',
      'Hydrogenation of oils (Ni catalyst, application in making ghee)',
      'IUPAC naming of simple carbon compounds',
      'Allotropes of carbon (diamond, graphite, fullerene)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'Activity 4.1: Testing the odour of ethanol and ethanoic acid.',
      'Activity 4.3: Dehydration of ethanol with conc. H₂SO₄ to produce ethene.',
      'Soaps are molecules in which one end is hydrophilic and the other is hydrophobic.',
      'Carbon has three allotropes — diamond, graphite, and fullerene — with very different properties.',
      'The general formula of the homologous series of alcohols is CₙH₂ₙ₊₁OH.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Alkane prefixes: "My Elephant Plays Best" — Methane(1), Ethane(2), Propane(3), Butane(4).',
      'Hydrocarbon formulas: "Anes add 2, Enes keep n, Ynes subtract 2" — CₙH₂ₙ₊₂, CₙH₂ₙ, CₙH₂ₙ₋₂.',
      'Functional groups: "OH = alcohol, CHO = aldehyde, COOH = acid" — increasing oxidation.',
      'Esterification: "Acid + Alcohol = Ester + Water" (sweet smell). Saponification: "Ester + Base = Soap + Alcohol."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Always draw electron dot structures showing shared electron pairs for covalent compounds.',
      'For IUPAC naming: find the longest carbon chain, number from the end nearest the functional group, and use the correct suffix.',
      'Remember: soaps form scum in hard water; detergents do not — this is a common exam question.',
      'Hydrogenation: unsaturated oil + H₂ →(Ni, 200°C)→ saturated fat; used to make vanaspati ghee.',
      'Know the structures and reactions of ethanol and ethanoic acid thoroughly — they appear in almost every exam.',
    ],
  },
];

export const periodicClassificationNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Early attempts at classification included Dobereiner\'s triads and Newlands\' law of octaves, both of which had limitations.',
      'Mendeleev (1869) arranged elements by increasing atomic mass and left gaps for undiscovered elements, predicting their properties.',
      'Mendeleev\'s table had limitations: isotopes were not placed, some elements were ordered by mass not properties, and hydrogen\'s position was ambiguous.',
      'Henry Moseley (1913) proposed the Modern Periodic Law: properties of elements are a periodic function of their atomic number.',
      'The modern periodic table has 18 groups (vertical columns) and 7 periods (horizontal rows); period number equals the number of electron shells.',
      'Across a period (left to right): atomic size decreases, metallic character decreases, electronegativity increases.',
      'Down a group: atomic size increases, metallic character increases, electronegativity decreases.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Periodic Law: Properties of elements are a periodic function of their atomic number (Modern) or atomic mass (Mendeleev).',
      'Group: A vertical column in the periodic table; elements in the same group have the same number of valence electrons.',
      'Period: A horizontal row in the periodic table; the period number equals the number of electron shells.',
      'Valency: The combining capacity of an element, determined by the number of valence electrons.',
      'Electronegativity: The tendency of an atom to attract the shared pair of electrons in a covalent bond.',
      'Metalloids: Elements with properties intermediate between metals and non-metals (B, Si, Ge, As, Sb, Te).',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Dobereiner\'s triads',
      'Newlands\' law of octaves',
      'Mendeleev\'s periodic table',
      'Modern Periodic Law (Moseley)',
      'Groups and periods',
      'Atomic radius',
      'Metallic and non-metallic character',
      'Electronegativity',
      'Metalloids',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Group 1 valency = +1 (alkali metals)',
      'Group 2 valency = +2 (alkaline earth metals)',
      'Group 17 valency = −1 (halogens)',
      'Group 18 valency = 0 (noble gases, full octet)',
      'Period number = number of electron shells',
      'Maximum electrons in a shell = 2n² (n = shell number)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Group 1: 2Na + 2H₂O → 2NaOH + H₂↑ (alkali metals react vigorously with water)',
      'Group 2: Mg + 2H₂O → Mg(OH)₂ + H₂↑ (less vigorous than Group 1)',
      'Group 17: Cl₂ + 2KBr → 2KCl + Br₂ (halogen displacement — more reactive halogen displaces less reactive)',
      'Group 18: Noble gases do not react under normal conditions (full octet, inert)',
      'Trend: Metallic character decreases across a period; reactivity of metals decreases left to right.',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Modern periodic table showing all 18 groups and 7 periods with element symbols',
      'Graph of atomic radius vs atomic number showing periodic trends',
      'Mendeleev\'s original periodic table with gaps for undiscovered elements',
      'Electron configurations of Group 1 (alkali metals) showing 1 valence electron',
      'Electron configurations of Group 17 (halogens) showing 7 valence electrons',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Lithium, sodium, and potassium (Group 1) are all soft, reactive metals that form +1 ions.',
      'Fluorine, chlorine, and bromine (Group 17) are all highly reactive non-metals that form −1 ions.',
      'Noble gases (Group 18) are inert because they have completely filled outer shells (octet).',
      'Atomic size decreases from left to right across a period because nuclear charge increases, pulling electrons closer.',
      'Atomic size increases down a group because a new electron shell is added in each period.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Dobereiner\'s triads: Li-Na-K (atomic masses 7, 23, 39; mean of Li and K = 23 = Na).',
      'Newlands\' law of octaves: When arranged by increasing atomic mass, every 8th element repeated properties (like musical octaves).',
      'Mendeleev predicted eka-silicon (now germanium) and eka-aluminium (now gallium) — their discovered properties matched his predictions.',
      'In the modern table, the position of an element is determined by its electronic configuration.',
      'Metalloids (B, Si, Ge) are used in semiconductors and electronics.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing atomic number with atomic mass — the modern table is based on atomic number, not mass.',
      'Forgetting that valency first increases then stabilises across a period (1, 2, 3, 4, 3, 2, 1, 0).',
      'Mixing up groups and periods — groups are vertical (same valence electrons), periods are horizontal (same shells).',
      'Not knowing why atomic size decreases across a period — nuclear charge increases with same shell.',
      'Forgetting that Mendeleev left gaps for undiscovered elements — this was his strength, not a weakness.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Mendeleev\'s achievements and limitations',
      'Modern Periodic Law and how it differs from Mendeleev\'s',
      'Trends in atomic size, metallic character, and electronegativity across periods and down groups',
      'Position of hydrogen in the periodic table (controversial)',
      'Why noble gases are inert (completely filled outer shell)',
      'Number of elements in each period (2, 8, 8, 18, 18, 32, incomplete)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'Mendeleev\'s periodic table was based on the formula of the oxides and hydrides formed by elements.',
      'Mendeleev left gaps for elements he predicted would be discovered (eka-silicon = Ge, eka-aluminium = Ga).',
      'The modern periodic table removes anomalies like the position of isotopes (same atomic number = same position).',
      'Elements in the same period have the same number of shells but different numbers of valence electrons.',
      'The metallic character of elements decreases from left to right and increases from top to bottom.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Noble gases: "He Never Arrived Kill Xeno" — He, Ne, Ar, Kr, Xe, Rn.',
      'Periods: "2, 8, 8, 18, 18, 32, rest" — number of elements in each period.',
      'Trends across period: "Size shrinks, metal fades, non-metal rises."',
      'Trends down group: "Size grows, metal grows, non-metal fades."',
      'Triads: "Li-Na-K" — average of first and third equals the second.',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Know the key differences between Mendeleev\'s and the modern periodic table (atomic mass vs atomic number).',
      'Memorise the trends: across a period — size decreases, metallic character decreases, electronegativity increases; down a group — opposite trends.',
      'Remember the number of elements in each period: 2, 8, 8, 18, 18, 32.',
      'Be able to explain why atomic size decreases across a period (increasing nuclear charge with same shell).',
      'Know the positions and properties of Group 1 (alkali metals), Group 17 (halogens), and Group 18 (noble gases).',
    ],
  },
];
