import type { NoteSection } from '../revision-content';

export const ourEnvironmentNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'An ecosystem consists of biotic (living: producers, consumers, decomposers) and abiotic (non-living: air, water, soil, sunlight) components interacting as a unit.',
      'A food chain shows the flow of energy from the sun through producers to consumers and decomposers.',
      'Trophic levels represent the position of organisms in a food chain; only about 10% of energy transfers to the next level (10% law).',
      'A food web is a network of interconnected food chains showing all feeding relationships in an ecosystem.',
      'Biodegradable waste can be decomposed by microorganisms; non-biodegradable waste cannot (plastic, glass, metal).',
      'The ozone layer in the stratosphere absorbs UV radiation and is depleted by CFCs (chlorofluorocarbons).',
      'Biological magnification is the accumulation of non-biodegradable toxins in increasing concentrations at higher trophic levels.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Ecosystem: A self-contained unit of living (biotic) and non-living (abiotic) components that interact and function together.',
      'Food chain: A sequence of organisms through which energy flows from producers to consumers to decomposers.',
      'Trophic level: The position of an organism in a food chain (T1 = producers, T2 = primary consumers, T3 = secondary consumers, T4 = tertiary consumers).',
      'Food web: A network of interconnected food chains showing all possible feeding relationships in an ecosystem.',
      'Biodegradable waste: Waste that can be decomposed by microorganisms (vegetable peels, paper, cloth).',
      'Non-biodegradable waste: Waste that cannot be decomposed by microorganisms (plastic, glass, metal).',
      'Ozone layer: A layer of ozone (O₃) in the stratosphere (15–35 km) that absorbs harmful UV radiation from the sun.',
      'Biological magnification: The accumulation of non-biodegradable toxins in increasing concentrations at higher trophic levels.',
      'Decomposers: Microorganisms (bacteria, fungi) that break down dead organisms and waste, returning nutrients to the soil.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Ecosystem (biotic and abiotic)',
      'Producers, consumers, decomposers',
      'Food chain and food web',
      'Trophic levels (T1, T2, T3, T4)',
      '10% law of energy transfer',
      'Biodegradable and non-biodegradable waste',
      'Ozone layer and CFCs',
      'Biological magnification',
      'Montreal Protocol',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Energy transfer: ~10% per trophic level (10% law)',
      'Ozone formation: O₂ + O → O₃ (in stratosphere, driven by UV)',
      'Ozone depletion: CFCs → Cl + O₃ → ClO + O₂ (chlorine destroys ozone)',
      'Food chain: Sun → Producer → Primary consumer → Secondary consumer → Decomposer',
      'Biological magnification: Toxin concentration increases at each higher trophic level',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Ozone formation: UV light splits O₂ into oxygen atoms → O + O₂ → O₃ (in the stratosphere).',
      'Ozone depletion: CFCs release chlorine atoms → Cl + O₃ → ClO + O₂ → chlorine destroys ozone molecules.',
      'Energy flow: Sun → Producers (photosynthesis) → Primary consumers → Secondary consumers → Decomposers → heat (unidirectional).',
      'Decomposition: Dead organisms + decomposers (bacteria, fungi) → nutrients returned to soil.',
      'Biological magnification: Toxins enter at producer level → concentrate at each trophic level → highest in top predators.',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Diagram of a food chain showing sun → grass (producer) → grasshopper (primary) → frog (secondary) → snake (tertiary)',
      'Diagram of a food web showing multiple interconnected food chains in an ecosystem',
      'Diagram of trophic levels with a pyramid showing energy decreasing at each level',
      'Diagram of ozone layer formation and depletion in the stratosphere',
      'Diagram of biological magnification showing toxin concentration increasing at higher trophic levels',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Energy flow in an ecosystem is unidirectional — it does not cycle back. Only nutrients cycle.',
      'Only about 10% of energy at one trophic level is available to the next; the rest is lost as heat in metabolic processes.',
      'The number of individuals at each trophic level decreases from producers to top consumers (pyramid of numbers).',
      'CFCs (chlorofluorocarbons) release chlorine atoms that destroy ozone molecules in the stratosphere.',
      'Top predators (e.g., hawks, humans) have the highest concentration of non-biodegradable toxins due to biological magnification.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Food chain: Grass → Grasshopper → Frog → Snake → Hawk.',
      'Biodegradable waste: Vegetable peels, paper, cotton cloth, kitchen waste.',
      'Non-biodegradable waste: Plastic bags, glass bottles, metal cans, DDT.',
      'Ozone depletion: CFCs from refrigerants and aerosols caused the ozone hole over Antarctica.',
      'Biological magnification: DDT sprayed on crops → absorbed by plants → eaten by small fish → eaten by large fish → eaten by hawks (highest concentration in hawks).',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing energy flow (unidirectional) with nutrient cycling (circular) — energy does not cycle back.',
      'Forgetting that decomposers are not a trophic level — they break down all levels and return nutrients.',
      'Mixing up biodegradable (can rot) with non-biodegradable (cannot rot) waste.',
      'Writing that ozone is formed by CFCs — ozone forms naturally from O₂ + O; CFCs deplete ozone, not form it.',
      'Forgetting that biological magnification affects non-biodegradable toxins only, not all substances.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Difference between food chain and food web',
      '10% law of energy transfer and why energy flow is unidirectional',
      'Ozone layer: formation, function, and depletion by CFCs',
      'Biological magnification with an example (DDT in food chain)',
      'Role of decomposers in an ecosystem',
      'Biodegradable vs non-biodegradable waste with examples',
      'Montreal Protocol and the ban on CFCs',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'An ecosystem consists of biotic and abiotic components that interact and function together as a unit.',
      'The transfer of energy in a food chain is unidirectional; only about 10% of energy is available to the next trophic level.',
      'The ozone layer shields the surface of the earth from harmful UV radiation from the sun.',
      'CFCs damage the ozone layer; the Montreal Protocol (1987) aimed to freeze and reduce CFC production.',
      'Non-biodegradable pesticides and heavy metals accumulate at higher trophic levels through biological magnification.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Trophic levels: "Producers → Primary → Secondary → Tertiary."',
      '10% law: "Ten percent travels, rest is lost as heat."',
      'Ozone: "O₃ saves from UV, CFC kills O₃."',
      'Waste: "Biodegradable = Can rot, Non-biodegradable = Cannot rot."',
      'Energy flow: "One way only — sun to heat. Nutrients cycle round and round."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Know the difference between a food chain (linear) and a food web (interconnected).',
      'Remember: energy flow is unidirectional (sun → producers → consumers → heat); only nutrients cycle.',
      'Be able to explain the 10% law and draw a pyramid showing energy decreasing at each trophic level.',
      'Know how ozone forms (O₂ + O → O₃) and how CFCs deplete it (Cl + O₃ → ClO + O₂).',
      'Be able to explain biological magnification with a specific example (e.g., DDT in a food chain).',
    ],
  },
];

export const sustainableManagementNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Sustainable development means meeting present needs without compromising future generations\' ability to meet theirs.',
      'The 3Rs — Reduce, Reuse, Recycle — are the core of waste management, in that order of priority.',
      'Water conservation methods include rainwater harvesting, drip irrigation, fixing leaks, and greywater reuse.',
      'Forests maintain biodiversity, the water cycle, soil, and climate; movements like Chipko and Amrita Devi Bishnoi protected them.',
      'Coal and petroleum are non-renewable fossil fuels formed over millions of years; their burning causes pollution and global warming.',
      'The Ganga Action Plan (1985) was launched to reduce pollution in the Ganga by treating domestic and industrial waste.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Sustainable development: Development that meets present needs without compromising the ability of future generations to meet their needs.',
      'Reduce: Using less of a resource to minimise waste.',
      'Reuse: Using an item again instead of discarding it and buying a new one.',
      'Recycle: Processing waste materials into new products.',
      'Rainwater harvesting: Collecting and storing rainwater for reuse or to recharge groundwater.',
      'Drip irrigation: A method of watering plants drop by drop at the roots, reducing water wastage.',
      'Non-renewable resources: Resources that cannot be replenished on a human timescale (coal, petroleum, natural gas).',
      'Renewable resources: Resources that can be replenished naturally (water, forests, solar energy).',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Sustainable development',
      '3Rs (Reduce, Reuse, Recycle)',
      'Water conservation and rainwater harvesting',
      'Drip irrigation',
      'Forest conservation (Chipko Movement, Amrita Devi Bishnoi)',
      'Ganga Action Plan',
      'Fossil fuels (coal, petroleum, natural gas)',
      'Non-renewable resources',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      '3Rs priority: Reduce > Reuse > Recycle',
      'Rainwater harvesting → Groundwater recharge',
      'Forests → Increased infiltration, reduced runoff, reduced soil erosion',
      'Fossil fuels: Coal, Petroleum, Natural gas (non-renewable)',
      '5Rs: Refuse, Reduce, Reuse, Recycle, Repurpose',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Burning fossil fuels: C + O₂ → CO₂ + heat (contributes to greenhouse effect).',
      'Burning coal: S + O₂ → SO₂ (causes acid rain).',
      'Rainwater harvesting: Rainwater → collection pit → filtration → groundwater recharge.',
      'Forest role: Rain → trees slow runoff → water infiltrates soil → groundwater recharged → soil erosion prevented.',
      'Drip irrigation: Water delivered drop by drop at plant roots → minimal evaporation and wastage.',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Diagram of a rainwater harvesting system showing collection, filtration, and groundwater recharge',
      'Diagram of drip irrigation showing pipes and emitters delivering water to plant roots',
      'Diagram of the 3Rs hierarchy (Reduce > Reuse > Recycle)',
      'Diagram showing the role of forests in the water cycle (infiltration, transpiration, preventing runoff)',
      'Diagram of a biogas plant as an example of sustainable resource use',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'India has 16% of the world\'s population but only 4% of its water resources, making water conservation critical.',
      'Forests increase water infiltration and reduce surface runoff, preventing soil erosion and recharging groundwater.',
      'Burning fossil fuels releases CO₂ (greenhouse gas) and SO₂ (acid rain), causing environmental damage.',
      'The Ganga is severely polluted by domestic and industrial waste; the Ganga Action Plan aims to treat this waste before it enters the river.',
      'Overuse of groundwater leads to depletion of aquifers, affecting agriculture and drinking water supply.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Chipko Movement: Villagers in Uttarakhand hugged trees to prevent them from being felled, led by Sundarlal Bahuguna.',
      'Amrita Devi Bishnoi: Sacrificed her life along with 363 others to protect Khejri trees in Rajasthan.',
      'Ganga Action Plan: Launched in 1985 to clean the Ganga by treating domestic and industrial waste.',
      'Water conservation at home: Fix leaking taps, use bucket instead of shower, reuse RO waste water for plants.',
      '5Rs: Refuse single-use plastic, Reduce consumption, Reuse items, Recycle waste, Repurpose old items.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing the order of the 3Rs — Reduce comes first (most important), then Reuse, then Recycle.',
      'Forgetting that coal and petroleum are non-renewable and take millions of years to form.',
      'Mixing up renewable and non-renewable resources — water and forests are renewable if managed properly.',
      'Not knowing that the Ganga Action Plan was launched in 1985, not a later date.',
      'Writing that recycling is the best option — reducing and reusing are higher priority than recycling.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'The 3Rs of waste management and their order of priority',
      'Why coal and petroleum are called non-renewable (formed over millions of years)',
      'Rainwater harvesting and its importance for groundwater recharge',
      'The Chipko Movement and Amrita Devi Bishnoi sacrifice for forest conservation',
      'The Ganga Action Plan and its objectives',
      'Sustainable development definition and importance',
      'Why India needs water conservation (16% population, 4% water resources)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'We have not inherited the Earth from our ancestors; we have borrowed it from our children. Resources must last for future generations.',
      'The 3Rs — Reduce, Reuse, Recycle — are the core of waste management. Reduce is the most important, followed by Reuse and then Recycle.',
      'Forests maintain biodiversity, regulate the water cycle, prevent soil erosion, and help maintain the climate.',
      'Coal and petroleum are non-renewable fossil fuels formed from dead organisms over millions of years.',
      'The Ganga Action Plan was launched in 1985 to reduce pollution in the Ganga by treating waste before it enters the river.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      '3Rs order: "Reduce before you Reuse, Reuse before you Recycle."',
      'Water: "Harvest rain, recharge aquifer, drip by drip."',
      'Forests: "Chipko = Hug trees, Bishnoi = Protect Khejri."',
      'Quote: "Borrowed from our children, not inherited from ancestors."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Know the 3Rs in order: Reduce > Reuse > Recycle. Be able to explain why reducing is better than recycling.',
      'Remember the key movements: Chipko Movement (Sundarlal Bahuguna, Uttarakhand) and Amrita Devi Bishnoi (Rajasthan, Khejri trees).',
      'Be able to explain rainwater harvesting and drip irrigation with diagrams.',
      'Know why fossil fuels are non-renewable and the environmental impact of burning them (CO₂, SO₂, global warming).',
      'Remember the Ganga Action Plan (1985) and its objective of treating waste before it enters the river.',
    ],
  },
];
