import type { NoteSection } from '../revision-content';

export const lightReflectionRefractionNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Light travels in straight lines and reflects off surfaces following the laws of reflection.',
      'Spherical mirrors (concave and convex) form images according to the mirror formula 1/v + 1/u = 1/f.',
      'Refraction is the bending of light when it passes from one transparent medium to another of different optical density.',
      'Lenses (convex and concave) refract light to form images; the lens formula is 1/v − 1/u = 1/f.',
      'The power of a lens is P = 1/f (in metres), measured in dioptres (D); convex lenses have positive power, concave lenses negative.',
      'The refractive index of a medium measures how much light slows down in it: n = c/v.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Reflection: The bouncing back of light from a surface.',
      'Incident ray: A ray of light falling on a surface.',
      'Reflected ray: A ray of light bouncing back from a surface.',
      'Normal: The perpendicular line drawn to the reflecting surface at the point of incidence.',
      'Refraction: The bending of light when it passes from one transparent medium to another.',
      'Refractive index: The ratio of the speed of light in vacuum to its speed in the medium (n = c/v).',
      'Focal length (f): The distance between the pole and the focus of a mirror or lens.',
      'Radius of curvature (R): The radius of the sphere of which the mirror is a part; R = 2f.',
      'Power of a lens (P): The reciprocal of the focal length in metres; P = 1/f, unit: dioptre (D).',
      'Magnification (m): The ratio of the height of the image to the height of the object; m = h\'/h = −v/u.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Laws of reflection',
      'Concave and convex mirrors',
      'Mirror formula (1/v + 1/u = 1/f)',
      'Snell\'s law of refraction',
      'Refractive index (n = c/v)',
      'Lens formula (1/v − 1/u = 1/f)',
      'Power of a lens (P = 1/f, dioptre)',
      'Magnification (m = −v/u = h\'/h)',
      'Sign convention (Cartesian)',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Mirror formula: 1/v + 1/u = 1/f',
      'Lens formula: 1/v − 1/u = 1/f (note the minus sign)',
      'Magnification: m = −v/u = h\'/h',
      'Power of lens: P = 1/f (f in metres, P in dioptres)',
      'Refractive index: n = c/v = sin i / sin r',
      'Relation between R and f: f = R/2 (for spherical mirrors)',
      'Power of combination: P = P₁ + P₂ (lenses in contact)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Reflection: i = r (angle of incidence equals angle of reflection); incident ray, reflected ray, and normal are coplanar.',
      'Refraction (Snell\'s law): n₁ sin i = n₂ sin r; light bends towards normal when entering a denser medium.',
      'Convex lens imaging: Object beyond 2F → real, inverted, diminished image between F and 2F.',
      'Concave mirror imaging: Object beyond C → real, inverted, diminished image between F and C.',
      'Total internal reflection: When light travels from denser to rarer medium at angle > critical angle, it reflects back entirely.',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Ray diagram for image formation by a concave mirror for six different object positions',
      'Ray diagram for image formation by a convex mirror (always virtual, erect, diminished)',
      'Ray diagram for image formation by a convex lens for various object positions',
      'Ray diagram showing refraction of light through a rectangular glass slab (incident ray, refracted ray, emergent ray)',
      'Diagram showing the sign convention (Cartesian) for mirrors and lenses',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'A concave mirror always forms a real, inverted image for objects beyond the focus; a virtual, erect image only when the object is between F and P.',
      'A convex mirror always forms a virtual, erect, and diminished image regardless of object position.',
      'When light passes through a glass slab, the emergent ray is parallel to the incident ray but laterally displaced.',
      'A convex lens converges parallel rays to the focus; a concave lens diverges them, appearing to come from the focus.',
      'The image formed by a plane mirror is always virtual, erect, same size, and laterally inverted.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Concave mirror uses: Shaving mirror (magnified virtual image), dentist\'s mirror, torch reflector, solar furnace.',
      'Convex mirror uses: Rear-view mirror in vehicles (wider field of view, erect image), blind corner mirrors.',
      'Convex lens uses: Magnifying glass, camera lens, microscope objective, correcting hypermetropia.',
      'Concave lens uses: Correcting myopia, peephole in doors.',
      'Refractive index examples: n_water = 1.33, n_glass = 1.5, n_diamond = 2.42.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Using the wrong sign convention — all distances are measured from the pole (mirror) or optical centre (lens); against incident light = negative.',
      'Confusing the mirror formula (1/v + 1/u = 1/f) with the lens formula (1/v − 1/u = 1/f) — note the sign difference.',
      'Forgetting that convex lens power is positive and concave lens power is negative.',
      'Writing m = v/u instead of m = −v/u (the negative sign is important for image orientation).',
      'Not applying sign convention correctly when substituting values into formulas.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Mirror formula and lens formula calculations with sign convention',
      'Image formation by concave and convex mirrors for different object positions',
      'Power of a lens and combination of lenses (P = P₁ + P₂)',
      'Refractive index and Snell\'s law',
      'Uses of concave and convex mirrors in daily life',
      'Magnification calculations (m = −v/u = h\'/h)',
      'Refraction through a glass slab (lateral displacement)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'The mirror formula 1/v + 1/u = 1/f holds for spherical mirrors under the new Cartesian sign convention.',
      'The refractive index of a transparent medium is the ratio of the speed of light in vacuum to its speed in that medium.',
      'Power of a lens is the reciprocal of its focal length; it is measured in dioptres when f is in metres.',
      'A concave mirror is called a converging mirror; a convex mirror is called a diverging mirror.',
      'A convex lens is called a converging lens; a concave lens is called a diverging lens.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Mirror vs Lens formula: "Mirror Plus, Lens Minus" — 1/v + 1/u = 1/f (mirror); 1/v − 1/u = 1/f (lens).',
      'Concave mirror uses: "Shaving, Dentist, Torch, Solar furnace."',
      'Convex mirror uses: "Rear-view, Blind corners."',
      'Sign convention: "Against the light = Negative; Along the light = Positive."',
      'Power: "Convex = Positive (+), Concave = Negative (−)."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Always apply the sign convention before substituting values into the mirror or lens formula.',
      'For image formation: draw at least two rays (one parallel to the axis reflecting/refracting through F, one through C/pole).',
      'Remember: concave mirror can form both real and virtual images; convex mirror only forms virtual images.',
      'Power of combination of lenses in contact: P = P₁ + P₂; if separated, use the lensmaker\'s formula.',
      'For magnification: positive m = erect image (virtual); negative m = inverted image (real).',
    ],
  },
];

export const humanEyeNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'The human eye works like a camera: the cornea and lens focus light onto the retina, where photoreceptors (rods and cones) convert light into nerve impulses.',
      'Accommodation is the ability of the eye lens to change its focal length (via ciliary muscles) to focus on near and distant objects.',
      'Common defects of vision are myopia (short-sightedness), hypermetropia (long-sightedness), and presbyopia; each is corrected by a specific type of lens.',
      'Dispersion of white light by a prism produces a spectrum of seven colours (VIBGYOR); violet bends most, red bends least.',
      'A rainbow is formed by dispersion and internal reflection of sunlight by water droplets.',
      'Atmospheric refraction causes twinkling of stars, advanced sunrise, and delayed sunset.',
      'The Tyndall effect is the scattering of light by colloidal particles, making a light beam visible.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Accommodation: The ability of the eye lens to change its focal length to focus on objects at different distances.',
      'Myopia (short-sightedness): A defect where the image of a distant object forms in front of the retina; corrected with a concave lens.',
      'Hypermetropia (long-sightedness): A defect where the image of a near object forms behind the retina; corrected with a convex lens.',
      'Presbyopia: An age-related defect where both near and far vision are affected; corrected with bifocal lenses.',
      'Dispersion: The splitting of white light into its constituent colours by a prism.',
      'Spectrum: The band of seven colours (VIBGYOR) produced by dispersion of white light.',
      'Tyndall effect: The scattering of light by particles in a colloid or suspension, making the light beam visible.',
      'Atmospheric refraction: The bending of light as it passes through layers of air of varying densities.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Cornea, iris, pupil, lens, retina, optic nerve',
      'Rods (dim light) and cones (colour vision)',
      'Ciliary muscles and accommodation',
      'Myopia, hypermetropia, presbyopia',
      'Dispersion and spectrum (VIBGYOR)',
      'Rainbow formation',
      'Tyndall effect',
      'Atmospheric refraction (twinkling of stars, advanced sunrise)',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Myopia correction: concave lens, f = −d (d = far point distance)',
      'Hypermetropia correction: convex lens, f = +d (d = near point distance)',
      'Power of lens: P = 1/f (dioptres, f in metres)',
      'Refractive index: n = c/v',
      'Rayleigh scattering: intensity ∝ 1/λ⁴ (shorter wavelengths scatter more)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Dispersion: White light → prism → VIBGYOR spectrum (violet bends most, red bends least).',
      'Rainbow formation: Sunlight → water droplet → refraction → dispersion → internal reflection → refraction → observer sees rainbow.',
      'Accommodation (near): Ciliary muscles contract → lens becomes thicker → focal length decreases → near object focuses on retina.',
      'Accommodation (far): Ciliary muscles relax → lens becomes thinner → focal length increases → distant object focuses on retina.',
      'Tyndall effect: Light passes through a colloid → particles scatter light → beam becomes visible (e.g., sunlight through dust).',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Diagram of the human eye showing cornea, iris, pupil, lens, retina, optic nerve, ciliary muscles',
      'Ray diagrams showing image formation in myopic eye and correction with concave lens',
      'Ray diagrams showing image formation in hypermetropic eye and correction with convex lens',
      'Diagram of dispersion of white light through a prism producing VIBGYOR spectrum',
      'Diagram of rainbow formation showing refraction, dispersion, and internal reflection in a water droplet',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'In a myopic eye, the image of a distant object forms in front of the retina (eyeball too long or lens too curved).',
      'In a hypermetropic eye, the image of a near object forms behind the retina (eyeball too short or lens too flat).',
      'When white light passes through a prism, violet deviates the most and red deviates the least.',
      'The sky appears blue because air molecules scatter shorter wavelengths (blue) more than longer wavelengths (Rayleigh scattering).',
      'Stars twinkle because atmospheric refraction changes continuously due to varying air density, but planets (being disc-like sources) do not twinkle.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Myopia: A person cannot see beyond 2 m → corrected with a concave lens of focal length 2 m (power = −0.5 D).',
      'Hypermetropia: A person cannot see within 100 cm → corrected with a convex lens of suitable power.',
      'Rainbow: Seen after rain when sunlight passes through water droplets acting as tiny prisms.',
      'Tyndall effect: A beam of sunlight is visible through dust in a dark room; blue colour of the sky.',
      'Advanced sunrise and delayed sunset: The sun is visible about 2 minutes before actual sunrise and 2 minutes after actual sunset due to atmospheric refraction.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing myopia (short-sighted, concave lens) with hypermetropia (long-sighted, convex lens).',
      'Forgetting that presbyopia is age-related and requires bifocal lenses (not just a single lens type).',
      'Writing that red light bends more than violet — violet bends most (shortest wavelength), red bends least.',
      'Confusing the Tyndall effect with refraction — Tyndall is scattering of light by particles, not bending.',
      'Not knowing why stars twinkle but planets don\'t — stars are point sources, planets are extended (disc-like) sources.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Accommodation mechanism (ciliary muscles, lens thickness change)',
      'Myopia and hypermetropia: causes and lens corrections',
      'Dispersion of white light by a prism (VIBGYOR, violet bends most)',
      'Why the sky is blue and the sunset is red (scattering)',
      'Tyndall effect and its examples',
      'Why stars twinkle but planets do not',
      'Advanced sunrise and delayed sunset (atmospheric refraction)',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'The eye lens is made of a transparent, jelly-like material; its curvature is controlled by ciliary muscles.',
      'The maximum distance at which the eye can see clearly is called the far point (infinity for a normal eye).',
      'The minimum distance for clear vision is the least distance of distinct vision (25 cm for a normal adult).',
      'The splitting of white light into its constituent colours by a prism is called dispersion.',
      'The Tyndall effect is the scattering of light by particles in a colloid or a fine suspension.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'VIBGYOR: "Violet, Indigo, Blue, Green, Yellow, Orange, Red" — Violet bends Most, Red bends Least.',
      'Myopia = Minus (concave lens); Hypermetropia = Hifi/High (convex lens).',
      'Twinkling: "Stars twinkle (point), Planets don\'t (disc)."',
      'Sky colour: "Blue scatters most (short wavelength), Red passes through (long wavelength)."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Know the parts of the eye and their functions (cornea = refraction, lens = fine focusing, retina = image formation, rods = dim light, cones = colour).',
      'Be able to draw ray diagrams for myopia and hypermetropia corrections.',
      'Remember: dispersion → VIBGYOR; violet bends most (shortest λ), red bends least (longest λ).',
      'Scattering ∝ 1/λ⁴ — shorter wavelengths scatter more (blue sky); at sunset, red/orange dominate because blue is scattered away.',
      'Atmospheric refraction: advanced sunrise (~2 min), delayed sunset (~2 min), twinkling of stars.',
    ],
  },
];

export const electricityNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'Electric current is the rate of flow of charge through a conductor; I = Q/t, measured in amperes (A).',
      'Ohm\'s law states that V = IR; the current through a conductor is directly proportional to the voltage across it (at constant temperature).',
      'Resistance depends on the material, length, and cross-sectional area: R = ρL/A, where ρ is resistivity.',
      'Resistors in series have the same current and add up: R = R₁ + R₂ + R₃; resistors in parallel have the same voltage and combine reciprocally.',
      'Electric power is P = VI = I²R = V²/R; the commercial unit of energy is the kilowatt-hour (kWh).',
      'The heating effect of current (H = I²Rt) is used in heaters, irons, and fuses.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Electric current: The rate of flow of electric charge through a conductor; I = Q/t, unit: ampere (A).',
      'Electric potential: The work done per unit charge to move a charge from infinity to a point; unit: volt (V).',
      'Potential difference: The work done to move a unit charge between two points; V = W/Q, unit: volt (V).',
      'Resistance: The opposition to the flow of electric current; R = V/I, unit: ohm (Ω).',
      'Resistivity (ρ): The resistance of a conductor of unit length and unit cross-sectional area; unit: Ω·m. It depends on material and temperature, not on length or area.',
      'Electric power: The rate at which electric energy is consumed; P = VI = I²R = V²/R, unit: watt (W).',
      '1 kWh: The energy consumed when 1 kW of power is used for 1 hour; 1 kWh = 3.6 × 10⁶ J.',
      'Fuse: A safety device that melts and breaks the circuit when current exceeds a safe limit.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Charge (Q), current (I), potential difference (V)',
      'Ohm\'s law (V = IR)',
      'Resistance and resistivity (ρ)',
      'Series and parallel circuits',
      'Electric power (P = VI = I²R = V²/R)',
      'Heating effect (H = I²Rt)',
      'Kilowatt-hour (kWh) and units',
      'Fuse and short circuit',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'I = Q/t (current = charge/time)',
      'V = IR (Ohm\'s law)',
      'R = ρL/A (resistance formula)',
      'Series: R_eq = R₁ + R₂ + R₃',
      'Parallel: 1/R_eq = 1/R₁ + 1/R₂ + 1/R₃',
      'P = VI = I²R = V²/R (electric power)',
      'H = I²Rt (Joule\'s law of heating)',
      '1 kWh = 3.6 × 10⁶ J',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Ohm\'s law: V = IR — doubling voltage doubles current (at constant R).',
      'Heating effect: Current passes through a high-resistance wire → wire heats up → H = I²Rt.',
      'Series circuit: If one bulb fails, all go off (same current path).',
      'Parallel circuit: If one appliance fails, others continue working (independent paths).',
      'Fuse action: Excessive current → fuse wire heats and melts → circuit breaks → appliance protected.',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Circuit diagram showing a battery, resistor, ammeter (in series), and voltmeter (in parallel)',
      'Diagram of resistors connected in series and in parallel',
      'Diagram of a household circuit showing live, neutral, and earth wires with a fuse',
      'Diagram of an electric fuse in a circuit',
      'V-I graph for an ohmic resistor (straight line through origin) and a non-ohmic resistor (curve)',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'In a series circuit, the current is the same through all resistors, but the voltage divides.',
      'In a parallel circuit, the voltage is the same across all resistors, but the current divides.',
      'The equivalent resistance in parallel is always less than the smallest individual resistance.',
      'Alloys (like nichrome) are used for heating elements because they have high resistivity and do not oxidise at high temperatures.',
      'Ammeters are connected in series (low resistance); voltmeters are connected in parallel (high resistance).',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Heating effect: Electric heater, iron, toaster, electric kettle, geyser.',
      'Lighting effect: Electric bulb (tungsten filament, high melting point 3380°C).',
      'Magnetic effect: Electromagnet, electric motor (studied in the next chapter).',
      'Fuse: Used in household circuits to protect appliances from overcurrent.',
      'Power calculation: If a bulb is rated 220V, 100W, then I = P/V = 100/220 = 0.45 A.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing series and parallel formulas — series adds resistances directly; parallel adds reciprocals.',
      'Forgetting that resistivity depends on material and temperature, not on length or area.',
      'Mixing up the units — power in watts, energy in joules or kWh; 1 kWh = 3.6 × 10⁶ J.',
      'Writing P = VI without knowing the alternative forms P = I²R and P = V²/R.',
      'Not knowing that a fuse is always connected to the live wire, not the neutral wire.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Ohm\'s law and V-I graph (straight line for ohmic resistors)',
      'Series and parallel equivalent resistance calculations',
      'R = ρL/A and factors affecting resistance',
      'Electric power formulas (P = VI = I²R = V²/R)',
      'Heating effect of current and its applications (heater, fuse)',
      'Why alloys are used in heating elements (high resistivity, no oxidation)',
      'Energy calculation in kWh and electricity bill problems',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'A stream of electrons moving through a conductor constitutes an electric current.',
      'The resistance of a conductor depends on its length, area of cross-section, and the nature of its material.',
      'The commercial unit of electrical energy is the kilowatt-hour (kWh), which is the energy consumed when 1 kW of power is used for 1 hour.',
      'The heating effect of electric current is used in devices such as electric heaters, irons, and toasters.',
      'A fuse is a safety device that protects circuits and appliances by melting when the current exceeds a safe value.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Series: "Same current, voltage splits, resistances add."',
      'Parallel: "Same voltage, current splits, reciprocals add."',
      'Power: "PVI squared R" — P = VI = I²R = V²/R.',
      'Wire colours: "Red Live, Black Neutral, Green Earth."',
      'Resistance: "R ∝ L (longer = more R), R ∝ 1/A (thicker = less R)."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Always use SI units consistently: V in volts, I in amperes, R in ohms, P in watts, E in joules or kWh.',
      'For series: R_eq = R₁ + R₂ + R₃ (always greater than the largest resistor).',
      'For parallel: 1/R_eq = 1/R₁ + 1/R₂ + 1/R₃ (always less than the smallest resistor).',
      'Remember all three power formulas and know when to use each (P = VI when V and I are known, P = I²R when I and R are known, P = V²/R when V and R are known).',
      'For electricity bills: Energy = Power × Time; convert to kWh and multiply by the rate per unit.',
    ],
  },
];

export const magneticEffectsNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'A current-carrying conductor produces a magnetic field around it; the direction is given by the right-hand thumb rule.',
      'A current-carrying conductor in a magnetic field experiences a force; direction is given by Fleming\'s left-hand rule (used in motors).',
      'Electromagnetic induction (Faraday) is the production of an electric current by changing the magnetic field; direction is given by Fleming\'s right-hand rule (used in generators).',
      'An electric motor converts electrical energy to mechanical energy; an electric generator converts mechanical energy to electrical energy.',
      'Domestic circuits use live, neutral, and earth wires; fuses and earth wires protect against short circuits and electric shock.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Magnetic field: The region around a magnet or current-carrying conductor where magnetic force can be detected.',
      'Solenoid: A coil of many turns of insulated copper wire in the shape of a cylinder; it behaves like a bar magnet when current flows.',
      'Electromagnet: A solenoid with a soft iron core that produces a strong magnetic field when current passes through it.',
      'Electromagnetic induction: The production of an induced EMF (and current) in a conductor due to a changing magnetic field.',
      'Electric motor: A device that converts electrical energy into mechanical (rotational) energy.',
      'Electric generator: A device that converts mechanical energy into electrical energy using electromagnetic induction.',
      'Short circuit: A direct contact between the live and neutral wires, causing a very high current to flow.',
      'Overloading: Connecting too many appliances to a single circuit, drawing more current than the safe limit.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Magnetic field and field lines',
      'Right-hand thumb rule',
      'Solenoid and electromagnet',
      'Fleming\'s left-hand rule (motor)',
      'Fleming\'s right-hand rule (generator)',
      'Electromagnetic induction (Faraday)',
      'AC and DC generators',
      'Domestic circuits (live, neutral, earth)',
      'Fuse and short circuit',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Force on conductor: F = BIL sin θ',
      'Right-hand thumb rule: Thumb = current direction, Fingers = magnetic field direction',
      'Left-hand rule: Thumb = Force/Motion, Forefinger = Field, Middle finger = Current (FBI → Motor)',
      'Right-hand rule: Thumb = Motion, Forefinger = Field, Middle finger = Induced current (FBI → Generator)',
      'AC supply in India: 50 Hz, 220 V',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Current through a straight wire → circular magnetic field around it (right-hand thumb rule).',
      'Current through a solenoid → uniform magnetic field inside (like a bar magnet); used to make electromagnets.',
      'Current-carrying conductor in a magnetic field → force F = BIL sin θ (Fleming\'s left-hand rule).',
      'Changing magnetic field through a coil → induced EMF (Faraday\'s law; Fleming\'s right-hand rule).',
      'Motor: Current in coil + magnetic field → force on coil → rotation (electrical → mechanical).',
      'Generator: Coil rotated in magnetic field → changing flux → induced current (mechanical → electrical).',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Magnetic field lines around a bar magnet (from N to S outside, S to N inside)',
      'Magnetic field around a current-carrying straight conductor (concentric circles)',
      'Magnetic field inside a solenoid (uniform, parallel lines)',
      'Diagram of an electric motor showing armature, commutator, brushes, and field magnet',
      'Diagram of an AC generator showing slip rings, armature, and field magnet',
      'Diagram of a domestic circuit showing live, neutral, earth wires, fuse, and appliances',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Iron filings around a bar magnet arrange themselves along magnetic field lines (from N to S).',
      'A compass needle placed near a current-carrying wire deflects, showing the magnetic field.',
      'The magnetic field inside a solenoid is uniform and parallel to the axis; outside, it is like a bar magnet.',
      'Reversing the direction of current reverses the direction of the magnetic field.',
      'A motor rotates because the force on the two sides of the coil is in opposite directions (couple).',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Electromagnet: Used in cranes for lifting iron, electric bells, loudspeakers.',
      'Electric motor: Used in fans, washing machines, mixers, electric cars.',
      'Electric generator: Used in power plants to generate electricity.',
      'Domestic circuit: Live wire (red, 220V), neutral (black, 0V), earth (green) — fuse on live wire.',
      'Short circuit: Live wire touches neutral wire directly → very high current → fuse melts → circuit breaks.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing Fleming\'s left-hand rule (motor) with right-hand rule (generator) — left = motor, right = generator.',
      'Forgetting that the force on a conductor is zero when the conductor is parallel to the magnetic field (sin θ = 0).',
      'Mixing up AC and DC generators — AC uses slip rings, DC uses a split-ring commutator.',
      'Not knowing the difference between live, neutral, and earth wires — fuse is always on the live wire.',
      'Writing that a generator "produces" energy — it converts mechanical energy to electrical energy.',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Right-hand thumb rule for magnetic field direction around a conductor',
      'Fleming\'s left-hand rule (motor) and right-hand rule (generator) — when and how to apply',
      'Electromagnetic induction and Faraday\'s law',
      'Difference between AC and DC generators (slip rings vs split-ring commutator)',
      'Domestic circuit: live, neutral, earth wires and fuse placement',
      'Function of earth wire (safety, prevents electric shock)',
      'Why a compass needle deflects near a current-carrying wire',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'A magnetic field is produced around a current-carrying conductor, as shown by the deflection of a compass needle.',
      'The direction of the magnetic field around a straight conductor is given by the right-hand thumb rule.',
      'A solenoid with a soft iron core acts as an electromagnet, producing a strong and controllable magnetic field.',
      'An electric motor converts electrical energy to mechanical energy using Fleming\'s left-hand rule.',
      'An electric generator converts mechanical energy to electrical energy using electromagnetic induction.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Hand rules: "Left for Motors, Right for Generators."',
      'FBI: "F = Force (thumb), B = Field (forefinger), I = Current (middle finger)."',
      'Wire colours: "Red Live, Black Neutral, Green Earth."',
      'Generator types: "AC = Slip rings, DC = Split ring commutator."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Know when to use the left-hand rule (motor, force on conductor) and the right-hand rule (generator, induced current).',
      'Be able to draw the magnetic field pattern around a bar magnet, straight conductor, and solenoid.',
      'Remember: AC generator uses slip rings, DC generator uses a split-ring commutator.',
      'Know the domestic circuit: live (red, 220V), neutral (black, 0V), earth (green, safety); fuse on live wire.',
      'Understand the function of the earth wire: it provides a low-resistance path to ground, preventing electric shock if the appliance body becomes live.',
    ],
  },
];

export const sourcesOfEnergyNotes: NoteSection[] = [
  {
    title: 'Chapter Summary',
    icon: 'BookOpen',
    items: [
      'A good fuel has high calorific value, low ignition temperature, low pollution, and is easy to transport and store.',
      'Conventional sources include fossil fuels (coal, petroleum, natural gas), hydroelectric power, thermal power, and nuclear energy.',
      'Renewable sources include solar, wind, tidal, geothermal, biogas, and hydroelectric energy.',
      'Nuclear energy is produced by fission (splitting heavy nuclei like U-235) or fusion (combining light nuclei like hydrogen).',
      'Biogas is produced by anaerobic decomposition of organic waste; it is 60–70% methane and is a clean, renewable fuel.',
      'The greenhouse effect is caused by CO₂, CH₄, and water vapour trapping heat; burning fossil fuels increases CO₂ and causes global warming.',
    ],
  },
  {
    title: 'Important Definitions',
    icon: 'BookMarked',
    items: [
      'Calorific value: The amount of heat energy produced by the complete combustion of 1 kg of a fuel (kJ/kg).',
      'Ignition temperature: The minimum temperature at which a fuel catches fire and starts burning.',
      'Renewable energy: Energy from sources that can be replenished naturally in a short time (solar, wind, hydro).',
      'Non-renewable energy: Energy from sources that cannot be replenished (coal, petroleum, natural gas).',
      'Nuclear fission: The splitting of a heavy nucleus (like U-235) into lighter nuclei, releasing energy and neutrons.',
      'Nuclear fusion: The combining of light nuclei (like hydrogen) to form a heavier nucleus, releasing enormous energy (powers the sun).',
      'Biogas: A mixture of methane (60–70%) and CO₂ (30–40%) produced by anaerobic decomposition of organic waste.',
      'Greenhouse effect: The trapping of heat by greenhouse gases (CO₂, CH₄, water vapour) in the Earth\'s atmosphere.',
    ],
  },
  {
    title: 'NCERT Keywords',
    icon: 'Key',
    items: [
      'Good fuel characteristics',
      'Conventional and non-conventional sources',
      'Fossil fuels (coal, petroleum, natural gas)',
      'Nuclear fission and fusion',
      'Renewable energy (solar, wind, tidal, geothermal, biogas)',
      'Solar cells (photovoltaic)',
      'Greenhouse effect and global warming',
      'Sustainable development',
    ],
  },
  {
    title: 'Important Formulas',
    icon: 'Sigma',
    items: [
      'Nuclear fission: ²³⁵U + ¹n → ¹⁴¹Ba + ⁹²Kr + 3¹n + energy',
      'Biogas composition: 60–70% CH₄ + 30–40% CO₂',
      'Energy = Power × Time (kWh)',
      '1 kWh = 3.6 × 10⁶ J',
      'Calorific value = Heat energy / Mass (kJ/kg)',
    ],
  },
  {
    title: 'Important Reactions',
    icon: 'FlaskConical',
    items: [
      'Nuclear fission: ²³⁵U + ¹n → ¹⁴¹Ba + ⁹²Kr + 3¹n + energy (controlled in reactors, uncontrolled in bombs).',
      'Nuclear fusion: 4 ¹H → ⁴He + 2e⁺ + 26.7 MeV (occurs in the sun; hydrogen bomb).',
      'Biogas production: Organic waste + anaerobic bacteria → CH₄ + CO₂ + trace gases.',
      'Combustion of fossil fuels: C + O₂ → CO₂ + heat; CH₄ + 2O₂ → CO₂ + 2H₂O + heat.',
      'Solar cell: Sunlight → semiconductor (silicon) → electric current (photovoltaic effect).',
    ],
  },
  {
    title: 'Important Diagrams',
    icon: 'Image',
    items: [
      'Diagram of a nuclear fission chain reaction showing U-235 splitting and releasing neutrons',
      'Diagram of a biogas plant showing inlet, digester, outlet, and gas storage',
      'Diagram of a solar panel (photovoltaic cell) converting sunlight to electricity',
      'Diagram of a windmill/wind turbine generating electricity',
      'Diagram of a hydroelectric power plant showing dam, turbine, and generator',
    ],
  },
  {
    title: 'Important Observations',
    icon: 'Eye',
    items: [
      'Fossil fuels produce CO₂, SO₂, and NO₂ on combustion, contributing to air pollution and global warming.',
      'Nuclear fission of U-235 releases enormous energy and neutrons, which can sustain a chain reaction.',
      'Biogas burns with a clean blue flame (like LPG) and produces no smoke, unlike wood or coal.',
      'Solar panels produce electricity only when sunlight is available; they are weather-dependent.',
      'Wind turbines require a minimum wind speed to operate and are located in coastal or open areas.',
    ],
  },
  {
    title: 'Important Examples',
    icon: 'Lightbulb',
    items: [
      'Fossil fuels: Coal (thermal power), petroleum (vehicles), natural gas (cooking, CNG).',
      'Nuclear energy: Used in nuclear power plants (Tarapur, Narora); fission of U-235.',
      'Solar energy: Solar panels for electricity, solar water heaters, solar cookers.',
      'Wind energy: Wind farms in coastal and open areas; windmills for pumping water and generating electricity.',
      'Biogas: Produced from cow dung and organic waste in biogas plants; used for cooking and lighting in rural areas.',
    ],
  },
  {
    title: 'Common Mistakes',
    icon: 'AlertTriangle',
    items: [
      'Confusing nuclear fission (splitting heavy nuclei) with fusion (combining light nuclei).',
      'Forgetting that biogas is mainly methane (CH₄), not CO₂.',
      'Writing that nuclear energy is "clean" without considering radioactive waste disposal.',
      'Not knowing the difference between renewable and non-renewable sources.',
      'Forgetting that the greenhouse effect is natural but enhanced by human activities (burning fossil fuels).',
    ],
  },
  {
    title: 'PYQ Favourite Concepts',
    icon: 'Star',
    items: [
      'Characteristics of a good fuel (calorific value, ignition temperature, pollution)',
      'Nuclear fission vs fusion (differences, examples, applications)',
      'Biogas production and its advantages over wood (clean, renewable, manure)',
      'Solar energy and its limitations (weather-dependent, large area needed)',
      'Greenhouse effect and global warming (causes and consequences)',
      'Difference between renewable and non-renewable energy sources',
      'Energy conservation and sustainable development',
    ],
  },
  {
    title: 'NCERT Boxed Points',
    icon: 'Box',
    items: [
      'A good source of energy should have high calorific value, be easy to store and transport, and produce minimal pollution.',
      'Fossil fuels are non-renewable and produce pollutants; their burning contributes to the greenhouse effect.',
      'Nuclear energy can produce enormous amounts of energy from small amounts of fuel, but the waste is hazardous.',
      'Biogas is a clean, renewable fuel produced by the anaerobic decomposition of animal dung and organic waste.',
      'Solar energy is the most promising renewable source, but solar cells are expensive and weather-dependent.',
    ],
  },
  {
    title: 'Memory Tricks',
    icon: 'Brain',
    items: [
      'Renewable: "SWIMBG" — Solar, Wind, (tIdal), (geo thermal), Bio, (hydro/Geothermal).',
      'Non-renewable: "Fossil fuels = Finite."',
      'Greenhouse gases: "CAMW" — CO₂, CH₄, (water vapour), N₂O.',
      'Nuclear: "Fission = Split (heavy → light), Fusion = Fuse (light → heavy)."',
    ],
  },
  {
    title: 'Exam Tips',
    icon: 'GraduationCap',
    items: [
      'Know the characteristics of a good fuel and be able to compare different fuels.',
      'Remember the key difference: fission splits heavy nuclei (U-235), fusion combines light nuclei (H → He).',
      'Be able to draw a labelled diagram of a biogas plant and explain the process.',
      'Know the advantages and disadvantages of each energy source (solar, wind, nuclear, biogas, hydro).',
      'Understand the greenhouse effect: CO₂ and CH₄ trap heat; more fossil fuel burning = more CO₂ = global warming.',
    ],
  },
];
